### ISSUE TITLE
please support latest node v20

### ISSUE THREAD

**Issue by born2net** [twilio/twilio-node#1009]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/twilio/twilio-node/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/twilio/twilio-node/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/twilio/twilio-node/issues) for a feature request that matches the one I want to file, without success.
- [X] This is not a general Twilio feature request or bug report. It is a feature request for the twilio-node JavaScript package.

### Problem Description

please support latest node v20

### Proposed Solution

right now when using node 20 we get
Call initiated: CA2f94 ....
so seems like all is working but NOTHING!

### Alternatives Considered

cannot go back to previous node

### Additional Information

none

**Comment by tiwarishubham635** [comment]
node v20 is already supported, see [here](https://github.com/twilio/twilio-node/blob/main/.github/workflows/test-and-deploy.yml#L20)

**Comment by bnb** [comment]
@born2net can you provide more context on how this is failing?

**Comment by born2net** [comment]
all goo now you can close as far as I am concerned.
