### ISSUE TITLE
programmatic twilio hook?

### ISSUE THREAD

**Issue by sandro-pasquali** [twilio/twilio-node#102]
Is it possible to set the sms/voice twilio hook via the library, rather than configuring it on the twilio interface?

**Comment by philnash** [comment]
Hey @sandro-pasquali, good news, that is possible. You need to update the number with the respective endpoint like this:

```javascript
var client = require('twilio')('ACCOUNT_SID', 'AUTH_TOKEN');
client.incomingPhoneNumbers('PHONE_NUMBER_SID').update({
  voiceUrl: NEW_VOICE_URL,
  smsUrl: NEW_SMS_URL
}, function(err, response) {
  // do something...
  console.log(response);
});
```

Let me know if that helps!

**Comment by sandro-pasquali** [comment]
Fantastic. Thanks!
