### ISSUE TITLE
[Feature Request]: official Node.js v22 support

### ISSUE THREAD

**Issue by electrovir** [twilio/twilio-node#1042]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/twilio/twilio-node/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/twilio/twilio-node/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/twilio/twilio-node/issues) for a feature request that matches the one I want to file, without success.
- [X] This is not a general Twilio feature request or bug report. It is a feature request for the twilio-node JavaScript package.

### Problem Description

Node.js v22 is now LTS: https://github.com/nodejs/node/releases/tag/v22.11.0

### Proposed Solution

Support Node.js v22. (Idk what work this requires.)

**Comment by manisha1997** [comment]
Hi, we will add the support for Node v22
