### ISSUE TITLE
Call started event ?

### ISSUE THREAD

**Issue by mFarghaly** [twilio/twilio-node#107]
I know this is not the right place to open this issue, but i couldn't find repo for twilio-js project.

In a nutshell is i am using Twilio client web and i want to show caller/callee timer when the call started. 
By 'call started' i mean the callee accepted the incoming connection.

![screenshot from 2015-07-19 17 12 18](https://cloud.githubusercontent.com/assets/108079/8766471/5e01ee0e-2e39-11e5-9a3d-28cfaba020fe.png)

The callee timer is shown when she accepts the incoming connection.
`The problem` is that there's no event i can listen to on the caller side to show the timer when call is accepted from the callee side !
Right now i am showing the caller the timer on .connect event which shows the timer during ringing and lead to `bad UX`.

**Comment by kwhinnery** [comment]
I think you're looking for [this event on the Twilio.Device object, right?](https://www.twilio.com/docs/client/device#connect-handler) - for further support, please e-mail help@twilio.com
