### ISSUE TITLE
Document error object

### ISSUE THREAD

**Issue by kevinburkeshyp** [twilio/twilio-node#109]
- What properties exist on the error object for normal 400-level exceptions?
- Say you get an unexpected error - server error, timeout, couldn't parse JSON, connection reset - what properties exist on the error object in that case? 

how can I distinguish the two?

**Comment by kwhinnery** [comment]
If Twilio sends a 4xx response, the body of the response is the `err` object. But your underlying request to document the behavior and contents of the error object is valid feedback.

**Comment by jingming** [comment]
All errors thrown by the library should conform to: https://github.com/twilio/twilio-node/blob/master/lib/base/RestException.js
