### ISSUE TITLE
add 2.0 Upgrade guide

### ISSUE THREAD

**Issue by kevinburkeshyp** [twilio/twilio-node#111]
Currently on 1.6.0. Does an upgrade guide exist? What breaks if I upgrade? I see a whole bunch of stuff around monitor/task router etc but wondering if core message flow changed at all

**Comment by kwhinnery** [comment]
The major version bump is due to paging changes that will change paging data properties in responses:

https://www.twilio.com/engineering/2015/04/16/replacing-absolute-paging-with-relative-paging

However, if you weren't using these properties, the rest of the API is unaffected.

**Comment by kevinburkeshyp** [comment]
Ah cool, good to know! Thanks!

On Tue, Jul 28, 2015 at 11:52 AM, Kevin Whinnery <notifications@github.com>
wrote:

> The major version bump is due to paging changes that will change paging
> data properties in responses:
>
>
> https://www.twilio.com/engineering/2015/04/16/replacing-absolute-paging-with-relative-paging
>
> However, if you weren't using these properties, the rest of the API is
> unaffected.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twilio/twilio-node/issues/111#issuecomment-125715854>.
>



-- 
kevin

**Comment by jingming** [comment]
We also have a `3.x.x` migration guide here: https://www.twilio.com/docs/libraries/node/migration-guide
