### ISSUE TITLE
npm ERR! 404 Not Found

### ISSUE THREAD

**Issue by iamwave007** [twilio/twilio-node#114]
I'm trying to install the module through package.json but it gives this error. What should I do please?

**Comment by iamwave007** [comment]
alright i solved my own problem.. so i did: 
    "twilio":"2.2.1"    vs.     "twillio":"2.2.1"

You guys did this on purpose didn't you

**Comment by philnash** [comment]
Glad you solved it! I'm pretty sure we didn't pick the name to mess with you (in fact, we released a video recently on [how the company got the name Twilio](https://www.youtube.com/watch?v=7vgxu8ONOdY) and none of it was to mess with installing libraries! :laughing: 

It may be why our logo font is so thick though, it's easier to see only one "L" in the middle then!

**Comment by iamwave007** [comment]
haha, thanks! i will see when i get back there.
