### ISSUE TITLE
Where is support for Nouns like Number?

### ISSUE THREAD

**Issue by rlaferla** [twilio/twilio-node#115]
Where is support for Nouns like Number?

**Comment by philnash** [comment]
You can nest nouns like `Number` in TwiML with this helper library as follows:

```javascript
var twilio = require("twilio");
var resp = new twilio.TwimlResponse();
resp.dial(function(){
  this.number("+447719532208");
});
```

There's more information on [nesting TwiML in the documentation](http://twilio.github.io/twilio-node/#twimlNesting).

Let me know if this helps!

**Comment by rlaferla** [comment]
Thanks.  But where is the documentation on what nouns are available, how to construct them and what parameters/options they take?

**Comment by philnash** [comment]
The documentation is all on the Twilio website. You can find the full TwiML reference here: https://www.twilio.com/docs/api/twiml. All the nouns and verbs are available as defined within that documentation, the available attributes for each noun are there too.

You construct them as per the example. You create a `TwimlResponse()` and call the downcased verb method, `dial` in my case. You can then pass an object with attributes for the verb and either a string or, if you can nest more TwiML within the verb, a function. My example above shows nesting a `Number` noun using `this`. That's pretty much all there is to it, the bulk of the docs are just the TwiML docs that I linked above.

Does that help?

**Comment by rlaferla** [comment]
Thanks again.

**Comment by philnash** [comment]
Give me a shout if there's anything else I can help with!
