### ISSUE TITLE
160 character limit for 1600 character resource (sending text messages)

### ISSUE THREAD

**Issue by bjones6** [twilio/twilio-node#120]
According to your documentation (https://www.twilio.com/docs/api/rest/sending-messages) text messages using the most recent Twilio API have a size limit of 1600 characters. 

However whenever I try to send a message over 160 characters (the old limit supposedly) I receive the following error:

"message": "The message body exceeds the 160 character limit.",
"code":21605",
"moreInfo":"https://www.twilio.com/docs/errors/21605"

I am using the nodeJS helper library and making the exact same call as the documentation described (again https://www.twilio.com/docs/api/rest/sending-messages)).

Is it possible the Twilio nodeJS library is using the old API call and the documentation is incorrect?

**Comment by bjones6** [comment]
Upon further investigation it appears the Twilio-node API does use the newer messages API, making the error a little more peculiar.

**Comment by philnash** [comment]
@bjones6 Could you post the code you are using that is causing this error? Thanks!

**Comment by bjones6** [comment]
Sure thing:

*  Library version (via package.json): "twilio": "^2.3.0"
* {"status":400,"message":"The message body exceeds the 160 character  limit.","code":21605,"moreInfo":"https://www.twilio.com/docs/errors/21605"}

And the code itself: 

// suffice to say the client credentials are correct
var client = require('twilio')(config.twilio.accountSid, config.twilio.authToken);

client.sms.messages.create({ 
    to: "+16504547270"    , 
    from: "+14153199805",
    body: body // where body is a 1234 character keyboard mashing
}, function(error, message){
   // ...
});
```

**Comment by ryan-rowland** [comment]
It looks like `client.sms.messages.create` is using the deprecated `/Accounts/{sid}/SMS/Messages` resource.

@bjones6 You can use client.sendMessage() for now.

**Comment by bjones6** [comment]
Hmm. This is the code I saw when I checked out https://github.com/twilio/twilio-node/blob/master/lib/resources/Messages.js.

```javascript
var baseResourceUrl = '/Accounts/' + accountSid + '/Messages';

    //Instance requests
    function Messages(sid) {
        var resourceApi = {
            get:generate(client, 'GET', baseResourceUrl + '/' + sid),
            post:generate(client, 'POST', baseResourceUrl + '/' + sid),
            delete:generate(client, 'DELETE', baseResourceUrl + '/' + sid)
        };
```

Am I interpreting it wrong? It seems to call the newer API.

**Comment by ryan-rowland** [comment]
If you look at where `.sms` is defined:
```
  sms: {
    messages:ListInstanceResource(client, sid, 'SMS/Messages',
      ['GET'],
      ['GET', 'POST', {create:'POST'}]
    ), /...
```

You'll see it's calling `ListInstanceResource`. If you inspect this method closely you'll see the URL being overridden:

```
var baseResourceUrl = '/Accounts/' + accountSid + '/' + resourceName;
//...
 Resource.baseResourceUrl = baseResourceUrl;
```

**Comment by bjones6** [comment]
Gotcha, thanks for the timely response.

**Comment by bjones6** [comment]
Would like to report client.sendMessage() does indeed call the new api (with the 1600 character limit), 

And just a polite reminder the docs (https://www.twilio.com/docs/api/rest/sending-sms) point to client.sms.messages.create() (with only a 160 character limit).

**Comment by philnash** [comment]
Glad this got sorted, going to close now.

@bjones6 The docs you point out are the docs for the old SMS/Messages resource. There is a note at the top of the documentation the explains the deprecation of the endpoint and points to the newer Messages resource.
