### ISSUE TITLE
A problem about Chinese number support

### ISSUE THREAD

**Issue by wp2123** [twilio/twilio-node#121]
Hello, I'm a Chinese user.I've tried several times to send a sms to a Chinese number which was 86 1760080***_, but everytime I got was the 400 error.The error message said that this number was invalid.
I'm confident that I use the API correctly because I can send sms to myself(86 1863014**_*).So, I hope you can help me to resolve the problem.
Thanks a lot.

PS: The number start with 176 in China is relatively new.So I guess the rule you detect if the number is a phone number is ancient.

I'm looking forward to receive your reply.Thanks again.

**Comment by jingming** [comment]
@wp2123 are you still seeing this problem? If so, please follow up with help@twilio.com and one of our support agents will be happy to assist you!
