### ISSUE TITLE
Break new line with long sms

### ISSUE THREAD

**Issue by ga12ru12** [twilio/twilio-node#122]
I send a sms with content like that:"Hi all\nThank you very much for....".
If my content is short, everything is ok. The sms of receiver like this:
"Hi all
Thank you very much for...." 
If my content too long. The sms of receiver have one line, like this: '
'Hi allThank you very much for...."
What 's happened? Anyone can help me please? 
Thanks

**Comment by jingming** [comment]
@ga12ru12 if you are still experiencing this issue, please redirect to help@twilio.com
