### ISSUE TITLE
Phone numbers filtering by app_id options doesn't seem to work.

### ISSUE THREAD

**Issue by Gargol** [twilio/twilio-node#124]
While going through the documentation on [twilio](https://www.twilio.com/docs/api/rest/incoming-phone-numbers) found an option to filter `incomingPhoneNumbers.list` by `VoiceApplicationSid`. Tried to use it in a couple of ways like so:

```javascript
client.incomingPhoneNumbers.list({ 'voiceApplicationSid': twilioConfig.APP_ID }, function (err, data) {
  // handling here
});

// or
client.incomingPhoneNumbers.list({ 'VoiceApplicationSid': twilioConfig.APP_ID }, function (err, data) {
  // handling here
});

// or
client.incomingPhoneNumbers.list({ 'voice_application_sid': twilioConfig.APP_ID }, function (err, data) {
  // handling here
});

// or
client.incomingPhoneNumbers.list(twilioConfig.APP_ID, function (err, data) {
  // handling here
});
```
None of these seem to work. Any idea if that is functionality that is available through twilio client or not ? Thanks for great library!

**Comment by philnash** [comment]
Hey @Gargol,

I'm not sure how you're reading the docs there, but the only filters are `PhoneNumber`, `FriendlyName` and `Beta`. You can see them documented here: https://www.twilio.com/docs/api/rest/incoming-phone-numbers#list-get-filters.

You are able to set or update the `VoiceApplicationSid` on a number, but not filter by it.
