### ISSUE TITLE
The From phone number +15005550006 is not a valid, SMS-capable inbound phone number or short code for your account

### ISSUE THREAD

**Issue by shahp00ja** [twilio/twilio-node#125]
I using a test account and trying to test SMS 
but it throws-
```
{ status: 400,
  message: 'The From phone number +15005550006 is not a valid, SMS-capable inbound phone number or short code for your account.',
  code: 21606,
  moreInfo: 'https://www.twilio.com/docs/errors/21606' }
```
According to the doc, only number usable in From is " +15005550006" then why does it throw the error? 
https://www.twilio.com/docs/api/rest/test-credentials#test-sms-messages-parameters-From   
 What else can be used in test account?

**Comment by shahp00ja** [comment]
+ @philnash : any change in test mobile number or anything i'm doing wrong ?                                                   this is my code   ```
var client = new twilio.RestClient(TWILIO_ACCOUNT_SID, TWILIO_AUTH_TOKEN);
client.sms.messages.create({
    to:'+918123981812',
    from:'+15005550006',
    body:'ahoy hoy! Testing Twilio and node.js'
}, function(error, message) {
   
    if (!error) {
        console.log('Success! The SID for this SMS message is:');
        console.log(message.sid); 
      console.log('Message sent on:');
        console.log(message.dateCreated);
    } else {
        console.log('Oops! There was an error.');
        console.log(error);
    }
});
```

**Comment by jarodreyes** [comment]
@shahp00ja I just ran into this error myself so I'll just jump in here real quick. In order to send a test sms using the Twilio test numbers, you need to make sure you are using your test credentials. From the looks of this code it seems you may be using your actual credentials.

To find your test credentials login to twilio.com and go to this link: https://www.twilio.com/user/account/developer-tools/test-credentials

Hope this helps!

**Comment by philnash** [comment]
Cheers @jarodreyes, that looks like the case to me too.

**Comment by carlosdp** [comment]
I'm going to close this issue since it looks resolved / isn't a bug with the library. Thanks @jarodreyes !

**Comment by shahp00ja** [comment]
@jarodreyes : awesome! thank you. Wondering how come I was not using these [the dashboard where I was trying, actual credentials were populated and so never got the idea of checking if those credentials were different ] , now I get success message, though didn't receive any sms [ IST ], is that not free for a test account with some free credits ?

**Comment by philnash** [comment]
@shahp00ja The test credentials are there to make sure that your requests are working as expected, however they do not send messages. So that is expected.

However, with your free account you can buy a number, use your real credentials and send a real SMS message that you will then receive on your phone. Give that a go and see how you get on.

**Comment by apoca** [comment]
hum unfortunately i ave the same error, and I'm using the test credentials..

**Comment by philnash** [comment]
@apoca What is the code you are using?

**Comment by apoca** [comment]
Case sensitive problem... Now it's working. Tks

**Comment by florence-smc** [comment]
WHAT WAS THE CODE??????? Running into the same error even after using the test credentials. HALP.

**Comment by philnash** [comment]
@florence-smc What code are you using? Maybe we can work it out if you share yours?

**Comment by arpitsethi** [comment]
I faced the same problem and then used the test credential. I am getting the response but sms is not actually delivered. Don't Twilio provide some credits so that we can test it end to end.

**Comment by efossier** [comment]
@arpitsethi Using the test credentias does not actually send an sms, it just lets you test making a request to the API. You need to use your actual creds and buy a phone number to be able to send an sms.

https://www.twilio.com/docs/api/rest/test-credentials

**Comment by Sanjay-pujari** [comment]
I'm using test credentials and trying to send SMS on Indian number. I'm not getting any error message but din receive any message on my mobile number

**Comment by philnash** [comment]
@Sanjay-pujari Using test credentials will respond as if a message was sent, but it won't actually send the message to your phone. As the [documentation says](https://www.twilio.com/docs/api/rest/test-credentials):

> You use these credentials in the same way as your live credentials. However, when you authenticate with your test credentials, **we will not charge your account, update the state of your account, or connect to real phone numbers.** You can now pretend to buy a phone number, or send an SMS, without actually doing so.

On the other hand, if you are receiving a [30008 error code](https://www.twilio.com/docs/api/errors/30008) that means that you made the API call correctly but the message delivery failed for unknown reasons. First up, I'd recommend you read through the [guidelines for sending SMS to India](https://www.twilio.com/sms/guidelines/in) and the [limitations of sending SMS to Indian mobile devices](https://support.twilio.com/hc/en-us/articles/223134167-Limitations-sending-SMS-messages-to-Indian-mobile-devices). If nothing there covers what you are doing, then please get in touch with [Twilio support](https://www.twilio.com/help/contact) with at least 3 message SIDs of messages that failed with a 30008 error code and they can try to track down the issue.

**Comment by dengere** [comment]
april 19, 2018. :)  I got same exception and message. I've used test credentials.

**Comment by ptimson** [comment]
I had to remove the `messagingServiceSid` to get it to work

**Comment by olyjosh** [comment]
I had the same error while I'm using test credentials with my verified phone number.
I latter got to know it's as a result of my **from** number which I use thesame number I registered for test. So I latter got it working by changing from number to **"+15005550006"**

**Comment by Ashalu** [comment]
In my case test credentials work properly with magic no. but in case of actual credential  it through error  with real no.

**Comment by krishnachandu** [comment]
![screen shot 2019-01-15 at 1 26 00 pm](https://user-images.githubusercontent.com/12947159/51208171-25507100-18ca-11e9-9180-c13ef6d96990.png)

This is the code snippet im using
i m using the test credentials i see at console page:

https://www.twilio.com/console

and the from account number i see at

https://www.twilio.com/console/phone-numbers/incoming

But i see an error message that

Unable to create record: The From phone number +15093599573 is not a valid, SMS-capable inbound phone number or short code for your account.

Can you please let me know the issue.
Moreover i've verified my TO phone number which is mine

**Comment by imthepitts** [comment]
@krishnachandu you should recycle your Auth Token since it was distributed in the first draft of your comment. 

https://www.twilio.com/console/project/settings 

Then please contact the Support team for help with the error you're seeing (most likely using your Test Credentials instead of Live Credentials).

https://www.twilio.com/help/contact 

All the Best,
Zack

**Comment by janat08** [comment]
This is an error bug, it doesn't mention the possibility of error occuring as result of test and real credentials/numbers being used.

**Comment by childish-sambino** [comment]
@janat08 I think the behavior is documented pretty well here: https://www.twilio.com/docs/iam/test-credentials

Given that the idea for using these test credentials and APIs is to simulate responses that you'd get when using live credentials, I don't agree that the error should add more information when using or not using test credentials.

**Comment by janat08** [comment]
Even by that logic mixing test/live credentials and apis is an error youre suppose to announce.

**Comment by childish-sambino** [comment]
@janat08 Maybe I'm not understanding. The error codes the API will return for test credentials are documented [here](https://www.twilio.com/docs/iam/test-credentials#test-sms-messages-parameters-From) and are based on the to/from number.

Are you saying that using test credentials with a non-test phone number should give an error about using test credentials?

**Comment by janat08** [comment]
It already does that only that error message is currently lying.

**Comment by childish-sambino** [comment]
@janat08 Are you saying that this error message is incorrect?

> The From phone number +15005550006 is not a valid, SMS-capable inbound phone number or short code for your account.

If you're using live credentials, I see that as a valid error message because the phone number is really not part of your account.

**Comment by janat08** [comment]
So then you should say "If you're using live credentials, I see that as a valid error message because the phone number is really not part of your account.

**Comment by janat08** [comment]
Instead of providing what is tantamount to 500 error and then qualifying that in GitHub issues because youre then justified for providing shit API.
