### ISSUE TITLE
documentation has no mention of how to send a dial response

### ISSUE THREAD

**Issue by coolaj86** [twilio/twilio-node#13]
I'm trying to create a server that forwards the call with the twilio number in the callerId so that the person receiving the call knows it's a business call (and to answer appropriately).

The documentation makes no mention of TwimlResponse in relation to Dial, Number, callerId, record, etc... and just looking over the code it's unclear to me.

(The raw xml I tried responds with an application error, so I figured trying the node api response object would be a good idea)

**Comment by jingming** [comment]
@coolaj86 if this is still applicable, we have redesigned to our TwiML generation code to be much more developer friendly with docs describing each Verb! You can find the classes here: https://github.com/twilio/twilio-node/blob/master/lib/twiml/VoiceResponse.js and https://github.com/twilio/twilio-node/blob/master/lib/twiml/MessagingResponse.js
