### ISSUE TITLE
ability to set proxy as option

### ISSUE THREAD

**Issue by msierks** [twilio/twilio-node#137]
Is it possible to set the proxy as an option ? Currently it seems the client library only looks for the HTTP_PROXY env var.

**Comment by MTempsNH** [comment]
+1

**Comment by jmctwilio** [comment]
@msierks @MTempsNH 

With the newest version of the library, you should be able to pass in your own RequestClient when constructing the Twilio client if you're regularly building the client.  Alternatively, you should be able to pass in some configuration options.  Please see this exchange on StackOverflow: https://stackoverflow.com/questions/3862813/how-can-i-use-an-http-proxy-with-node-js-http-client

However, I believe that this only works if your proxy doesn't require SSL itself as it becomes another issue entirely to issue CONNECT requests over SSL to the proxy and then forward to the server.
