### ISSUE TITLE
Moving to node v4.* and ES6

### ISSUE THREAD

**Issue by sheppardv** [twilio/twilio-node#143]
Do you have some plans to moving to new version of NodeJS and ES6 ?

**Comment by Ragil** [comment]
Are you facing any specific issues when using v4 and es6?

**Comment by sheppardv** [comment]
Nope, I'm asking just for rewriting with new js syntax like classes and so on. That could make it more readable. Don't you think so?

**Comment by Ragil** [comment]
It has been on our radar but no concrete plans as of yet. Let us know if you encounter version specific issues.
