### ISSUE TITLE
Invalid directory /crypto

### ISSUE THREAD

**Issue by jessahouano** [twilio/twilio-node#144]
After installing twilio-node and using var client = require('twilio')(accountSid, authToken), this appears.

![simulator screen shot jan 13 2016 5 05 25 pm](https://cloud.githubusercontent.com/assets/4317355/12289707/eae2be6a-ba17-11e5-8451-693c01536768.png)

**Comment by Ragil** [comment]
Hi @jessahouano,

What version of node are you running? Also what OS?

**Comment by jessahouano** [comment]
Hi @Ragil ,

I'm running node v5.2.0 on OS X Yosemite 10.10.5

**Comment by Ragil** [comment]
@jessahouano You might have a bad install of node. Can you try running `require('crypto');` in node.
If that causes an error, try re-installing node.

**Comment by jessahouano** [comment]
@Ragil I already re-installed my node to a stable version(v5.6.0) but the issue still occur.

**Comment by carlosdp** [comment]
@jessahouano it looks like you are using the library in React Native, which uses a different JS engine. You would need to raise this issue in the React Native support channels to see why `crypto` doesn't seem to work!

**Comment by carlosdp** [comment]
@jessahouano also, what exactly are you trying to use the Twilio library for here?

**Comment by jessahouano** [comment]
@carlosdp I would like to send a message via Twilio for number verification which I needed for my React Native app. I tried Twilio api but it won't work so I was hopeful twilio-node will do the job for me.

**Comment by carlosdp** [comment]
@jessahouano the twilio-node library is intended to be used in a server-side application. It won't work in browser/client apps, such as React apps. You'd need to create a Node web service to make the number verification happen and then have your React Native app connect to that.

**Comment by jingming** [comment]
Answered.

**Comment by RUIFERNANDE5** [comment]
@jessahouano have you come up with a solution?
I need to access Twilio.Device in react-native
