### ISSUE TITLE
Use `request.hostname`, not `request.headers.host`

### ISSUE THREAD

**Issue by 907th** [twilio/twilio-node#151]
I think it should be `request.hostname` instead of `request.headers.host` [in this line](https://github.com/twilio/twilio-node/blob/master/lib/webhooks.js#L41).

**Comment by 907th** [comment]
The difference is that Express respects `trust proxy` setting and `X-Forwarded-*` headers in `request.hostname` and `request.protocol` methods. See [docs](http://expressjs.com/en/guide/behind-proxies.html).

**Comment by 907th** [comment]
I can create a PR if you agree.

**Comment by carlosdp** [comment]
Nice catch, yea if you could create a PR that would be great.

**Comment by 907th** [comment]
@carlosdp Oh, it appears to be a difficult problem to just switch to `request.host(name)`.
The issue is that old `request.headers.host` (which just returns `Host` header) preserves port information (if any), e.g. for http://localhost:3000 browser will send `Host: localhost:3000` header. But `request.host(name)` omits port portion (but respects `X-Forwarded-*` headers on other side).

So if we decide to use `request.hostname` then all users using explicit ports in their callback urls should specify either `{ url: ... }` or `{ port: ... }` options when calling `validateExpressRequest()`. I don't know a way to make `validateExpressRequest` 'just work' without any explicit options when people uses proxies and/or custom ports.

**Comment by modeswitch** [comment]
This has changed in Express v5, and the issue with `req.hostname` not including the port was apparently a bug. See https://expressjs.com/en/guide/migrating-5.html#req.host for full details.

**Comment by jmctwilio** [comment]
Closing this issue as the library currently uses a version of Express with the bug.  If and when we update to Express v5+, we can update the handling for webhooks.
