### ISSUE TITLE
Parse.com outdated module : Unable to complete HTTP request

### ISSUE THREAD

**Issue by Tibabal** [twilio/twilio-node#152]
Hi,

Parse.com uses an old version of Twilio module. Since a few hours, this outdated version doesn't work anymore. Is this possible to provide back backward-compatibility as it used to work until today ?
That's not really possible for us to migrate now to Parse-Server (and so, with an updated Twilio module).

Thanks !

Edit : As @hramos pointed out, Parse.com is not using official Twilio npm module. I leave this message hoping someone at Twilio will try to update server to provide back compatibility...

**Comment by carlosdp** [comment]
So we didn't change anything server side to cause any incompatibility... Could you be more specific about the problem? You're saying this *isn't* the official library?

**Comment by Tibabal** [comment]
Sure and thanks for answering !
As some users are beginning to complain on [Twitter](https://twitter.com/search?f=tweets&vertical=default&q=twilio&src=typd) , Twilio module in Parse.com CloudCode (which as said by one of its contributor @hramos, is not the official one but probably a modified version to fit there needs) now returns

    {"status":0,"message":"Unable to complete HTTP request"}

when calling `twilio.sendSms`
It used to work until some hours ago

**Comment by hramos** [comment]
If they're using the built-in Twilio Cloud Code Module in Parse (e.g. via `require('twilio')`), then they're not using the one from this repository. The Twilio Cloud Code module has not been updated in the last 3 years. We've been recommending that people switch to using `twilio-node` instead.

Cloud Code is not Node.js but many npms can be adapted to work in Cloud Code with minimal effort. 

In any case, this is solved by migrating to Parse Server, which being a node module, should work with `twilio-node` without any modification.

**Comment by jbredice** [comment]
Based on Hector's answer we understand that Parse Twilio module is not an officially supported module from Twilio.  Still - something changed today.  Twilio peeps: should at least be able to see these formerly successful requests hitting your API and generating errors, yes?

**Comment by Tibabal** [comment]
`Twilio-node` could indeed be adapted by including all dependencies recursively, and updating all `require` to relative path for it to be includable to Parse.com CloudCode, but that's quite an effort to do, and I'll do it only on last resort.
Migrating to parse-server is of course what'll be done in the end, but as Parse.com recommends it itself [here](https://github.com/ParsePlatform/parse-server/wiki/Migrating-an-Existing-Parse-App) :

> We recommend the following schedule:
> 
> April 28, 2016: Data migrated to a self-hosted MongoDB (Step 1)
> July 28, 2016: Finish setting up your self-hosted Parse Server and release a new app pointing to it (Steps 2-12)

So everyone (including me) hasn't finished all the migration process yet, and this mainly because of many bugs still present in last Parse-Server release.

**Comment by hramos** [comment]
You can also use Parse's webhooks to redirect a specific Cloud function to a Node.js server where you can use the official Twilio npm. No need to fully migrate to Parse Server when using that approach.

**Comment by Tibabal** [comment]
@hramos Good suggestion, I'll probably use that solution in case Twilio's team can't resolve this :+1:

**Comment by carlosdp** [comment]
We think we might know what is causing this, not a change on our side, but we're going to try and see if we can do something to fix this on our end in a few minutes.

**Comment by hollaholla** [comment]
👍@carlosdp we are down as well

**Comment by nsarafa** [comment]
Same here. Keeping an eye on this thread for news on the fix

**Comment by hramos** [comment]
FYI, here's the related issue opened on Parse's bug tracker: https://developers.facebook.com/bugs/1696266953962575/

**Comment by jbredice** [comment]
Ahhh...  Expiring cert issue?  Now it makes sense that nobody changed anything today but somehow it broke.  :)

**Comment by carlosdp** [comment]
This might be fixed now, could someone try again and report back here please? Thanks!

**Comment by hollaholla** [comment]
Fixed!

**Comment by carlosdp** [comment]
Excellent, thanks guys! We believe Parse's servers changed their CA store to one that didn't trust our current certificate. We by coincidence had a cert change scheduled for today anyways, so this should work fine now.

**Comment by jbredice** [comment]
Yep.  Working again...  Thanks Carlos!!!

Thanks also Hector: you're always on top of this stuff.

**Comment by hramos** [comment]
Thanks @carlosdp! Let me know if there's any followup required on our side.

**Comment by Tibabal** [comment]
Thanks a lot @carlosdp and @hramos for your reactivities, that's fixed by now !

**Comment by carlosdp** [comment]
@hramos should be fine, you guys were good actors, we technically had a less-than-trusted cert. (CA root stores are weird)

**Comment by carlosdp** [comment]
Hey guys, unfortunately, we had to rollback our cert chain from earlier today. If nothing changed on Parse's side, Parse apps might have trouble connecting to Twilio again.

We're going to investigate this more tomorrow, but in the meantime if you are somehow able to direct your requests to https://api.twilio.com:8443, you should be able to use the API with a cert Parse trusts.

Please let me know here if you see this error regress in your apps. Thanks!

**Comment by Tibabal** [comment]
@carlosdp Same error than yesterday now...
Unfortunately, we can't change your API endpoint, and I think that Parse won't do this neither :-/
@hramos  ?

**Comment by carlosdp** [comment]
@Tibabal it doesn't let you change the port anywhere right?

**Comment by Tibabal** [comment]
@carlosdp Right, the only thing we can do is require('twilio'), as far as I know

**Comment by jessalfredsen** [comment]
Having the same issue here. Would really like to see a solution to this.

**Comment by Perviking** [comment]
I'm also looking for a solution. Currently all new users can't sign up :(

**Comment by Helmikku** [comment]
Hey,

I was facing the same issue but the port fix did the job for me!
I don't use parse's old Twilio Cloud Code Module, for it is out to date. You can use the httpRequest tool though. Here is an example for sending SMS (sorry for the code's look, I don't know how to display spaces or tabs):

`Parse.Cloud.httpRequest({`
`    method: "POST",`
`        url: "https://{your AccountSID}:{your AuthToken}@api.twilio.com:8443/2010-04-01/Accounts/{your AccountSID}/{if test credential insert 'SMS/'}Messages.json,`
`        body: {`
`            To: "phoneNumber",`
`            From: "+15005550006",`
`            Body: "message"`
`        }`
`    }).then(`
`    function(httpResponse) {`
`            console.log(httpResponse.text);`
`        },`
`        function(httpResponse) {`
`            console.log(httpResponse.text);`
`        }`
`    );`
`}`

**Comment by fishandphil** [comment]
Same issue on our side. No one can sign-up to our app..

**Comment by fishandphil** [comment]
Helmikku answer worked for us. Thank you (y)

**Comment by cpolo** [comment]
Having the same issue. We are trying to apply Helmikku solutions... but parse please, it'd be nice if you keep things working while we do all the migration... :-S

**Comment by nsarafa** [comment]
@cpolo doesn't look like it's on Parse. Something similar happened earlier yesterday and @carlosdp was quick to implement a hot fix. Hopefully, they come through again with another patch.

**Comment by cpolo** [comment]
Yeah, but carlos said they rolled it back, right? Anyhow, we applied Helmikku solution and it seems to be working now. Thanks guys.

**Comment by jessalfredsen** [comment]
@Helmikku Thanks you so much. You solution works for us as well.

**Comment by Helmikku** [comment]
You're welcome :)
@carlosdp is the port fix a permanent solution? If not, can you tell us when we need to get back to the default port?

Thanks!

**Comment by magneticorb** [comment]
@Helmikku @carlosdp  Thanks for the fix - we were already going the HTTP request route but didn't include the port number previously. Adding the port number fixed this for us.

**Comment by seancrowe5** [comment]
@Helmikku thanks for the fix :+1:

**Comment by pocketdeveloper** [comment]
@Helmikku You're THE BOSS great fix, we lost hundreds of users because of this annoying bug. Thanks for the fix!

**Comment by jakeva** [comment]
@Helmikku ✌️Works for us too, thanks!

**Comment by carlosdp** [comment]
Hey again, thanks @Helmikku for posting the solution!

@nsarafa the problem *is* on Parse's side. They stopped trusting our SSL cert yesterday morning out of the blue. We attempted to remedy it for our customers on our side by upgrading our cert, and that worked. However, some non-Parse customers experienced problems with the new cert, so we had to rollback.

We can't do anything to fix this on our end at the moment without breaking those customers, so the burden is either on Parse to rollback their SSL change, or unfortunately on you guys to implement the fix @Helmikku posted.

**Comment by hramos** [comment]
Hey all, we're taking a look at this again on Parse's side. If you're affected by this, please subscribe to https://developers.facebook.com/bugs/1696266953962575/ so we can followup if we need more information.

**Comment by carlosdp** [comment]
Thanks for the note @hramos! I'll leave this issue open until this is resolved in case people come in here with the same issue.

**Comment by Hipolyto** [comment]
Thanks Helmikku

**Comment by skinp** [comment]
@carlosdp heads up, the root CA used for api.twilio.com's SSL cert was dropped from mozilla's cert bundle. Anyone that keeps their ca-certificates bundle up to date (as they should) will get those errors...

**Comment by carlosdp** [comment]
@skinp thanks, yea we're aware of the problem, which is why we were already going to switch the certs yesterday (the timing of the Parse issue was coincidental). we had to delay it because we need to give customers time to update their CA stores if they are running on an older one.

**Comment by hramos** [comment]
Thank you @skinp for rolling things back on our end. This should now be resolved.

**Comment by inakiabt** [comment]
In the meantime, we used AWS API Gateway + Lambda to proxy these Twilio calls.
Here is the Lambda function we use and an example of how to make a `sendSms` call from a Cloud Code function.
https://gist.github.com/inakiabt/569c974b59a6cb5736a6

If anyone can confirm that Cloud Code is working OK again would be great to rollback this temp fix.

**Comment by carlosdp** [comment]
It looks like Parse has reverted the store on their end so this should be resolved for now. Closing this issue.
