### ISSUE TITLE
Cannot list US numbers with AreaCode provided

### ISSUE THREAD

**Issue by terusus** [twilio/twilio-node#159]
A few days ago twilio-node started failing to list numbers in the US when an area code is provided.

Example:
```javascript
var options = {
  VoiceEnabled: true,
  SmsEnabled: true,
  AreaCode: 202
}
```

Error:
```json
{
  "status": 404,
  "message": "The requested resource /2010-04-01/Accounts/AC.../AvailablePhoneNumbers/US/Mobile.json was not found",
  "code": 20404,
  "moreInfo": "https://www.twilio.com/docs/errors/20404"
}
```

Or simply no numbers (local).

Exactly same options (with proper area code works for Canada). Exactly the same code worked a week ago.

Any ideas?

**Comment by jingming** [comment]
@terusus What version of the library are you using? Are you looking for Mobile numbers? According to the FAQ, Twilio does not have US Mobile number capabilities https://www.twilio.com/help/faq/phone-numbers/which-countries-does-twilio-have-phone-numbers-in-and-what-are-their-capabilities

**Comment by terusus** [comment]
2.9.0

I am looking for mobile and for local. Listing local numbers just returns an empty list for 202, 212...

**Comment by jingming** [comment]
We do not support US mobile numbers. If you are getting a empty list for `202`, `212`, etc. I imagine it is because there are no numbers available. For further questions there, please contact help@twilio.com.
