### ISSUE TITLE
Unable to update async

### ISSUE THREAD

**Issue by ssangani** [twilio/twilio-node#161]
Hey,

We have been using twilio version 2.3 for a while and recently wanted to update async to the latest (atleast upto v1.5) and I noticed there was a dependency conflict with form-data. I went through the modules tree and found twilio is dependent on request which in turn depends on v0.2 of form-data which in turn needs v0.9 of async.

I tried updating twilio to latest v2.9.1 which still depends as -> request v2.55.0 -> form-data v0.2.0 -> async v0.9.0

Is there a way I can update async to latest and preserve v0.9.0 for form-data, so it doesn't break twilio?

**Comment by jmctwilio** [comment]
@ssangani 

So sorry for the late response.  The team has been very busy for a long while now.  Although I'm sure you've already answered your question, I'll add a few resources here for others who come across this issue and close out the ticket.

https://github.com/npm/npm/issues/5499
https://www.npmjs.com/package/npm-install-version
