### ISSUE TITLE
Cannot submit multiple Type parameters to Lookups API

### ISSUE THREAD

**Issue by devinrader** [twilio/twilio-node#162]
_Note: These issues are for bugs and feature requests for the helper libraries. If you need help or support, please email help@twilio.com and one of our experts will assist you!_

Version: Latest
API Subdomain (api/taskrouter/ip_messaging): lookups
### Code Snippet

``` javascript
client.phoneNumbers( (req.query.number || req.body.number) ).get({
    type: ['carrier','caller-name']
}
```
### Exception / Log

```
No exception.  Just doesn't add the parameters to the Twilio API URI
```
### Steps to Reproduce
1. Use the code above, but provide a real phone number to the function.  
2. Execute code
3. See that Type parameters are not added correctly to the requested URL
   3.
### Feature Request

_If this is a feature request, make sure you search Issues for an existing request before creating a new one!_

**Comment by kevzettler** [comment]
Same issue there. The http endpoint expects two `Type` params

`https://lookups.twilio.com/v1/PhoneNumbers/6156?Type=carrier&Type=caller-name`

This library is limited by one key `{type: ...`  key

**Comment by jingming** [comment]
This feature should be supported in the `3.x.x` line of the library.
