### ISSUE TITLE
Issue with ':' in access token identity

### ISSUE THREAD

**Issue by jteplitz602** [twilio/twilio-node#166]
**Version: 2.9.1**
**API Subdomain (api/taskrouter/ip_messaging): AccessToken**

Including a ':' in an identity string causes all invites to that client to fail with no additional error information. The identity string is _not_ rejected, and the client is able to connect to the Programmable Video API, but can not invite other clients and cannot receive invites themselves.
### Code Snippet

``` javascript
let token = new AccessToken(SID, KEY, SECRET);
token.addGrant(myGrant);
token.identity = 'some string that contains a :';
let tokenStr = token.toJwt();
```

If the client connects to Twilio using the programmable video library using the above identity their connection will be successful, but all outgoing invites will fail with no specific reason and no incoming invites will be received.

**Comment by jingming** [comment]
@jteplitz602 are you still having this issue?

**Comment by jteplitz602** [comment]
I was a couple months ago. I changed my project to simple avoid colons so
unfortunately I don't know if it's still a problem.

**Comment by jmctwilio** [comment]
I believe this is an issue with ':' being used in contexts that consider it to be a reserved character.  I'll investigate and then forward to our documentation team.  As it's no longer an issue for you, I'll close the PR.
