### ISSUE TITLE
library samples not working

### ISSUE THREAD

**Issue by julianfrank** [twilio/twilio-node#171]
*Note: These issues are for bugs and feature requests for the helper libraries. If you need help or support, please email help@twilio.com and one of our experts will assist you!*
https://www.twilio.com/docs/libraries/node
None of the examples are working!

**Version:**
2.9.1
**API Subdomain (api/taskrouter/ip_messaging):**

### Code Snippet
```javascript
 // Twilio Credentials 
var accountSid = 'AC---<removed>'; 
var authToken = '905---<removed>'; 
 
var twilio = require('twilio');
var client = new twilio.RestClient(accountSid, authToken);

client.messages.create({
    body: 'Hello from Node',
    to: '+1---<removed>',  // Text this number
    from: '+1---<removed>' // From a valid Twilio number
}, function(err, message) {
    console.log(message.sid);
});
```

### Exception / Log
```
d:\Users\Johan\Documents\CloudCode\twilliotry>node trycall.js
D:\Users\Johan\Documents\CloudCode\twilliotry\trycall.js:6
var client = new twilio.RestClient(accountSid, authToken);
             ^

TypeError: twilio.RestClient is not a constructor
    at Object.<anonymous> (D:\Users\Johan\Documents\CloudCode\twilliotry\trycall.js:6:14)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:159:18)
    at node.js:444:3
```

### Steps to Reproduce
1.just run any of the explamples in this url...all are not working!
2.
3.

### Feature Request
_If this is a feature request, make sure you search Issues for an existing request before creating a new one!_

**Comment by kevinburke** [comment]
Do you have a file named twilio.js in your path? It might be overriding the
library load? What happens if you run console.log twilio

On Tuesday, June 14, 2016, Julian Frank <notifications@github.com> wrote:

> *Note: These issues are for bugs and feature requests for the helper
> libraries. If you need help or support, please email help@twilio.com
> <javascript:_e(%7B%7D,'cvml','help@twilio.com');> and one of our experts
> will assist you!*
> https://www.twilio.com/docs/libraries/node
> None of the examples are working!
>
> *Version:*
> 2.9.1
> *API Subdomain (api/taskrouter/ip_messaging):*
> Code Snippet
>
>  // Twilio Credentials var accountSid = 'AC---<removed>'; var authToken = '905---<removed>';
> var twilio = require('twilio');var client = new twilio.RestClient(accountSid, authToken);
> client.messages.create({
>     body: 'Hello from Node',
>     to: '+1---<removed>',  // Text this number
>     from: '+1---<removed>' // From a valid Twilio number
> }, function(err, message) {
>     console.log(message.sid);
> });
>
> Exception / Log
>
> d:\Users\Johan\Documents\CloudCode\twilliotry>node trycall.js
> D:\Users\Johan\Documents\CloudCode\twilliotry\trycall.js:6
> var client = new twilio.RestClient(accountSid, authToken);
>              ^
>
> TypeError: twilio.RestClient is not a constructor
>     at Object.<anonymous> (D:\Users\Johan\Documents\CloudCode\twilliotry\trycall.js:6:14)
>     at Module._compile (module.js:541:32)
>     at Object.Module._extensions..js (module.js:550:10)
>     at Module.load (module.js:456:32)
>     at tryModuleLoad (module.js:415:12)
>     at Function.Module._load (module.js:407:3)
>     at Function.Module.runMain (module.js:575:10)
>     at startup (node.js:159:18)
>     at node.js:444:3
>
> Steps to Reproduce
>
> 1.just run any of the explamples in this url...all are not working!
> 2.
> 3.
> Feature Request
>
> *If this is a feature request, make sure you search Issues for an existing
> request before creating a new one!*
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/twilio/twilio-node/issues/171>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAOSIzZlGiA2_V9d5BvAelyih8q46Lyqks5qLquPgaJpZM4I1UQy>
> .
>


-- 

--
Kevin Burke
925.271.7005 | kev.inburke.com

**Comment by kwhinnery** [comment]
I can confirm that the sample you provided does work with version 2.9.1 of the library, which you get by default when you `npm install twilio`. Would +1 Burke's suggestion to confirm you are indeed loading the Twilio module.

**Comment by julianfrank** [comment]
I changed the code after trolling your library...

Here is what finally worked:
// Twilio Credentials 
var accountSid = 'AC<removed>';
var authToken = '905<removed>';

var inspect = require('util').inspect

var client = require('twilio')(accountSid, authToken);
//[JF] The Returned object is a Rest Client and explicit call for Restclient fails...Also new is not accepted

console.log(inspect(client))

client.sendMessage({
//[JF] Original code in website had 'client.messages.create'...That does not work...
    body: 'Hello from JF Node',
    to: '+19372650725',  // Text this number
    from: '+1<removed>' // From a valid Twilio number
}, function (err, responseData) { //this function is executed when a response is received from Twilio

    if (!err) { // "err" is an error received during the request, if any

        // "responseData" is a JavaScript object containing data received from Twilio.
        // A sample response from sending an SMS message is here (click "JSON" to see how the data appears in JavaScript):
        // http://www.twilio.com/docs/api/rest/sending-sms#example-1

        console.log(responseData.from); 
        console.log(responseData.body); // outputs "word to your mother."

    }
})

I tried again today and it works....ok to close this issue
