### ISSUE TITLE
TwiML Dial Number

### ISSUE THREAD

**Issue by nthhtn** [twilio/twilio-node#172]
I'm building myself a click-to-call website that utilizes Twilio. After I configured in TwiML app and wrote Twilio JavaScript SDK client-side to make request to Twilio, then Twilio will make a POST request to this route of mine:

```
 app.post('/callcenter',function(req,res){    
    const twilio=require('twilio');
    var twiml=new twilio.TwimlResponse();
        res.type('text/xml');
        twiml.dial({},function(node){
            node.number('MY_PHONE_NUMBER');
        });
        res.send(twiml.toString());
 );
```

This is the most simplified use of Dial in REST API for TwiML that I want to respond to Twilio to make a call to MY_PHONE_NUMBER. But I always ended up hearing voice of "An error occured..." Please someone help me point out what did I do wrong in this route handler?

**Comment by dkundel** [comment]
Hi @nthhtn,

I'm trying to understand the full scenario. Are you planning to connect two physical phones with the press of a button like in [this example](https://www.twilio.com/docs/tutorials/walkthrough/click-to-call/node/express#0) or are you trying to allow someone to call you straight out of the browser (i.e. via WebRTC)?

Cheers!

**Comment by jingming** [comment]
@nthhtn are you still have trouble here?
