### ISSUE TITLE
Get list of incoming phone numbers

### ISSUE THREAD

**Issue by tobiasc** [twilio/twilio-node#173]
I cannot get a list of incoming phone numbers associated with the accountId (without IncomingPhoneNumberSid), as described in this REST call: https://www.twilio.com/docs/api/rest/incoming-phone-numbers#list

The use case is that I need to verify whether a given account has a specific incoming phone number associated with it. That means that I'd like the below code to work:

```
// Doesn't work
// https://www.twilio.com/docs/api/rest/incoming-phone-numbers#list
var twilio = require('twilio')(accountSid, authToken);
twilio.incomingPhoneNumbers().list().then(function (data) {
    console.log(data);
}, function (err) {
    console.log(err);
});

// Works
// https://www.twilio.com/docs/api/rest/incoming-phone-numbers#instance
var twilio = require('twilio')(accountSid, authToken);
twilio.incomingPhoneNumbers({IncomingPhoneNumberSid}).list().then(function (data) {
    console.log(data);
}, function (err) {
    console.log(err);
});
```

**Version:** 2.9.1
**API Subdomain (api/taskrouter/ip_messaging):** /2010-04-01/Accounts/{AccountSid}/IncomingPhoneNumbers
**Error Msg:** ```message: 'The requested resource /2010-04-01/Accounts/{AccountSid}/IncomingPhoneNumbers/undefined.json was not found'```

**Comment by philnash** [comment]
Hey @tobiasc,

You're right, the code you have does not work. However, if you remove the parentheses on the call to `incomingPhoneNumbers` it should just work!

The example from [our documentation](https://www.twilio.com/docs/api/rest/incoming-phone-numbers#list-get-example-1) looks like:

```javascript
var client = require('twilio')(accountSid, authToken);

client.incomingPhoneNumbers.list(function(err, data) {
    data.incomingPhoneNumbers.forEach(function(number) {
        console.log(number.phoneNumber);
    });
});
```

And your example should work if it looked like this:

```javascript
var twilio = require('twilio')(accountSid, authToken);
twilio.incomingPhoneNumbers.list().then(function (data) {
    console.log(data);
}, function (err) {
    console.log(err);
});
```

**Comment by tobiasc** [comment]
Thanks @philnash, that works great. Sorry, guess I didn't see I could switch the docs to Node.js, so I was looking at it with C#.
