### ISSUE TITLE
I've noticed a Synchronous API call in a constructor

### ISSUE THREAD

**Issue by export-mike** [twilio/twilio-node#186]
Hi I found this recently and was wondering what the reasoning for it is.

In a node server environment where the application is dealing with multiple concurrent requests its likely the server will block trying to load the resources code on the first attempt. require does do caching but in general its advised against using require within functions that run after startup time. 

https://github.com/twilio/twilio-node/blob/45858420688854494c2ed476a1997773c33a32a0/lib/RestClient.js#L28

May I suggest you move the require to top and reference it and do something like:

`````` JavaScript
var resource = require('./resource')```
function RestClient(sid, tkn, options) {
    options = options || {};
    RestClient.super_.call(this, sid, tkn, options.host, options.apiVersion, options.timeout);

    //REST Resource - shorthand for just "account" and "accounts" to match the REST API
    var accountResource = account(this);
//...

}```
``````

**Comment by jingming** [comment]
This has been addressed in `3.x.x` line of the library.
