### ISSUE TITLE
ability to release a purchased number... :(

### ISSUE THREAD

**Issue by export-mike** [twilio/twilio-node#187]
hi my app allows customers to buy lots of numbers but the api on twilio doesn't seem to document how to "release" a number.

Any info on this would be great.

Mike

**Comment by mplacona** [comment]
Hi, have a lok at this:

https://www.twilio.com/docs/api/rest/incoming-phone-numbers#instance-delete

The code for that can be found [here](https://github.com/twilio/twilio-node/blob/45858420688854494c2ed476a1997773c33a32a0/lib/resources/IncomingPhoneNumbers.js) and you just need to make a `DELETE` http request.

**Comment by export-mike** [comment]
so something like```export const releaseNumber = ({
  accountSid,
  numberSid
}) =>
  new Promise((resolve, reject) => {
    twilio(accountSid, TWILIO_AUTH_KEY)
    .incomingPhoneNumbers(numberSid)
    .delete((err) => {
      if (err) return reject(err);
      resolve();
    });
  });```

**Comment by philnash** [comment]
Hey @export-mike,

The Node library actually supports promises as well as callbacks so you don't need to wrap this up in your own promise. You should be able to do:

```javascript
export const releaseNumber = ({
  accountSid,
  numberSid
}) => twilio(accountSid, TWILIO_AUTH_KEY).incomingPhoneNumbers(numberSid).delete()
```

**Comment by immexerxez** [comment]
Just incase anyone references this issue in the future delete has been changed to remove:

`export const releaseNumber = ({
  accountSid,
  numberSid
}) => twilio(accountSid, TWILIO_AUTH_KEY).incomingPhoneNumbers(numberSid).remove()`
