### ISSUE TITLE
Searching for GB numbers by "begins with term"?

### ISSUE THREAD

**Issue by export-mike** [twilio/twilio-node#191]
Hi 

I notice the docs provide information on searching for telephone numbers by area code but according to the docs its only supported for USA? 

I'm using the nearNumber property which does return results but no way near as helpful as the results I get when entering the same number into the twilio dashboard manually.

The dashboard seems to have a way to search by ``` Search Term Match: begins with term``` I'd like to do the same search but via the API.

**Comment by philnash** [comment]
Hey @export-mike,

I'm not sure if this is the way that the dashboard does it, but you can search by a pattern which can be forced to make it work like a begin with search.

[Example 2 for the available phone numbers resource is a good example of this](https://www.twilio.com/docs/api/rest/available-phone-numbers#local-get-basic-example-2).

Give that a go and let me know how you get on.

**Comment by export-mike** [comment]
works like a dream! 👍
