### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by newtriks** [twilio/twilio-node#193]
It would appear that the JWT object generated by this library does not include a `scope` key/value which is expected by the JS SDK for setup? 

**Version:**
**API Subdomain (api/taskrouter/ip_messaging):**

Twilio: `2.10.0`
JS: `media.twiliocdn.com/sdk/js/client/v1.3/twilio.js`
### Code Snippet

``` javascript
var accountSid = 'AC***';
var apiKeySid = 'SK***';
var apiKeySecret = '***';
var serviceSid = 'IS***';
var identity = 'user@example.com';

const token = new AccessToken(apiKeySid, accountSid, apiKeySecret);
const endpointId = 'ip-messaging-demo:' + identity + ':demo-device';

const ipmGrant = new IpMessagingGrant({
  serviceSid: serviceSid,
  endpointId: endpointId
});


token.addGrant(ipmGrant);
token.identity = identity;

console.log(token.toJwt());
```
### Exception / Log

```
twilio.js:3933 Uncaught TypeError: Cannot read property 'length' of undefined

  objectize @ twilio.js:3933
  (anonymous function) @ twilio.js:3839
  Device @ twilio.js:786
  setup @ twilio.js:1249
  handleToken @ (index):21
  o @ jquery.min.js:2
  fireWith @ jquery.min.js:2
  w @ jquery.min.js:4
  d @ jquery.min.js:4
```

<img width="638" alt="screen shot 2016-09-03 at 08 16 25" src="https://cloud.githubusercontent.com/assets/31971/18224330/6da9d5e0-71c9-11e6-92b3-0c4629abe9e1.png">
### Steps to Reproduce
1. Generate token using above steps with `twilio-node` library. 
2. Confirm token in UI and run `Twilio.Device.setup(token);` (JWT signature verified using: https://jwt.io).
3. Generates error above.

**Comment by katafractari** [comment]
I have the same problem using SDK for Java (7.3.0). May I ask what's the status on this one?

**Comment by jingming** [comment]
@newtriks I think you might be using the wrong JWT. If you are looking for the JWT that includes `scope`, please use https://github.com/twilio/twilio-node/blob/master/lib/jwt/ClientCapability.js
