### ISSUE TITLE
What is the method to create a phone call with rc13

### ISSUE THREAD

**Issue by wayofthefuture** [twilio/twilio-node#196]
Looking for docs to create a phone call for RC13 3.0.0.

Thanks

**Comment by philnash** [comment]
There are a bunch of [examples in this file](https://github.com/twilio/twilio-node/blob/next-gen/examples/example.js) of making different things happen with the API, though creating a call isn't there.

To make a call using the version 3 release candidate you need to do the following:

```javascript```
var accountSid = process.env.TWILIO_ACCOUNT_SID;
var token = process.env.TWILIO_AUTH_TOKEN;

var twilio = new Twilio(accountSid, token);

twilio.calls.create({
  from: YOUR_TWILIO_NUMBER,
  to: THE_NUMBER_YOU_ARE_CALLING,
  url: "https://example.com/voice"
}).then(function(call) {
  console.log(call.sid);
}).catch(function(err) {
  console.error(err);
});
```

If you're looking for more information on making calls with the API in general, check out the [documentation on making calls](https://www.twilio.com/docs/api/rest/making-calls).
