### ISSUE TITLE
Notify Service Update Input Validation Error

### ISSUE THREAD

**Issue by sschadwick** [twilio/twilio-node#197]
Trying to update a Notify Service:
`client.notify.services('ISxxx').update({messagingServiceSid: null, friendlyName: 'newName'})` 

fails with `TypeError: Cannot read property 'name' of null`.

Seems that node-twilio doesn't like receiving a null entry for messagingServiceSid even though .list() will return {... messagingServiceSid: null ...}

**Comment by sschadwick** [comment]
I should note that this is on 3.0.0-rc13

**Comment by jingming** [comment]
@sschadwick can you try this with the latest release and let us know if you are still seeing this issue?
