### ISSUE TITLE
Missing post for role update

### ISSUE THREAD

**Issue by confuser** [twilio/twilio-node#200]
**Version:** 2.11.0
**API Subdomain (api/taskrouter/ip_messaging):**
### Code Snippet

https://www.twilio.com/docs/api/ip-messaging/rest/roles

``` javascript
var accountSid = 'ACCOUNT_SID';
var authToken = 'AUTH_TOKEN';
var IpMessagingClient = require('twilio').IpMessagingClient;

var client = new IpMessagingClient(accountSid, authToken);
var service = client.services('SERVICE_SID');

service.roles('ROLE_SID').post({
    permission: 'sendMessage'
}).then(function(response) {
    console.log(response);
}).fail(function(error) {
    console.log(error);
});
```

NOTE: The original snippet isn't valid, as it uses the same key twice in the post object 
### Exception / Log

```
TypeError: Object #<Object> has no method 'post'
```
### Steps to Reproduce
1. Try to update a role using the example snippet
2. Throws an error as the only available methods are `list` and `get`

**Comment by jingming** [comment]
@confuser we have updated the library to the `3.x.x` line that supports this feature here: https://github.com/twilio/twilio-node/blob/master/lib/rest/chat/v2/service/role.js#L496
