### ISSUE TITLE
Invalid token generation

### ISSUE THREAD

**Issue by dylanjmcdonald** [twilio/twilio-node#201]
My node server is producing an invalid token each time I request one from my iOS application. When I set my token endpoint in my iOS application to use my Node server I receive a "Twilio Services Error" error, but when I swap the endpoint to use the python quickstart server from Twilio, which I have hosted on Heroku, it works correctly. I've triple checked that the Account SID, Auth Token, and Application SID match across both servers.

**twilio-node version:** 2.11.0
### Token Endpoint

``` javascript
app.get('/token', function (request, response) {

    var capability = new twilio.Capability(config.TWILIO_ACCOUNT_SID, config.TWILIO_AUTH_TOKEN);

    capability.allowClientOutgoing(config.TWILIO_TWIML_APP_SID);

    var token = capability.generate();

    response.send(token);

});
```

**Comment by jingming** [comment]
@dylanjmcdonald we updated the JWT generation mechanism in the latest version of the library. Please give that a try and let us know if the problem persists.
