### ISSUE TITLE
Not a able to capture the response from callback response url

### ISSUE THREAD

**Issue by sunilkumarmandadi** [twilio/twilio-node#212]
**5.0:**
**API Subdomain (api/taskrouter/ip_messaging):**

### Code Snippet
 string AccountSid = "xxxxx";
            string AuthToken = "yyyyy";
            var twilio = new TwilioRestClient(AccountSid, AuthToken);

            Message message = await Task.Run(() => twilio.SendMessage(
                "+22222222222", "+11111111111",
                "Twilio test message",
                "http://abcd/Notification/Test"
            ));

# paste code here
```

### Exception / Log
```
I couldn't find a way to capture the status from callback response url. I am using c# web api.
```

**Comment by jingming** [comment]
@sunilkumarmandadi please redirect this question to help@twilio.com and be sure to mention that you are using C#.
