### ISSUE TITLE
Provide option to set promise library

### ISSUE THREAD

**Issue by offero** [twilio/twilio-node#217]
It would be beneficial to provide as an option the promise library that the twilio library uses. Other libraries allow you to specify which promise library to use but otherwise defaults to the built-in promise implementation.

The twilio library documentation says that Q is the defacto standard library for promises, but in my experience that is not the case. Bluebird is used much more and is much more performant. Additionally, node has it's own Promise implementation now, so that should be used as the default.

### Example from the AWS library
```javascript
AWS.config.setPromisesDependency(require('bluebird'));
```

**Comment by kolencherry** [comment]
+1. Bluebird has a lot more syntactic sugar (e.g. .each()).

**Comment by jmctwilio** [comment]
Bluebird is awesome.  Not sure how soon we'll be able to make the change, but thanks for the suggestion.
