### ISSUE TITLE
No documented way to use API keys

### ISSUE THREAD

**Issue by gabegorelick** [twilio/twilio-node#220]
The API allows you to use account SID and auth token for authorization, but there's no documented way to use API keys instead of auth tokens.

**Version:** 2.11.1

### Code Snippet
```javascript
// this is the normal way to instantiate a RestClient
new twilio.RestClient(accountSid, authToken);

// this will give auth errors when making API requests
new twilio.RestClient(keySid, keySecret);

// this appears to work
const client = new twilio.RestClient(accountSid, keySecret);
client.accountSid = keySid; 
```

The last method works because `accountSid` needs to be the actual account SID (and not an API Key SID) so that request paths are generated correctly, i.e. `GET /2010-04-01/Accounts/ACCOUNT_SID`. But we want the key SID and secret [to be used for Basic auth](https://github.com/twilio/twilio-node/blob/e69304af9959c36a9f562c9a87ab63294ab978bc/lib/Client.js#L77).

### Feature Request
The optional options parameter to the `RestClient` should accept a `keySid` option. For example:
```js
new twilio.RestClient(accountSid, keySecret, {keySid: 'KEY_SID'});
```
`process.env.TWILIO_KEY_SID` should also be checked.

**Comment by jingming** [comment]
@gabegorelick We have updated the base client in the `3.x.x` line of the library to accept `username` and `password` here: https://github.com/twilio/twilio-node/blob/master/lib/rest/Twilio.js#L87

Note that if you wish to use API key authentication, you will also have to pass in the account sid in the `opts`.

**Comment by tylercollier** [comment]
I had a hard time finding info about using API keys too, and I found this page from google. Later, I found the answer and want to share here.

I found the info here: https://www.twilio.com/docs/glossary/what-is-an-api-key#how-do-i-authenticate-with-an-api-key. It has code examples for Node, but I'll post the relevant part here. The trick is to use the api key and secret, and ALSO the account SID. All 3.

```js
const accountSid = process.env.TWILIO_ACCOUNT_SID;
const apiKey = process.env.TWILIO_API_KEY;
const apiSecret = process.env.TWILIO_API_SECRET;
const client = require('twilio')(apiKey, apiSecret, { accountSid });
```

**Comment by abierbaum** [comment]
IMHO. This should really be documented better in the examples given this is the security best practice.

**Comment by govindrai** [comment]
Also what about `validateRequest`? It requires authToken. But what if you want to use API key/secret? is that possible? Seems like the best practice is not achievable here. 

export function validateRequest(
  authToken: string,
  twilioHeader: string,
  url: string,
  params: Record<string, any>
)
