### ISSUE TITLE
Unable to filter messages.get with >= date

### ISSUE THREAD

**Issue by Nogbit** [twilio/twilio-node#223]
I'm following the documentation [here](https://www.twilio.com/docs/guides/sms/how-to-retrieve-and-modify-message-history-in-node-js#search-previous-messages) and [here](https://www.twilio.com/docs/api/rest/message) to get a list of messages sent on/after a specific date.  The code below works fine when I don't use `>=` and I get 7 results.  But using the `>=` I get a list of all my messages...its as if that param is ignored.  Please advise.

**Version:** 2.11.1
**API Subdomain (api/taskrouter/ip_messaging):** /messages

### Code Snippet
```javascript
let latest = '2017-02-28';
let list = await client.messages.get({dateSent: `>=${latest}`});

console.log(list.messages.length);
console.log(list.first_page_uri);
```

### Log
```
50
/2010-04-01/Accounts/[my-acct]/Messages.json?DateSent=%3E%3D2017-02-28&PageSize=50&Page=0
```

### Steps to Reproduce
1. Run the code above
2. The Log output line 1 should be `7` not `50`.

**Comment by jingming** [comment]
@Nogbit The `3.x.x` line of the library should support the feature via `dateSentAfter` here: https://github.com/twilio/twilio-node/blob/master/lib/rest/api/v2010/account/message.js#L144

Please feel free to reopen this issue if you continue to have issues.

**Comment by wswoodruff** [comment]
I'm experiencing an issue where the `dateSentAfter` param is ignored using `channel.messages()`. It's ignored when I use `channel.messages().each` and `.list` as well.

lib version `3.9.3`

Here's the gist of what I'm sending
```
const yesterday = new Date(new Date().getTime() - (24 * 60 * 60 * 1000));

channel.messages().list({
    limit: 5,
    dateSentAfter: yesterday
}).then((wrongMessages) => { console.log('wrongMessages', wrongMessages); });
```

**Comment by wswoodruff** [comment]
Yeah I'm just getting the first 5 messages in the channel. The channel is a UserChannelInstance https://www.twilio.com/docs/libraries/reference/twilio-node/3.9.3/Twilio.Chat.V1.ServiceContext.UserContext.UserChannelInstance.html

**Comment by wswoodruff** [comment]
I was using the wrong type of channel instance for this, `dateSentAfter` is not available on a user channel, gotta use the `order` option
