### ISSUE TITLE
How can I get the number of segments before sending a SMS

### ISSUE THREAD

**Issue by gsabran** [twilio/twilio-node#224]
Is it possible to know how many segments a given message will use?

**Comment by jingming** [comment]
@gsabran Please direct this question over to help@twilio.com! We have many support agents that would be happy to help you out!

**Comment by gsabran** [comment]
Thanks. I've searched the repo for `segments` that only appears [here](https://github.com/twilio/twilio-node/blob/31d04e0d9033e3f0d3d57b9737b0bfc70b8780ce/lib/rest/api/v2010/account/message.js#L476) and seems to be set from the payload after the message is sent (I might be wrong). The [doc](https://www.twilio.com/docs/libraries/node) doesn't mention anything about it and states _This library is open source, so if you find a feature missing or a bug, we encourage you to file an issue or contribute back to the twilio-node project._ I'm happy to contact support by email but github was a more natural place for me to go to about this. lmk
