### ISSUE TITLE
unable to send a message with MessagingServiceSid

### ISSUE THREAD

**Issue by jonathanong** [twilio/twilio-node#232]
*Note: These issues are for bugs and feature requests for the helper libraries. If you need help or support, please email help@twilio.com and one of our experts will assist you!*

**Version:**

v2

**API Subdomain (api/taskrouter/ip_messaging):**

sms messages

### Code Snippet
```javascript
  twilio.sms.messages.create({
    to: phone_number,
    messagingServiceSid: twilioConfig.NOTIFICATION_MESSAGING_SERVICE_ID,
    body: message
  }).then(debug, onError)
```

### Exception / Log
```js
{ status: 400,
  message: 'A \'From\' phone number is required.',
  code: 21603,
  moreInfo: 'https://www.twilio.com/docs/errors/21603' }
```

### Steps to Reproduce
1.
2.
3.

### Feature Request

according to the docs at https://www.twilio.com/docs/api/rest/sending-messages#post-parameters-conditional, only one of `From` or `MessagingServiceSid` is required. From is not.

**Comment by jingming** [comment]
@jonathanong Support for Messaging Services has been added in the the `3.x.x` line of the library. Please give that a try and feel free to open this ticket if you are still having issues!

**Comment by usamamashkoor** [comment]
I am still facing the issue in 3.x.x version.
