### ISSUE TITLE
Wrong Timezone

### ISSUE THREAD

**Issue by AnatoliyGatt** [twilio/twilio-node#235]
Hi, don't know if it's a Twilio issue or just a Node.js issue, but the timezone with which SMSs are sent is wrong. Both my mobile device and computer (where the server is spinning) have CET as a configured timezone. Though all SMSs I'm receiving are in UTC (i.e. 2 hours behind). Any tips on how to fix this?

**Comment by efossier** [comment]
Hi Anatoliy, thanks for writing in. All dates returned by the api are in UTC regardless of where the messages are sent from. This is to enforce consistent dates across all users. Knowing that dates are in UTC we recommend you do the conversion to your time zone yourself in your code. Hope this helps!

**Comment by AnatoliyGatt** [comment]
@efossier What do you mean? Can I explicitly set the timezone for the SMS that I'm are sending?

**Comment by efossier** [comment]
@AnatoliyGatt No its not possible to set the timezone on the sms. The timestamps on messages are set at the API layer in UTC when you make the api call to create one. We return the dates as strings which are in utc because thats the timezone the api uses for all dates. If you want to work with messages in a different timezone in your code then you will have to load the date strings into a Date object and do the conversion there. 

We are currently working on a next generation node library which should automatically load dates into Date objects in which case it should pick up your global system timezone.

**Comment by AnatoliyGatt** [comment]
@efossier Oh, I guess you understood me wrong, I don't have a problem internally with my timezone, I'm very unhappy with a fact that users receiving SMSs that are dated "2h ago".

**Comment by efossier** [comment]
@AnatoliyGatt Ah I see my mistake, still not sure I fully understand: You mean the sms on their phone says it was received 2h ago even though they just received it?

**Comment by AnatoliyGatt** [comment]
@efossier Correct!

**Comment by AnatoliyGatt** [comment]
@efossier Also, I have changed the default timezone in the Twilio admin console, doesn't seem to effect anything on the API side though.

**Comment by dougblack** [comment]
Hey @AnatoliyGatt, I'm a bit confused as well.

When you use the Twilio API to send an SMS, Twilio records the `date_created` property in UTC. It does not send any time-related information to the receiving device. Any device-side issues related to the receiving timestamp would be the fault of the device, not Twilio.

Are you seeing incorrect timestamps on the device side or through Twilio's API? I just attempted to reproduce this issue and saw correct timestamps both on the receiving side (an iPhone) and when viewing the Message record via the API.

**Comment by AnatoliyGatt** [comment]
@dougblack Hi, I'm not concerned with the response from the Twilio server, the actual issue is on the device, I'm receiving SMSs that is dating "2h ago". Haven't even looked into the API response.

**Comment by AnatoliyGatt** [comment]
@dougblack As I have mentioned in the beginning, both device and server have CET as their default timezone.

**Comment by AnatoliyGatt** [comment]
@dougblack Also, I have mentioned that even SMSs from Twilio (like 2 factor authentication SMSs, when I'm logging into Twilio) are also coming to my device marked as "2h ago".

**Comment by efossier** [comment]
@AnatoliyGatt Twilio does not send any timestamps with the sms to the receiving device, receiving an sms from twilio is the same as receiving an sms from anyone else from the phone's perspective. If the device is receiving the sms with a 2hr old timestamp then that is either a fault in the device or the sms is getting delayed and the carrier is holding the sms for 2hrs before it makes it to the target phone. 

Are you seeing 2hr delays between when you make the request to Twilio to send a message and when the phone actually receives the message?

This is definitely not an issue with the helper library or the API, if you keep seeing this behavior I would recommend contacting customer support at support@twilio.com. They can investigate carrier problems or problems similar to that. If you do open a support ticket, please include a link to this issue so they have more context.

**Comment by AnatoliyGatt** [comment]
@efossier There is no delay, the messages are coming instantly, but showing as they were received 2h ago. Will try to contact Twilio support then. Thanks.

**Comment by vermalokesh0704** [comment]
In which timezone Twilio API server return the UTC time, i mean where the API server based in which timezone?
