### ISSUE TITLE
Issue Capabilities Array

### ISSUE THREAD

**Issue by jonhill13** [twilio/twilio-node#237]
**Version**: 2.8

I believe there are a couple of issues in the code in the /lib/Capability.js file.

**Issues:**
1. The length of the capability array (this.capabilities) builds up over time.
2. The capabilities variable in the "Capability.prototype.generate" function takes the entire this.capability array because "this.capabilities.slice(0)" takes the entire array. (var capabilities = this.capabilities.slice(0))

The first issue regarding the "this.capabilities" array building up over time is an issue because over time the array will impact memory but also because the "Capability.prototype.generate" function is sending the entire array to Twilio which will cause an error.  

The second issue regarding the "Capability.prototype.generate" function, the "var capabilities = this.capabilities.slice(0)" takes the entire "this.capabilities" array and sends it to Twilio which after time will be too large and Twilio will send back an error when verifying the token.

I came across these issues after my app would not allow for outgoing and/or incoming calls after about two weeks of running.  The system would run fine and then the tokens being generated and sent to Twilio to verify would send back an error of "Application not found", which would make a call to get a new capability token and send that to Twilio to verify but would again return and error of "Application not found".

I raised this issue with Twilio and Twilio said, "Decoding your token seems to show a long list", and they said that the scope should only be one for incoming and/or outgoing.  This led me to look into the library where the tokens were being generated, and finding the two issues raised above.

I have offered some solutions below and would love to hear if any other developers are seeing this same issue, and would be open to adding this solution if approved.

**Solutions:**

There are a couple of solutions to address these issues.

The first would be to clear the "this.capabilities" array, "this.capabilities = [];", after creating the "payload" object and before returning the javascript web token in the "Capability.prototype.generate" function. I have implemented this in my code base and is working well.

The other option would be to change the "var capabilities = this.capabilities.slice(0)" to take only the last element in the array and clear the array at some point in time.

**Comment by jingming** [comment]
@jonhill13 we have redesigned the way that these tokens work in the `3.x.x` line of the library. Please give that a try and reopen this ticket if you are still experiencing issues!
