### ISSUE TITLE
QS Should be updated for security reasons

### ISSUE THREAD

**Issue by BrandonCopley** [twilio/twilio-node#239]
QS should be upgraded to 6.4.0 to fix some minor security flaws.

If 6.4.0 is incompatible, we can use 6.2.3 as well I believe: 6.3.2, 6.2.3, 6.1.2, 6.0.4 are patched versions

https://snyk.io/vuln/npm:qs:20170213?utm_source=trace

**Comment by faust64** [comment]
When you stumble upon these, feel free to open a PR. Fix was included a while ago, that one could be closed.

**Comment by ilanbiala** [comment]
@BrandonCopley I don't believe this vulnerability exists. Where do you see us using `QS`?

**Comment by faust64** [comment]
It's pulled as a request dependency.
AFAIU, that issue was about updating the request dependency (if not patching request itself).

**Comment by jmctwilio** [comment]
Thank you for the link.  When I checked, it shows no vulnerabilities found.  I hope I'm interpreting that correctly.  For now, I'll close this issue as resolved.
