### ISSUE TITLE
Concat-Stream should be updated for security reasons

### ISSUE THREAD

**Issue by BrandonCopley** [twilio/twilio-node#240]
For security reasons concat-stream should be updated to version 1.5.2 or higher

https://snyk.io/vuln/npm:concat-stream:20160901?utm_source=trace

**Comment by faust64** [comment]
I don't see that module being included here. Could you clarify?

**Comment by ilanbiala** [comment]
@BrandonCopley I don't believe this vulnerability exists. Where do you see us using `concat-stream`?

**Comment by jmctwilio** [comment]
I don't see any vulnerabilities listed from snyk for our current build.  If I'm misinterpreting the results, please correct me.  For now, I'm closing this PR as resolved and very much appreciate your bringing the issue to our attention.
