### ISSUE TITLE
Where to find documentation for 3.x API?

### ISSUE THREAD

**Issue by joonhocho** [twilio/twilio-node#252]
I can't find proper documentation for node 3.x api.

**Comment by joonhocho** [comment]
My lookup code isn't working anymore after upgrading from v2.x.
This doc seems outdated: https://www.twilio.com/docs/api/lookups

**Comment by natesilva** [comment]
The reference docs start at https://twilio.github.io/twilio-node/3.0.0/Twilio.html, but the page you mentioned should be okay. On that page -- with the window maximized -- you can see sample code, make sure the SDK version selected is 3.x. That will show an example, but it doesn’t show how to set the lookup type. Here’s a better example:

```javascript
// get caller-name (async/await style)
const result = await client.lookups.v1.phoneNumbers(numberToLookup)
  .fetch({ type: 'caller-name'});

// or, get carrier (traditional Promise style)
 client.lookups.v1.phoneNumbers(numberToLookup)
  .fetch({ type: 'carrier'})
  .then((result) => console.log(result));
```

**Comment by joonhocho** [comment]
@natesilva Thank you for your answer!

**Comment by joonhocho** [comment]
I will close this.
