### ISSUE TITLE
[Documentation] Source code and twilio support docs are inconsistent

### ISSUE THREAD

**Issue by alvincrespo** [twilio/twilio-node#254]
I was trying out the beta for functions today and while I was looking for documentation I found an inconsistency on my end. 

The documentation [here](https://support.twilio.com/hc/en-us/articles/115007737928-building-apps-with-twilio-functions), states that you can utilize `MessagingResponse#message` in this manner:

```
var twiml = new Twilio.twiml.MessagingResponse()
twiml.message("Hello SMS")
```

But based on my understanding of the source, the `message` method takes in two parameters, `attributes` and `body`. The confusing part is that the function I set up in Twilio works perfectly fine with one argument - so I'm curious which might be the correct way?

**Version: alpha**
**API Subdomain: MessagingResponse**

### Code Snippet
```javascript
MessagingResponse.prototype.message = function(attributes, body) {
  return new Message(this.response.ele('Message', attributes, body));
};
```
From [here](https://github.com/twilio/twilio-node/blob/alpha/lib/twiml/MessagingResponse.js#L27-L29).

**Comment by efossier** [comment]
@alvincrespo I think both should work, taking a look at the `ele` function in the `xmlbuilder` dependency it looks like attributes are optional and can be omitted.
