### ISSUE TITLE
Calling availablePhoneNumbers with limit 0 never returns

### ISSUE THREAD

**Issue by natesilva** [twilio/twilio-node#263]
**Version: 3.4.0**

If you look for available phone numbers, but pass `limit: 0`, it times out and never returns.

Of course, passing `limit: 0` is pointless, but it should return an empty array or throw an error. It should not time out.

This can happen when the number of phone numbers needed is a calculated value (we have 5 and we need a total of 5, so we need to buy 0). We’re checking for this now and not attempting to buy 0 phone numbers. 🤣 

### Code Snippet
```javascript
// (in an async function somewhere)

const opts = { 
  excludeAllAddressRequired: 'true',
  voiceEnabled: 'true',
  mmsEnabled: 'true',
  smsEnabled: 'true',
  limit: 0,
  inRateCenter: 'WSNGTNZN08',
  inRegion: 'VA' 
}

// this never returns if limit is 0
const numbers = await this._twilioClient.availablePhoneNumbers('US').local.list(opts);
```

**Comment by efossier** [comment]
@natesilva Thanks for bringing this to our attention, this is definitely unintended behavior. I've created a ticket for us to track the bug. I'll keep you updated as to when we are able to start working on a fix.

**Comment by kevinburke** [comment]
I believe I have an open Twilio Support ticket about this issue as well

**Comment by efossier** [comment]
Fixed: https://github.com/twilio/twilio-node/pull/297
