### ISSUE TITLE
Is Text to Voice functionality available in 2.x of sdk?

### ISSUE THREAD

**Issue by harkinj** [twilio/twilio-node#264]
Hi,
Is text to voice functionality available in 2.x?
Or must we upgrade to 3.x to get this via the transcribe functionality of the Record verb ?
Thanks for your time.
John

**Comment by efossier** [comment]
@harkinj Transcribing is done by setting the `transcribe=true` attribute on the Record verb, the 2.x library lets you pass arbitrary attributes to any of the verbs so you do not need to upgrade to use that functionality. If you want to use any new verbs however you will need to upgrade.
