### ISSUE TITLE
LookupsClient is not a constructor

### ISSUE THREAD

**Issue by yotavm** [twilio/twilio-node#267]
*Note: These issues are for bugs and feature requests for the helper libraries. If you need help or support, please email help@twilio.com and one of our experts will assist you!*
hey, 
i try to use the lookup in version 3.4.0 
and i get 

**Version:**
node: v6.11.0
twilio: v3.10.10
**API Subdomain (api/taskrouter/ip_messaging):**

### Code Snippet
```javascript
/* const LookupsClient = require('twilio').LookupsClient
const lookupsClient = new LookupsClient(accountSid, authToken); */
```

### Exception / Log
```
</Users/yotavmasa/Desktop/oklive/oklive/oklive-server/okliveAuth/src/config/common/index.js:4
const lookupsClient = new LookupsClient(accountSid, authToken);
                      ^

TypeError: LookupsClient is not a constructor
    at Object.<anonymous> (/Users/yotavmasa/Desktop/oklive/oklive/oklive-server/okliveAuth/src/config/common/index.j
s:4:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/yotavmasa/Desktop/oklive/oklive/oklive-server/okliveAuth/src/api/routes.js:2:16)
    at Module._compile (module.js:570:32)
>
```

### Steps to Reproduce
1.
2.
3.

### Feature Request
_If this is a feature request, make sure you search Issues for an existing request before creating a new one!_

**Comment by ilanbiala** [comment]
If you're looking for the lookups API, I think you'll want to do:
```
const twilio = require('twilio');
const client = twilio(accountSid, authToken);
```
Then you can access our REST API by doing `client.lookups.request()` or by using some other methods under `client.lookups`. Please reply if you still have any other questions.

**Comment by yotavm** [comment]
thanks =]

**Comment by ilanbiala** [comment]
Can you clarify what you mean by functions? Usually the easiest way to explore the given methods for me is to just open the Node REPL by typing `node`, and executing a few lines of code line by line to see what is returned. Also, you can tab complete in the REPL, so if you type `client.lookups.` and press tab, the REPL will print out all the methods that you can do, such as `client.lookups.request()`, `client.lookups.phoneNumbers()`, etc.

Does that answer your question?

**Comment by yotavm** [comment]
yes all working now thanks =]
