### ISSUE TITLE
Wrong error returned from client.messages.create

### ISSUE THREAD

**Issue by GrandathePanda** [twilio/twilio-node#270]
I just figured out a support ticket I submitted a little while ago and it looks like a bug with either your sdk or the api. If you manage to supply a 'to' number with ':' in it it chokes and tells you your 'from' number is wrong when it should really tell me I have some incomprehensible garbage in my 'to'. Which I grant is obscure, in fact I only stumbled on it because I had a function that I supplied arguments to in the wrong order, put my 'body' in the 'to' place accidentally. The snippet below should be able to minimally reproduce it.

**Version: 3.4.0**

### Code Snippet
```javascript
import twilio from 'twilio'

let configuredClient = new twilio(process.env.TWILIO_ACCOUNT_SID, process.env.TWILIO_AUTH_TOKEN)
const sendMessage = (body, to) => {
  return configuredClient.messages.create({
    body,
    to,
    from: process.env.TWILIO_PHONE_NUMBER
  })
}
sendMessage('anything', ':')
```

### Exception / Log
```
{ [Error: The 'From' number +1********** is not a valid phone number, shortcode, or alphanumeric sender ID.]
  status: 400,
  message: 'The \'From\' number +1********** is not a valid phone number, shortcode, or alphanumeric sender ID.',
  code: 21212,
  moreInfo: 'https://www.twilio.com/docs/errors/21212',
  detail: undefined }
```

### Steps to Reproduce
1.Set up the client like normal with authToken and SID.
2.Attempt to send a message, but include a ':' somewhere in the 'to' number. 
3. You should see an error that tells you your from number is incorrect which is a red herring.

**Comment by efossier** [comment]
@GrandathePanda Hmm thats an interesting bug, its definitely something being returned by the api however. You are more likely to get help from support@twilio.com in this instance, I am going to close this as we want to keep the issues limited to bugs/features requests for the node library.
