### ISSUE TITLE
Sync API does not exist in the 3.4 release of the Node library

### ISSUE THREAD

**Issue by vinitdave27** [twilio/twilio-node#274]
*Note: These issues are for bugs and feature requests for the helper libraries. If you need help or support, please email help@twilio.com and one of our experts will assist you!*

**Version:** ^3.4.0
**API Subdomain (api/taskrouter/ip_messaging):** sync

### Code Snippet
var Twilio = require('twilio').Twilio;
var client = new Twilio(accountSid, authToken);
client.sync.services.list()
  .then(function(response) {
    console.log(response);
  }).catch(function(error) {
    console.log(error);
  });

### Exception / Log
sync object is null and services is not a function of the sync object.

### Steps to Reproduce
1. npm install twilio
2.Use express app to access the document/service list for the Sync API

**Comment by efossier** [comment]
@vinitdave27 That is because Sync is a developer preview product and therefore is only included in the `alpha` releases of our library. Try 3.4.0-alpha1
