### ISSUE TITLE
call using ApplicationSid

### ISSUE THREAD

**Issue by tamal-appsbee** [twilio/twilio-node#275]
Version: 3.4.0

Following  **Make an outbound call** (Ref. https://www.twilio.com/docs/api/rest/making-calls)

```
const accountSid = 'xxxxxxxxxxx';
const authToken = 'xxxxxxxxxxx';
const client = require('twilio')(accountSid, authToken);

client.calls.create({
  ApplicationSid: 'xxxxxx',
  to: '+1xxxxxxxxxxx',
  from: '+1xxxxxxxxxx',
})
.then((call) => process.stdout.write(call.sid)).catch((err) => console.log(err));

```
**Getting following error:**

{ [Error: Url parameter is required. For more information, see http://www.twilio.com/docs/api/twiml]
  status: 400,
  message: 'Url parameter is required. For more information, see http://www.twilio.com/docs/api/twiml',
  code: 21205,
  moreInfo: 'https://www.twilio.com/docs/errors/21205',
  detail: undefined }

**Comment by imthepitts** [comment]
@tamal-appsbee, sorry for the confusion. The options you pass in should use headless camelCase:

```
client.calls.create({
  applicationSid: 'xxxxxx',
  to: '+1xxxxxxxxxxx',
  from: '+1xxxxxxxxxx',
}).then(...)
```

The complete set of available options are specified here:
https://github.com/twilio/twilio-node/blob/master/lib/rest/api/v2010/account/call.js#L92

Please give that a try and let me know if it works for you.

**Comment by tamal-appsbee** [comment]
@imthepitts Thanks, It worked :)
