### ISSUE TITLE
client.outgoingCallerIds.create is not a function

### ISSUE THREAD

**Issue by isaacpz** [twilio/twilio-node#278]
**Version:** 3.5.0
**API Subdomain** api/rest/outgoing-caller-ids

The `client.outgoingCallerIds.create` function is not implemented on the nodejs library. Other `outgoingCallerIds` calls work fine.

The unimplemented code snippet is found in the documentation [here](https://www.twilio.com/docs/api/rest/outgoing-caller-ids?code-sample=code-add-a-new-outgoing-caller-id&code-language=js&code-sdk-version=2.x)

### Code Snippet
```javascript
client.outgoingCallerIds.create({friendlyName: "somename", phoneNumber: "somenumber"});
```

### Exception / Log
```
client.outgoingCallerIds.create is not a function
```

**Comment by tcollins590** [comment]
I am having the same issue.

@isaacpz did you find a solution to this?

**Comment by efossier** [comment]
@isaacpz @tcollins590 Sorry for the confusion, the docs you linked have an incorrect code snippet, I've reached out to the docs team to have this corrected as soon as possible.

The functionality you are looking for is accessible at `client.validationRequests.create(...)`.
