### ISSUE TITLE
Transferring number from master to subaccount does nothing

### ISSUE THREAD

**Issue by seriph** [twilio/twilio-node#281]
**Version:3.6.2**

### Code Snippet
```node
const accountSid = 'ACyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy';
const authToken = 'your_auth_token';
const client = require('twilio')(accountSid, authToken);

const currentNumberOwnerAccountSid = 'ACyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy';
const newNumberOwnerAccountSid = 'ACzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz';
const phoneNumberSid = 'PNyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy';

client.api.accounts(currentNumberOwnerAccountSid)
  .incomingPhoneNumbers(phoneNumberSid)
  .update({
    accountSid: newNumberOwnerAccountSid // specify new account owner
  })
  .then((number) => console.log(number));
```

### Exception/Log
```
Update returns an IncomingPhoneNumberInstance instead of the expected response
```

### Steps to Reproduce
1. Attempt to transfer a phone number from a master account to a subaccount
2. Update does not produce the response anticipated
3. Nothing changes about my account. The phone number stays where it was

Note that running the same request through curl works as expected

**Comment by jmctwilio** [comment]
Thank you for your feedback.  We're working on a solution.

**Comment by sambaker** [comment]
@seriph I had the same problem last week. The latest code in github has it fixed but the latest release did not at the time.

If you need an urgent fix to v3.6.2, open node_modules/twilio/lib/rest/api/v2010/account/incomingPhoneNumber.js and add a new line 841:

    'AccountSid': _.get(opts, 'accountSid'),

to `IncomingPhoneNumberContext.prototype.update`. The Node library wasn't passing accountSid on to the REST API.

**Comment by sambaker** [comment]
Update, turns out @tmconnors has an open pull request that you can reference, although the line numbers differ to v3.6.2 https://github.com/twilio/twilio-node/pull/289/files

**Comment by childish-sambino** [comment]
Closed by https://github.com/twilio/twilio-node/pull/289
