### ISSUE TITLE
Limitation of 160 charectors in sms in trial account?

### ISSUE THREAD

**Issue by jasspro** [twilio/twilio-node#283]
I've got problem sending messages longer than 160 characters when using this gem. The response I get is:

{"status"=>400,
 "message"=>"The message body exceeds the 160 character limit.",
 "code"=>21605,
 "more_info"=>"http://www.twilio.com/docs/errors/21605"}

In my msg, i have only 200 character , but i have trial account. 
so i would like to know, can i send more than 160 character msg i trial account?
or can it sent after upgrade the account?

Any ideas?

**Comment by jmctwilio** [comment]
Thanks for reaching out.  Please contact help@twilio.com to resolve this issue.
