### ISSUE TITLE
Mocking sendMessage for Twilio 2.11.1

### ISSUE THREAD

**Issue by CodeOtter** [twilio/twilio-node#287]
Are there any tutorials or libraries or advice on how to mock [sendMessage](https://github.com/twilio/twilio-node/blob/2.11.1/lib/resources/Messages.js#L14) for unit tests?  It's incredibly over-engineered and difficult to make sense of.

`sendMessage` appears to return a nodeified promise via https://github.com/twilio/twilio-node/blob/2.11.1/lib/Client.js#L93, but having to require Q just for unit tests when I'm already using Bluebird strikes me as needless.

**Comment by jmctwilio** [comment]
Thanks for contacting us.  Our current library version 3.6 and we're no longer supporting version 2.11.1.
