### ISSUE TITLE
Getting a token with custom TTL does not work

### ISSUE THREAD

**Issue by GeoffreyPlitt** [twilio/twilio-node#291]
Hi,

Based on info I've gathered from a few places where Twilio has docs, I figured the following would allow a custom TTL (24 hours) instead of the default (1 hour)
```
const token = new AccessToken(
    TWILIO_ACCOUNT_SID,
    TWILIO_AUTH_TOKEN, // aka API key
    TWILIO_API_SECRET,
    3600 * 24 // 24 hour expiration
  )
```
But the final argument is being ignored, we're still getting tokens that expire in an hour. Please advise how to properly get a longer token.

**Comment by imthepitts** [comment]
Hi @GeoffreyPlitt,

Sorry for the confusion. The TTL needs to be included as part of an options object:

https://github.com/twilio/twilio-node/blob/master/lib/jwt/AccessToken.js#L200

Something like this:

```
const token = new AccessToken(
    TWILIO_ACCOUNT_SID,
    TWILIO_AUTH_TOKEN, // aka API key
    TWILIO_API_SECRET,
    {ttl: 3600 * 24 } // 24 hour expiration
  )
```
Please give that a try and let me know if it works for you.

All the Best,
Zack

**Comment by GeoffreyPlitt** [comment]
Perfect, thanks!

**Comment by WajdiBf** [comment]
Hi @imthepitts  
I tried This 
`   

     const token = new AccessToken(
            config.TWILIO_ACCOUNT_SID,
            config.TWILIO_API_KEY,
            config.TWILIO_API_SECRET,
            { ttl: 3600 * 24 } )

`
But TTL  object is still ignored, any help pls
