### ISSUE TITLE
443 Error not found on twilio.messages.create

### ISSUE THREAD

**Issue by gitsad** [twilio/twilio-node#292]
Hi
I have a problem and I cannot find a solution. I do not know why I'm getting this error bellow:
```
{
    "twilioError": {
        "code": "ENOTFOUND",
        "errno": "ENOTFOUND",
        "syscall": "getaddrinfo",
        "hostname": "api.twilio.com",
        "host": "api.twilio.com",
        "port": 443
    }
}
```
Of course, twilioError is my custom name of this object. The piece of code which I was trying to run is here:
```
const admin = require('firebase-admin');
const twilio = require('./twilio');

module.exports = (req, res) => {
    if(!req.body.phone) {
        return res.status(422).send({ error: 'You must provide a phone number' });
    }
    const phone = String(req.body.phone).replace(/[^\d]/g, '');
    admin.auth().getUser(phone)
        .then((userRecord) => {
            const code = Math.floor(Math.random() * 8999 + 1000);
            twilio.messages.create({
                body: 'Your code is',
                to: phone,
                from: '+48799448802',
            })
                .then(() => {
                    admin.database().ref('users/' + phone)
                        .update({ code: code, codeValid: true }, () => {
                            res.send({success: true});
                        })
                }).catch((err) => res.status(422).send({ twilioError: err }));
        })
        .catch(err => {
            return res.status(422).send({ error: err });
        })
}
```
Here is also my twilio.js which I've imported to this file above:
```
const Twilio = require('twilio').Twilio;
const twilioAccount = require('./twilioAccount');

const accountSid = twilioAccount.accountSid;
const authToken = twilioAccount.authToken;

module.exports = new Twilio(accountSid, authToken);
```
I really want to know how to resolve this. I went through all Twilio's documentation and I didn't find an explanation. Even on the first page, at the very bottom, is mentioned about possible errors on sending messages and there is no information about 443 Error.

My versions:
```
"firebase-admin": "~5.2.1",
"firebase-functions": "^0.6.2",
"twilio": "^3.0.0-rc.13"
```
As you can see **I also used firebase to deploy my app.** Are there some restrictions between firebase and twilio?

If someone knows what I am doing wrong or where is the problem I will be grateful for helping me.
Thanks!

**Comment by efossier** [comment]
Your code snippet for initializing the twilio client is slightly different from the documented way on twilio.com:
```js
var accountSid = 'ACXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'; // Your Account SID from www.twilio.com/console
var authToken = 'your_auth_token';   // Your Auth Token from www.twilio.com/console

var twilio = require('twilio');
var client = new twilio(accountSid, authToken);
```

Perhaps this is the cause?

Otherwise it seems that the error is that you are unable to connect to `api.twilio.com` and port 443 (the https port). Are you able to connect to `https://api.twilio.com` in your web browser? from the command line? This is likely not a problem with the library itself and more your environment and overall ability to connect to the twilio api.

**Comment by gitsad** [comment]
I think the initializing step is the same as mine:
```
const Twilio = require('twilio').Twilio;
const twilioAccount = require('./twilioAccount');

const accountSid = twilioAccount.accountSid;
const authToken = twilioAccount.authToken;

module.exports = new Twilio(accountSid, authToken);
```
and your example:

```
var accountSid = 'ACXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'; // Your Account SID from www.twilio.com/console
var authToken = 'your_auth_token';   // Your Auth Token from www.twilio.com/console

var twilio = require('twilio');
var client = new twilio(accountSid, authToken);
```

As you can see, I have auth data in an external file which I import to init file. But still, I have not checked your suggestion about connection. I will try it and I will respond as fast as I could. :+1:

**Comment by dondre** [comment]
It's time to whip out your Credit Card if you want to use Firebase to make 3rd party API calls

**Comment by shouryalala** [comment]
@dondre Thats the problem right? I'm facing the same problem..

**Comment by childish-sambino** [comment]
@dondre Yes, that looks to be the issue. Billing information is required to make external calls from Firebase.

**Comment by amicming** [comment]
Even those I am getting this error if I sent a message to multiple phone numbers. I have enough credits.

**Comment by childish-sambino** [comment]
@amicming Please open a new issue with the details of what’s going on.

**Comment by cherucole** [comment]
> It's time to whip out your Credit Card if you want to use Firebase to make 3rd party API calls

I had the same error too but after entering my credit card on firebase the error went away
