### ISSUE TITLE
TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by subodhpareek18** [twilio/twilio-node#295]
**Version:**
3.8.1

### Code Snippet
```js
const twilio = new Twilio(creds.accountSid, creds.authToken);
const chatClient = twilio.chat.services(creds.chatServiceSid);

// ....
JSON.stringify(chatClient.channels(id).fetch())
```

### Exception/Log
```
TypeError: Converting circular structure to JSON
```

**Comment by subodhpareek18** [comment]
For now I've written this utility that removes some of the keys (that I anyways didn't really want) and that removes all the circular references.

I think there should be an options object that we could pass while instantiating twilio which could remove these references for us.

```js
import R from 'ramda';

const dangerous = ['_version', '_context', '_solution'];
const omit = R.omit(dangerous);

export default data => {
  if (R.is(Array, data)) {
    return { data: R.map(omit, data) };
  } else {
    return omit(data);
  }
};
```

**Comment by efossier** [comment]
@subodhpareek18 This worked for me, perhaps different versions of node fail to deserialize the data? Which version are you running? 

```
> client.chat.services("IS1234").channels("CH1234").fetch().then((res) => console.log(res));
{ state: 'pending' }
> ChannelInstance {
  _version:
   V2 {
     _domain:
      Chat {
        twilio: [Object],
        baseUrl: 'https://chat.twilio.com',
        _v1: undefined,
        _v2: [Circular] },
     _version: 'v2',
... } }
```

**Comment by subodhpareek18** [comment]
Sorry, I wasn't fully clear on my requirements, so when I `console.log` the above then it gives me this Object `ChannelInstance` and that's fine, but I need to send the response back to the client that called my method. 

For that to happen I need to send it as JSON, because only JSON can travel across HTTP not JS Objects.

```js
const channel = await this.client.channels(id).fetch()
return Promise.resolve(channel)
```
This is where I get an error where my web server framework tries to JSON.stringify the channel object.

**Comment by subodhpareek18** [comment]
I think a `{ lean: true }` or `{ raw: false }` would be a good idea. Many ORMs like `sequelize` and `mongoose` do it. Or else there could be a `.toJSON()` method.

**Comment by subodhpareek18** [comment]
This will also improve the performance, especially for find calls. If the user simply wants a plain object without any context, etc then the helper library could circumvent Object Creation and simply return the response it got from the twilio api.

**Comment by efossier** [comment]
Ah I see, to be clear the circular references are done on the client side so passing a `lean` or `raw` option in the api call would be a bit strange. I think its reasonable to investigate a `toJSON` method. Thanks for flagging this!

**Comment by subodhpareek18** [comment]
So it depends on the actual requestor of the resource. If a piece of code within my server was calling another piece of code then it wouldn't be an issue. 

But if I want to have a full integration with twilio chat and make a REST API enabled microservice for it that other frontends and servers could depend on. Then I would want to have a way to get a plain JS object with no circular references, so that I can easily pass the response around without worrying about whether it can be transported over HTTP or Websocket calls or through some other transport.

So in this case my server wouldn't actually get this request:
```
GET myChatMicroService.com/twilio/chat/channels?lean=true
```

I would implicitly apply it myself knowing the request has come over the HTTP or WS transport. And the call would simply be
```
GET myChatMicroService.com/twilio/chat/channels
```

**Comment by efossier** [comment]
@subodhpareek18 Wouldnt implementing `toJSON` on our resources be the best of both worlds? This way you can still use the circular references in code to get a resources version, domain, etc. but when it comes to serializing only the essential stuff would get serialized?

**Comment by subodhpareek18** [comment]
Yes it would be, though I'm thinking that `toJSON` is actually not that good an idea, a plain JS object should still be returned. Because many web server frameworks automatically JSON.stringify stuff. So in this case it might so happen that JSON..stringify gets called twice.

So maybe a `toPlain` or `toNonCircular` would make more sense. Users can then safely call `JSON.strringify` on it whenever they want.

**Comment by subodhpareek18** [comment]
`{ lean: true }` might make sense when the users already know that they just want the plain data every time and nothing else. And it would also boost performance. 

Which is my current requirement, but of course it has to be make sense for a lot of people, before I can expect anybody to invest time on it.

**Comment by efossier** [comment]
I've created a ticket internally to evaluate the different options and implement one so we should hopefully get to this in the near future.

**Comment by timwis** [comment]
Ran into this using graphcool. Had to manually pick/omit fields too :/

**Comment by tafs7** [comment]
it seems that the response from the twilio api via the client is not a well formed JSON response.
```
 _version:
   V2 {
     _domain:
```
In this example, `V2` is not defined in a way that can be deserialized into a JSON object.  Am I missing something?

**Comment by cymen** [comment]
@efossier Is there any update to this?

**Comment by efossier** [comment]
@cymen and anyone else interested, I apologize for not getting to this sooner. Our team has been swamped in work and we haven't had time to get to this. I looked into it a little and it doesn't seem to be much work in our code generator tool so I'll do my best fix this in the next couple of weeks.

@tafs7 You're correct there currently isnt a way to serialize the objects returned by the library to pure JSON. Your best bet is subodhpareek18's workaround for now.

**Comment by efossier** [comment]
I've created this PR which should solve this issue, would appreciate any feedback you all have.

https://github.com/twilio/twilio-node/pull/325

**Comment by efossier** [comment]
A `toJSON` method has been added to all instance objects in `3.13.0`. Thank you all for your patience.

**Comment by kenriy** [comment]
hello, Converting circular structure to JSON ,how to do?
