### ISSUE TITLE
List Method should also accept a skip attribute.

### ISSUE THREAD

**Issue by subodhpareek18** [twilio/twilio-node#296]
**Version:**
3.8.1

### Feature Request

Currently the node client list method accepts a limit attribute.
```js
this.client.roles.list({ limit: 50 })
```

But it's not possible to pass a skip params as well that would take us to the next page skipping the number of records mentioned.

```js
// returns the first page (first 50 records)
this.client.roles.list({ limit: 50, skip: 0 })

// returns the second page (next 50 records)
this.client.roles.list({ limit: 50, skip: 50 })
```

The above would be extremely helpful and intuitive in building a paginated integration.

**Comment by efossier** [comment]
@subodhpareek18 This is currently supported via the `getPage` method, heres an example which accomplishes what you want:

```js
var twilio = require('twilio');
var client = new twilio("AC123", "auth");

// Get the first 50 records
var page;
client.roles.page({limit: 50}).then((result) => page = result);

// Get actual contents of page
page.instances.forEach((role) => console.log(role.sid));

while(page.nextPageUrl != null) {
    client.roles.getPage(page.nextPageUrl).then((result) => page = result);
}
```

Unfortunately the `getPage` doesn't allow passing the `limit` option but the `nestPageUrl` encodes the page size from the first request so you will continue to get the same amount of records per page as the returned in the first page.

Hope this helps, feel free to reopen if this doesnt work for you!

**Comment by subodhpareek18** [comment]
Yes, this does make sense if we are to linearly go from one page to another. But if I were to fetch the 3rd or 4th page directly `{ skip: 150 }` then how can I go about doing that here?

**Comment by efossier** [comment]
@subodhpareek18 We don't support absolute paging in the API (paging to arbitrary spots in the list), we only support relative paging (ie next page, previous page). This is due to resource constraints on our side, api calls would take too long if users could index anywhere into the list of resources.

**Comment by subodhpareek18** [comment]
Okay, got it. Thanks!
