### ISSUE TITLE
Auto-generated docs are missing

### ISSUE THREAD

**Issue by natesilva** [twilio/twilio-node#299]
This must have happened in the last few days. The auto-generated docs that were available at https://twilio.github.io/twilio-node/ are missing.

Workaround is to download this repo and open the docs dir locally, but the docs web site was handy and is referenced from other places like [here](https://www.twilio.com/docs/libraries/node#more-documentation).

**Comment by efossier** [comment]
@natesilva Sorry for the confusion, we've moved all our docs to the main twilio.com domain, you can find that same page at https://www.twilio.com/docs/libraries/reference/twilio-node/
