### ISSUE TITLE
Upgrade moment to 2.19.3

### ISSUE THREAD

**Issue by alltouch** [twilio/twilio-node#304]
NSP check fails with `Regular Expression Denial of Service` error. Required moment upgrade to 2.19.3

**Comment by YasharF** [comment]
https://snyk.io/test/npm/twilio

**Comment by jhdielman** [comment]
@cilindrox @YasharF @alltouch There's an open PR to resolve this. Should be merged soon :)

**Comment by YasharF** [comment]
https://github.com/twilio/twilio-node/pull/305

**Comment by cilindrox** [comment]
Thanks @jhdielman @YasharF !

**Comment by esetnik** [comment]
I have the same issue. Any idea when this is expected to land in the next moment version?

**Comment by kuryaki** [comment]
Gonna add twilio to `.nsprc` ignore in the meantime

**Comment by YasharF** [comment]
Confirming that the issue is now resolved with the release of 3.11.1 and the package is no longer being flagged by nsp.
