### ISSUE TITLE
ChatGrant is not a constructor

### ISSUE THREAD

**Issue by anthonydelgado** [twilio/twilio-node#307]
After a ton of trouble shooting just wanted to answer my own question here just in case anyone else is stuck with this error. So I was using the Twilio Node SDK "twilio": "^3.0.0" in my package.json file and I was trying to use the chat token generator example on the Twilio Docs. I was using the docs for "v3" so I thought "3.0+" would be fine but in actuality I had to switch to "twilio": "3.9.0" to get the "ChatGrant" constructor to work.

**Comment by philnash** [comment]
Apologies @anthonydelgado, we [only updated what was the `IpMessagingGrant` to `ChatGrant` in version 3.9.0](https://github.com/twilio/twilio-node/pull/279). I always recommend you try to work with the latest version of the library if you can.

Thanks for leaving the note though, hopefully it can help someone if they are searching for the same problem in the future.

**Comment by anthonydelgado** [comment]
Thanks Phil 💪
