### ISSUE TITLE
user.userChannels().list() fails to find chat channels

### ISSUE THREAD

**Issue by pushups** [twilio/twilio-node#309]
**Version:**
3.10.0

### Code Snippet
```node
const chatUser = await chatService.users(identity).fetch();
const channels = await chatUser.userChannels().list();
```

### Exception/Log
```
status=404, message=The requested resource /Services/*serviceSid*/Users/*identityString*/Channels was not found, code=20404, moreInfo=https://www.twilio.com/docs/errors/20404, detail=undefined
```

### Steps to Reproduce
1. With a valid chatService object, fetch a user via their `identity` string.
2. Attempt to fetch a list of their channels.

### Result
A 404 occurs because the user channels resource is only available via the `userSid` and not the `identity` value. The `chatUser.userChannels().list()` call should be able to correctly supply the `userSid` and not the `identity` string. (Or the REST API should accept an identity string).

### Workaround
```
let chatUser = await chatService.users(identity).fetch();
chatUser = await chatService.users(chatUser.sid).fetch();
const channels = await chatUser.userChannels().list();
```
This correctly instantiates the `chatUser` object with the `userSid` instead of the identity so that it can correctly make the `userChannels().list()` request.

**Comment by efossier** [comment]
@pushups Yes this is counter intuitive and I'm sorry for the confusion. One question: are you using the `v1` chat api or `v2`? ie which does your code look like?
```js
// v2
chat.v2.services('IS2134').users('bob').fetch();
// or
chat.services('IS1234').users('bob').fetch();

// v1
chat.v1.services('IS1234').users('bob').fetch();
```

**Comment by pushups** [comment]
@efossier We are using the `v2` api.

```
const chatClient = new Twilio(accountSid, authToken);
const chatService = chatClient.chat.services(serviceSid);
```

**Comment by efossier** [comment]
@pushups Ok, thanks for the information. This should definitely be supported and is a bug on our end. I've brought it up with the relevant team.

**Comment by efossier** [comment]
@pushups We just pushed an update to the API which should fix this. Feel free to reopen if you continue to have issues.
