### ISSUE TITLE
When first using a target number (international) the sms is queued and sent but .catch is triggered

### ISSUE THREAD

**Issue by rluncasu** [twilio/twilio-node#313]
I've observed this on v 3.11.0.
When I first used new phone numbers to send sms to, the messages were correctly sent but instead of triggering .then(result=>{}) , the .catch(err=>{}) was triggered, oddly enough with no err (undefined).

I haven't got any steps to reproduce as I can't reproduce it yet but It happened on at least three occasions so far.

**Comment by childish-sambino** [comment]
This is tough to debug without more details. Recommend [filing a support ticket](https://twilio.com/help/contact) if you're able to pull the message SID or re-opening this ticket with the steps to recreate the issue.
