### ISSUE TITLE
Document TwiML functionality

### ISSUE THREAD

**Issue by natesilva** [twilio/twilio-node#314]
*Note: These issues are for bugs and feature requests for the helper libraries.
If you need help or support, please email help@twilio.com and one of our experts
will assist you!*

**Version:** 3.11.0

### Feature Request

Document the TwiML functionality — `VoiceResponse`, `MessagingResponse`, `FaxResponse`. The functions in `lib/twiml` have inline documentation, but it’s not included in the published `docs/`.

**Comment by childish-sambino** [comment]
Do the docs here suffice?
* https://www.twilio.com/docs/voice/twiml
* https://www.twilio.com/docs/sms/twiml
* https://www.twilio.com/docs/fax/twiml
