### ISSUE TITLE
ESOCKETTIMEDOUT issue

### ISSUE THREAD

**Issue by ShMcK** [twilio/twilio-node#317]
Twilio is failing 10-25% of the time with the below ESOCKETTIMEDOUT error.

**Version:**
3.11.1

### Exception/Log
```
"error":{"code":"ESOCKETTIMEDOUT","connect":false}
```

See 21 related issues with the dependency [request](https://github.com/request/request/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+ESOCKETTIMEDOUT)

### Steps to Reproduce
1. Run several instances of a AWS lambda each instantiating Twilio node in parallel
2. Add logging to record the returned errors
3. Notice that somewhere between 1 in every 5-10 messages fails with the above error

**Comment by nicholasstephan** [comment]
I'm getting this same error. Did you ever identify a cause?

**Comment by ShMcK** [comment]
Only handled it with a retry strategy. It hasn't failed consecutively more than 3 times.

**Comment by QuotableWater7** [comment]
We are also seeing this error very frequently, and we also get it passing after a retry or two 🤔

**Comment by dkundel** [comment]
Hey folks! 

This seems to be an AWS Lambda issue. They are throttling web requests and as a result the Twilio requests are being throttled. The only solution here seems to use a retry logic like suggested in #338.

Cheers,
Dominik
