### ISSUE TITLE
date parser bug with moment 2.19.3

### ISSUE THREAD

**Issue by dnalborczyk** [twilio/twilio-node#318]
twilio: v3.11.2
nodejs: v9.5.0

twilio, or rather moment (v2.19.3),  is parsing certain RFC2822 dates wrong, and leaves some dates as strings, instead of a Date object.

affected code path:
https://github.com/twilio/twilio-node/blob/14a85ad2c8a0b999f71642585e8a5a680349f084/lib/base/deserialize.js#L61

https://github.com/twilio/twilio-node/blob/14a85ad2c8a0b999f71642585e8a5a680349f084/lib/base/deserialize.js#L10

I haven't debugged which version of moment fixed the issue, but 2.20.1 seems to work.
Not sure if this is a bug in moment, or if the formatting string is wrong ('ddd, DD MMM YYYY HH:mm:ss [+0000]')

example repro:
```javascript
const { startDate } = await client.calls(sid);
```

if *startDate* (and any other date for that matter) is e.g. *'Wed, 09 Aug 2017 01:13:35 +0000'* as fetched with the REST API, parseDate() m.isValid() will be false, and a string will be returned, as supposed to a date object.

that makes me thinking, why is a string being returned in the first place? was that meant to be some sort of an escape hatch? and why is the API not returning an ISO date which would make matters simpler to begin with?

**Comment by childish-sambino** [comment]
Fixed by https://github.com/moment/moment/issues/4227
