### ISSUE TITLE
Realtime Google Speech Transcription

### ISSUE THREAD

**Issue by tvvignesh** [twilio/twilio-node#320]
I tried Twilio Speech recognition and was not so happy with the accuracy of conversion to text. I wanted to use Google Speech API for transcription and I was following this article: https://medium.com/@mheavers/better-twilio-transcriptions-with-the-google-web-speech-api-eb24274c5e3

There, they record the speech and then send the details to Google Speech API. Is there any way to do it realtime without hanging up the call. Something like a replacement for Twilio Speech Recognition.

Thanks in advance.

**Comment by dkundel** [comment]
Hey @tvvignesh,

Can you give me a bit more detail on where it's falling short? Is it a particular language or any special terms? Did you use hints for the speech recognition? I would love to give that feedback to the team to make sure we improve on this if you are not satisfied. 

As for using the Google Speech API the only way currently is to do it via the recording. There is no need for you to actually hang up the call but the entire process would be performed asynchronously so creating a "real-time" effect will be significantly harder with this.

Cheers,
Dominik

**Comment by tvvignesh** [comment]
Thanks for your reply @dkundel  I have raised this as a ticket as well and have been talking to Jan Dusek your support team. I was given the suggestion to use hints by the support team as well which I plan to use soon. 

You can try any of these (I have added the possible queries there):
https://alpha.ramco.com/ivr-aviation-timesheet.html
https://alpha.ramco.com/ivr-aviation-summary.html
https://alpha.ramco.com/ivr-logistics-summary.html

We use wit.ai to do entity extraction and intent recognition.

I was thinking of something like https://github.com/nexmo-community/voice-google-speechtotext

**Comment by BobIpDatapoint** [comment]
Hi @tvvignesh , did you get any clue to improve Twilio speech recognition accuracy? I'm facing same problem and my experience is Google Speech and Amazon work much better transcribing audio.

Cheers!

**Comment by tvvignesh** [comment]
@BobIpDatapoint : While I tried a lot of ways, the quality of recognition did not get improved and stayed the same. So, I ended up just avoiding speech recognition and sticking to IVR.

**Comment by onofrioP89** [comment]
Any news about it?

**Comment by amirkargar** [comment]
I'm facing the same issue. Any work around or any better solution for this?

**Comment by onofrioP89** [comment]
The performance/accuracy of speech recognition of Twilio from 1 week is very bad

**Comment by amirkargar** [comment]
@onofrioP89 by performance, do you mean speed wise? if yes, how long does it take usually?

**Comment by onofrioP89** [comment]
we are seeing delays (partialResultCallback and action) and incorrect transcripts for a week. a week ago it was much better

**Comment by childish-sambino** [comment]
Does [Media Streams](https://www.twilio.com/blog/media-streams-public-beta) help to accomplish what you're looking for?

**Comment by tvvignesh** [comment]
@childish-sambino Exactly but sadly when I saw I was able to find only one connector (from Gridspace) so far. I understand that it is in beta but something like sending it via a custom protocol like WebRTC/RTMP/something else will help or you can send it to partners who do that.

**Comment by gambhirpulkit** [comment]
Any progress in this till now? Is it possible to stream audio and convert speech to text using Google speech API instead of Twilio voice recognition to convert from speech to text?

**Comment by tvvignesh** [comment]
I have not tried it but there is a blog about this here: https://cloud.google.com/blog/topics/partners/using-google-cloud-speech-to-text-to-transcribe-your-twilio-calls-in-real-time
