### ISSUE TITLE
Cannot send SMS with MessagingServiceSid (3.11.3)

### ISSUE THREAD

**Issue by xyk2** [twilio/twilio-node#323]
I am trying to send SMS messages with a messaging service. When sending an SMS message with `MessagingServiceSid` and no `from`, the request errors out. The docs say that either a `from` or `MessagingServiceSid` is required, however requests with only the SID errors out.

**Version:** 3.11.3

### Code Snippet
```node
twilio.messages.create({
	MessagingServiceSid: 'config.twilio_messagingServiceSid',
	body: 'Hello from Node',
	to: 'NUMBER'
})
.then(message => {
	console.log(message.sid);
})
.catch(err => {
	console.log(err);
});
```

### Exception/Log
```
{ [Error: A 'From' phone number is required.]
  status: 400,
  message: 'A \'From\' phone number is required.',
  code: 21603,
  moreInfo: 'https://www.twilio.com/docs/errors/21603',
  detail: undefined }
```

### Steps to Reproduce
1. Install package version 3.11.3
2. Attempt to send an SMS message with a messaging service using only the MessagingServiceSid

In the meantime, I downgraded back down to 2.11.1 which works with the same code.

**Comment by dkundel** [comment]
Hey @xyk2,

To make it more user friendly for Node.js developers we flip all request properties to `camelCase` rather than `CamelCase`. Meaning for this one you want to use `messagingServiceSid` rather than `MessagingServiceSid` and it should work.

Cheers,
Dominik

**Comment by usamamashkoor** [comment]
I am still facing the issue in 3.x.x version
