### ISSUE TITLE
How to send SMS longer than 1600 characters?

### ISSUE THREAD

**Issue by artofspeed** [twilio/twilio-node#327]
I'm trying to send a relatively long SMS, but it says `The concatenated message body exceeds the 1600 character limit.`

Is there any way to surpass this limit? Thanks.

**Comment by keanlo93** [comment]
Did you fixed it?

**Comment by childish-sambino** [comment]
SMS character limit is 1600: https://www.twilio.com/docs/glossary/what-sms-character-limit

Please [file a support ticket](https://twilio.com/help/contact) if you need additional assistance.
