### ISSUE TITLE
TypeError: Cannot read property 'isTTY' of undefined

### ISSUE THREAD

**Issue by rubencg195** [twilio/twilio-node#332]
*I am trying to implement a group video chat, I have tried with the latest version 3.13.1 and downgrade until 3.11.0 but all of them give the same error. I've also tried with version 2.11.1 and the error stopped but the function require('twilio').jwt.AccessToken; returned null in v2x*

**Version:**

### Code Snippet
```node
# import * as twilio from 'twilio';

### Exception/Log
```
<place exception/log here>
![image](https://user-images.githubusercontent.com/25628940/37574119-206e0956-2ae4-11e8-9ed5-90c1e81c2b8f.png)

package.json
![image](https://user-images.githubusercontent.com/25628940/37574132-44f9cdb4-2ae4-11e8-9419-5cd2c8f0e301.png)

ReactJS Screen Log
![image](https://user-images.githubusercontent.com/25628940/37574179-a94dfb82-2ae4-11e8-9c6c-fc7b885d6afb.png)

```

### Steps to Reproduce
1. Intall using npm install twilio --save
2.Install npm install twilio-video --save
3. import * as twilio from 'twilio';
4. var AccessToken = require('twilio').jwt.AccessToken;

**Comment by freeboarder42** [comment]
I have exactly the same issue. If you found a solution please post.

**Comment by dkundel** [comment]
Hey @rubencg195 and @freeboarder42!

The `twilio` module is designed to be used server-side only. If you are building a serverless application and need to use the library to generate an access token, I would recommend to [create a Twilio Function in the Console](https://www.twilio.com/console/runtime/functions/manage) for it and use that.

Cheers,
Dominik

**Comment by m1729** [comment]
Hey, dkundel!

I'm trying to build a chat application and has the same problems. Please fix the issue or specify the workaround for the problem. 'Twilio functions' we are looking for. If you have such function than definitely you have a working solution for Amazon Lambda. Just need the source for download.

**Comment by m1729** [comment]
Ok. Thank you for your silent help. Downgrade to 2.11.1 version and little code redesign solves the problem. Still eager to see the solution for the latest release.

**Comment by jayanth1991** [comment]
hey @m1729 if you are building using ReactJS, here is how we were able to resolve it
In the public `index.html` we listed this as a script:
```html
<script type="text/javascript" src="//media.twiliocdn.com/sdk/js/client/v1.4/twilio.min.js"></script>
```

And in the React components (or anywhere in React) you can do this:
`let Twilio = window.Twilio;`
