### ISSUE TITLE
Feature Request: Add way to specify proxy for requests

### ISSUE THREAD

**Issue by dkundel** [twilio/twilio-node#336]
### Feature Request

The `request` library we are using offers a way to specify a `proxy` but there is currently no way for developers to pass that into our default `RequestClient`. We should allow to specify it in the configuration of the constructor or find a way to pass it on a per request basis.

**Version:** any

### Code Snippet
```node
// Proposed solution:
// Specify the proxy globally
const client = twilio('accountSid', 'authToken', { proxy: 'proxyUrl' });
```

**Comment by childish-sambino** [comment]
This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.

**Comment by tlawrie** [comment]
Is there any update on this?

**Comment by tlawrie** [comment]
I have submitted a PR for this issue 👍
