### ISSUE TITLE
ECONNRESET sometimes when create calls

### ISSUE THREAD

**Issue by markmacau** [twilio/twilio-node#338]
Hi,

I gott ECONNRESET error SOMETIME. It is strange. Most of time it success without error. The ratio of error/success is 1:10 or even lower.  When I get an error, then retry without any change of code, it always success. Any idea why it happen and how to prevent it? Thanks in advance.

Mark

**Version:**
3.15.1
on AWS Lambda Node.js 6.10

### Code Snippet
```node

 twilio.calls
      .create({
params
      })
.catch(function(error){
          console.log(error)
      })
```

### Exception/Log
```
at TLSSocket.socketCloseListener (_http_client.js:285:23)
at emitOne (events.js:101:20)
at TLSSocket.emit (events.js:188:7)
at _handle.close (net.js:497:12)
at TCP.done [as _onclose] (_tls_wrap.js:332:7) code: 'ECONNRESET'
```

### Steps to Reproduce
1.
2.
3.

**Comment by spalmertwilio** [comment]
Lambda has throttles on network requests which are not specific to Node.JS or Twilio.  So a backoff and retry is the only solution.  Please review:  https://github.com/tim-kos/node-retry

**Comment by dkundel** [comment]
I'll close this issue for now since there seems to be no solution for this on our side since it's Lambda related.

Cheers,
Dominik
