### ISSUE TITLE
Send sms to a random input number

### ISSUE THREAD

**Issue by CrescensMay** [twilio/twilio-node#342]
how can I send a SMS to a random number seems to not working,

String phone = resquest.getParameter("phone);
String message = String.valueOf(new Random().nextInt());
Twilio.init(ACCOUNT_SID, AUTH_TOKEN);

            Message message1 = Message.creator(
                    new PhoneNumber(phone),  // To number
                    new PhoneNumber("+17XXXXXX"),  // From number
                       message                   // SMS body
            ).create();

**Comment by dkundel** [comment]
Hey @CrescensMay,

You should not be able to send an SMS to a random number but only to valid phone numbers. What's your use case for this? 

Cheers,
Dominik
