### ISSUE TITLE
config.sample.js - No such file as per README instructions

### ISSUE THREAD

**Issue by colindaly** [twilio/twilio-node#348]
_To run live tests (such as client.live.spec.js) against your Twilio account, you will need to create a local configuration file. In the project root directory, do the following:

    cp config.sample.js config.js
    Edit config.js with your account information, a Twilio number, and your own mobile number
    Run the live tests_

**Comment by dkundel** [comment]
Hey @colindaly!

Thanks for reaching out and showing this outdated information. I updated the README.md respectively. 

Have a great weekend,
Dominik
