### ISSUE TITLE
Release number at the end of its billing cycle

### ISSUE THREAD

**Issue by yadavanand** [twilio/twilio-node#350]
Is there a way using which I can release a particular number at the end of its billing cycle.
I am refering [this](https://www.twilio.com/docs/usage/api/usage-records) link.
But in that link, I am not able to find/locate anything that gives me the current bill cycle for a particular number.
Please help me with that.

One more question when does Twilio bill me for a particular number?
I am referring this [link](https://support.twilio.com/hc/en-us/articles/223135227-How-and-when-are-phone-numbers-billed-)

From what I understand,
If I purchase a number on 24/05/2018,
current months cycle would end on 23/06/2018,
Next month charge will be on 24/06/2018.

Is that correct?

**Comment by dkundel** [comment]
Hey @yadavanand,

Could you reach out to help@twilio.com? They should be the best ones to assist you on this issue :) 

Cheers,
Dominik
