### ISSUE TITLE
DTMF tones arent playing long enough and MP3 version isnt playing back

### ISSUE THREAD

**Issue by Technickster** [twilio/twilio-node#367]
I am having an issue playing back DTMF tones using twiml, they wont play over mp3 and the ones using the digits option of <play> in twiml dont play correctly or long enough from what I can tell.

**Version:**
3.18.0

## USING Digits
The tone does not play long enough for the other end to recognise it. I am dialing an automated service, it works fine when using my normal phone and keypad, so I can only assume it is the duration that it is the length.

```node
twiml = new twilio.twiml.VoiceResponse()
twiml.play(digits:   '1')
```
## USING Audio Files
So I thought maybe I just play the tone from an MP3 but I only hear a blip of it but then nothing for the duration. I can play anything else that I made in the same way, but not a dtmf tone. You can see the url for the tone if you wanted to try it. The .wav file is in the same bucket.

```node
twiml = new twilio.twiml.VoiceResponse()
twiml.play('https://s3-us-west-2.amazonaws.com/dtmf-tones/1.mp3')
```

Is there an issue playing the DTMF tones over MP3 or WAV or is there a way to increase the length of the dtmf tone from twilio? 

Thanks in advance

**Comment by imthepitts** [comment]
Hi @Technickster, 

Sorry for the trouble. This behavior isn't controlled by the helper library, but is dependent on the downstream telecom infrastructure. Please reach out to our Support Team for assistance with this issue: https://www.twilio.com/help/contact

All the Best,
Zack

**Comment by SethVerishop** [comment]
Just wanted to say I am having this issue also, and it absolutely is something on twilios end that could be changed. For example to open a a garage by pressing 9 when the callbox calls the number, it won't work because the tone isn't recognized. Sometimes it is, about 1 in 5 tries.

**Comment by Technickster** [comment]
@SethVerishop 
Old thread but what I ended up having to do is make my own recordings of the DTMF tones and play those the same way you play a file. There is something weird going on with Twilio's thing or where ever it was coming from.
