### ISSUE TITLE
Error: Error reading response: Response does not contain content type

### ISSUE THREAD

**Issue by jimmylogic** [twilio/twilio-node#369]
Hi

I am getting this error in statusCallback on Twilio dashboard page

I am using 

`  	res.status(200)
    .contentType('text/html')
    .send();`

To send response to twilio

**Comment by imthepitts** [comment]
Hi @jimmylogic, 

Sorry you're having trouble. This is not an issue with the helper library, but you can usually solve this by replying to status callbacks with a 204 No Content.

Please contact Twilio Support if you need further assistance with your status callback response.

https://www.twilio.com/help/contact

All the Best,
Zack
