### ISSUE TITLE
twilio the development server returned code 500

### ISSUE THREAD

**Issue by Hypothesis-github** [twilio/twilio-node#370]
![hjghj](https://user-images.githubusercontent.com/20628299/43534872-a4c73cb4-95cd-11e8-9ff1-090a314d42db.jpg)
**Version:** "twilio": "^3.18.0",

```
  const accountSid = 'AC2d890ba28cf3f4b595a3dbb248608a9a'
    const authToken = 'bff54d357195b72f8a223aeed3335343'
    var twilio = require('twilio');
    const client = new twilio(accountSid, authToken);
```

### Exception/Log
```
The package at ".C:\\Users\\shaha\\Documents\\swipe2\\node_modules\\twilio\\lib\\webhooks\\webhooks.js" attempted to import the Node standard library module "crypto". It failed because React Native does not include the Node standard library. Read more at https://docs.expo.io/versions/latest/introduction/faq.html#can-i-use-nodejs-packages-with-expo
```

### Steps to Reproduce
Just include the code inside any react native

**Comment by Hypothesis-github** [comment]
This issue cannot be fixed by using expo at the moment

**Comment by dkundel** [comment]
Hi @Hypothesis-github,

This library is not supposed to be used in any client-facing code. You shouldn't expose your credentials in a client application. Similarly you should avoid exposing them here :) 

What were you trying to do?

Cheers,
Dominik

**Comment by imthepitts** [comment]
@Hypothesis-github please change your Auth Token as soon as possible, in case anyone saw your original post.

Instructions:
https://support.twilio.com/hc/en-us/articles/223136027-Auth-Tokens-and-How-to-Change-Them

Please contact Support if you need assistance with that process: 
https://www.twilio.com/help/contact

All the Best,
Zack
