### ISSUE TITLE
TypeScript Error: `Beep` in reservation update is the wrong type, should be boolean | string

### ISSUE THREAD

**Issue by evanhuang8** [twilio/twilio-node#379]
*Note: These issues are for bugs and feature requests for the helper libraries.
If you need help or support, please email help@twilio.com and one of our experts
will assist you!*

This definition is wrong: https://github.com/twilio/twilio-node/blob/421d9f1754f0077caad87923138fd29d9ae0423e/lib/rest/taskrouter/v1/workspace/task/reservation.d.ts#L87

The `Beep` option should be either true false or a string, but if you set it to be true/false right now it pops an error. Using a string form of `'false'` does NOT achieve the same result.

**Version:**

### Code Snippet
```node
let result = await this.client
      .workspaces(wsid)
      .tasks(tsid)
      .reservations(rsid)
      .update({
        instruction: 'conference',
        to: clientID,
        from: internalNumber,
        accept: true,
        beep: false,
        endConferenceOnExit: true,
        conferenceStatusCallback: statusUrl,
        conferenceStatusCallbackEvent: ['start', 'end', 'join', 'leave'],
        conferenceStatusCallbackMethod: 'POST'
      });
```

### Exception/Log
```
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string or Buffer. Received type boolean
        at write_ (_http_outgoing.js:601:11)
        at ClientRequest.write (_http_outgoing.js:573:10)
        at Request.write (/Path/to/project/node_modules/request/request.js:1500:27)
```

### Steps to Reproduce
1. Call the update method with `Beep` to be false
2.
3.

### Feature Request
_If this is a feature request, make sure you search Issues for an existing
request before creating a new one!_

**Comment by dkundel** [comment]
Hi @evanhuang8,

Thanks for flagging that. This fix has to be done in our code generation tool so I won't be able to push a quick fix. @cjcodes can you put that on the radar for your team to get this fixed? :) 

Cheers,
Dominik

**Comment by cjcodes** [comment]
@evanhuang8 (cc @dkundel) I see you have a thread going with support about this, but I wanted to update the public ticket for the sake of visibility.

The library doesn't support boolean values for REST requests (they would end up just getting converted to strings anyway for a `application/x-www-form-urlencoded` `POST`).

The issue causing this behavior isn't related to this, and has been escalated to the TaskRouter engineering team.

I'm going to close this issue, as it's not an issue specific to the helper libraries.

Thanks for reporting, @evanhuang8!
