### ISSUE TITLE
Twilio Studio Namespace not available

### ISSUE THREAD

**Issue by eorroe** [twilio/twilio-node#381]
**Version:**
4.6.0

`twilio.studio` is undefined

Looking at the [docs](https://www.twilio.com/docs/studio/rest-api)

I should be able to use the following code:

```
TwilioClient.studio.flows('FW9d816f0b90d2a10b913868462e339d29').executions.create(
  { to: '+1646221xxxx', from: '+1331481xxxx', parameters: JSON.stringify({name: "Clément"})}
).then(function(execution) { console.log(execution.sid); });
```

**Comment by imthepitts** [comment]
Hi @eorroe,

Sorry you're having trouble. Version 4.6.0 doesn't exist in the Node.js helper library. The latest version is 3.19.2: https://github.com/twilio/twilio-node/blob/master/CHANGES.md

Your code snippet works fine on my environment at version 3.19.2. Would you please verify the version you're using?

If you need further assistance using the helper library or with the docs, please contact our Support team: https://www.twilio.com/help/contact

All the Best,
Zack

**Comment by eorroe** [comment]
Not sure why my configuration had 4.6.0 that fixed it thanks!
