### ISSUE TITLE
Typing via index.d.ts is incomplete  

### ISSUE THREAD

**Issue by Shahaed** [twilio/twilio-node#387]
Typing does not export the type of the client (`TwilioClient`)

```ts
    import * as twilio from 'twilio';
    private client: twilio: any; //type is not exported

    constructor(config: TwilioConfig) {
        this.client = twilio(config.account_sid, config.auth_token);
    }

```

**Comment by dkundel** [comment]
Hi @Shahaed!

There is two components to this actually. The first one is that indeed we are missing to export `Twilio` as an additional class and is being addressed in #389.


The other one, however, is an import issue. The current way the library is written in JS, influenced how we had to write the TS typings. You have to import the following way if you want the proper typing support:

```
import twilio = require('twilio');
```

This way you'll get the full typings support. You can check it out an example in [example.ts#L2](../blob/master/examples/typescript/example.ts#L2).

Let me know if this doesn't work to me.

Cheers,
Dominik

**Comment by ewisuri** [comment]
With #389, the exported client type will be `Twilio` in the namespace:
```typescript
import * as twilio from 'twilio';
let client: twilio.Twilio = twilio(sid, token);
```

**Comment by Shahaed** [comment]
@ewisuri nice! Thanks

**Comment by dkundel** [comment]
I'll close this issue already. @cjcodes should be merging this in.

Cheers,
Dominik
