### ISSUE TITLE
scmp 0.0.3 deprecated 

### ISSUE THREAD

**Issue by kamronbatman** [twilio/twilio-node#392]
SCMP is out of date and should be updated to take advantage of better crypto standard functions.

**Version:** 3.23.1

### Code Snippet
```node
function validateBody(body, expectedValue) {
  var hash = crypto
    .createHash('sha256')
    .update(Buffer.from(body, 'utf-8'))
    .digest('base64');

  return scmp(expectedValue, hash);
}
```

### Exception/Log
```
npm WARN deprecated scmp@0.0.3: scmp v2 uses improved core crypto comparison since Node v6.6.0
```

### Steps to Reproduce
1. Install `twilio` via `npm`

**Comment by csantanapr** [comment]
I'm interested on this fix, I'm also affected by the Warning.

Is there a ETA when a new version of the library would be release?
