### ISSUE TITLE
Is client threadsafe?

### ISSUE THREAD

**Issue by jordan0159** [twilio/twilio-node#400]
Hey, I was wondering if the client itself is thread safe. Say I want to call client.messages.create asynchronously for each incoming api request, would I need to create a new client object per request or would I be able to simultaenously use the same client object permanently - as long as the api is running?

**Comment by childish-sambino** [comment]
I don't see anything in the client that's not thread-safe (other than some internal last request/response tracking but that's just for the unit tests). Feel free to thread away!
