### ISSUE TITLE
Typescript Notify V1 notification - data parameter doesn't match docs

### ISSUE THREAD

**Issue by mhaywardSchlow** [twilio/twilio-node#408]
**Version: 3.27.1**

Hello,

Thanks for the awesome library -- I'm running into one small issue.

The data property for the notification service is listed in the [documentation](https://www.twilio.com/docs/notify/api/notification-resource) as an object however the Typescript bindings are giving me a type-mismatch error saying it needs to be a string. 

Looking at the code, it looks like it's referenced as a string property [here](https://github.com/twilio/twilio-node/blob/master/lib/rest/notify/v1/service/notification.js#L65), but in other sdks like [twilio-python](https://github.com/twilio/twilio-python/blob/master/twilio/rest/notify/v1/service/notification.py#L52), it is listed as a dict or in the [twilio-csharp](https://github.com/twilio/twilio-csharp/blob/master/src/Twilio/Rest/Notify/V1/Service/NotificationResource.cs#L116) it is listed as an object.

### Code Snippet

The below snippet gives me an error
```node
service.notifications.create({
                    identity,
                    data: {
                        title, 
                        notId, 
                        body,
                    }
                });
```
Error:
```
Argument of type '{ identity: any; data: { title: any; notId: number; body: any; }; }' is not assignable to parameter of type 'NotificationListInstanceCreateOptions'.
  Types of property 'data' are incompatible.
    Type '{ title: any; notId: number; body: any; }' is not assignable to type 'string'.
```

Should the typescript bindings be modified to match the types of the other SDKs or am I doing something wrong?

Thanks for your help!

**Comment by packlam** [comment]
**Version: 3.33.0**

This is also the case for many of the other properties on the `NotificationListInstanceCreateOptions` interface. The following properties are all typed as strings when the [documentation](https://www.twilio.com/docs/notify/api/notification-resource) states that they're objects:

- `alexa`
- `apn`
- `data`
- `facebookMessenger`
- `fcm`
- `gcm`
- `sms`
