### ISSUE TITLE
validateExpressRequest as documented works with twiml but not event callbacks

### ISSUE THREAD

**Issue by unfinishedteleporter** [twilio/twilio-node#411]
Not sure if this is the right place - its not technically a problem with the twilio-node library, but with the documentation.

**Version:**
3.28.0
### Code Snippet
```node
let host = req.headers.host;
if (req.protocol === 'https') {
  // Strip off the port, like the requesting twilio server would have
  host = host.substring(0, host.indexOf(':'));
}
const valid = twilio.validateExpressRequest(req, authToken, {host: host});
```

### Steps to Reproduce
1. Have a server using non-standard https port (e.g. 3443)
2. Use the above snippet to process an incoming request from Twilio for TwiML
3. Use the above snippet to process an incoming request from Twilio that is a callback for event (e.g. conference callback)

In (2), it will work. In (3) it will not, unless you remove the line that strips the port.

This indicates that when Twilio generates the signature it strips the port when preparing a request for TwiML, but not for a callback. The reason I was stripping out the port in the first place was because https://www.twilio.com/docs/usage/security states:

>For SMS and voice callbacks over HTTP, Twilio will drop the username and password (if any) from the URL before computing the signature. For SMS and voice callbacks over HTTPS, Twilio will drop the username, password and port (if any) before computing the signature. This behavior will continue to be supported in the 2008-08-01 and 2010-04-01 versions of the API to ensure compatibility with existing code. We understand this behavior is inconsistent, and apologize for the inconvenience.

I assumed in the context of the documentation "callback" means any request from twilio to another server in the process of calls (so twiml or reporting an event). However it seems to be different for different circumstances.

I tried finding other issues/discussions about this, but it was related to stripping out the _standard_ ports, not nonstandard ones.

**Comment by childish-sambino** [comment]
Linking to https://github.com/twilio/twilio-python/issues/402 for tracking (different language, same issue).

The docs were updated today but it looks like the conference callback behavior should also be tested and added to the doc.
