### ISSUE TITLE
The function validateRequest does not exist

### ISSUE THREAD

**Issue by xueyongg** [twilio/twilio-node#413]
How do i validate the request from Twilio? Following the instructions from https://www.twilio.com/docs/usage/security#validating-requests

the library does not have any function named validateRequest. 

Please assist

**Comment by childish-sambino** [comment]
Are you looking at the module itself and not the client instance? Perhaps to clarify:
```
const twilio = require('twilio');
...
console.log(twilio.validateRequest(authToken, twilioSignature, url, params));
```

**Comment by nomankt** [comment]
facing same issue
