### ISSUE TITLE
Typo in RoomAttributes participantIdentity typing

### ISSUE THREAD

**Issue by mkrymski** [twilio/twilio-node#415]
**Version: 3.28 **

Hello, I think there is a typo in RoomAttributes interface in twiml/VoiceResponse.d.ts

`  
  export interface RoomAttributes {
    participantidentity?: string;
  }
`
should be changed to 
`  export interface RoomAttributes {
    participantIdentity?: string;
  }
`

The [docs](https://www.twilio.com/docs/voice/twiml/connect/room) suggest that is should be written in camel case.

Thanks

**Comment by childish-sambino** [comment]
Fixed in version `3.32.0`.
