### ISSUE TITLE
cannot build <ssml> string in VoiceResponse

### ISSUE THREAD

**Issue by abv** [twilio/twilio-node#435]
*Note: These issues are for bugs and feature requests for the helper libraries.
If you need help or support, please email help@twilio.com and one of our experts
will assist you!*

**Version:**

3.30.0

### Code Snippet
```
let say = twiml.say(`Got it. Your zipcode is`);
say.ssmlSayAs({
  'interpret-as': 'digits'
}, zipcode + '');
twiml.say(`near ${resp.city}, ${resp.state_name}.`);
```

### Feature Request
The above code generates the following Twiml:
```
<Say>Got it. Your zipcode is
    <say-as interpret-as="digits">11218</say-as>
</Say>
<Say>near BROOKLYN, New York.</Say>
```

Looking through the code and docs, it appears that there is no way to generate the following Twiml w/ this library:
```
<Say>Got it. Your zipcode is
    <say-as interpret-as="digits">11218</say-as>
    near BROOKLYN, New York.
</Say>
```

While these look the same, the voice engine pronounces them differently. A new `<Say>` is treated as a new sentence. I'd like to use <ssml> tags mid sentence, not just at the end of sentences.

**Comment by abv** [comment]
My solution:
```    let say = twiml.say(`Got it. Your zipcode is`);
    say.ssmlSayAs({
      'interpret-as': 'digits'
    }, 11218);
    say.say.txt(`near Brooklyn, NY.`);```

**Comment by childish-sambino** [comment]
There's a detailed example which uses `addText` [here](https://www.twilio.com/docs/voice/twiml/say/text-speech#generating-ssml-via-helper-libraries). In your case:
```
let say = twiml.say(`Got it. Your zipcode is`);
say.ssmlSayAs({
  'interpret-as': 'digits',
}, zipcode + '');
say.addText(`near ${resp.city}, ${resp.state_name}.`);
```

**Comment by abv** [comment]
@childish-sambino thank you. i overlooked this.
