### ISSUE TITLE
Missing identity in token when not string

### ISSUE THREAD

**Issue by phillip055** [twilio/twilio-node#438]
*Note: These issues are for bugs and feature requests for the helper libraries.
If you need help or support, please email help@twilio.com and one of our experts
will assist you!*

**3.29**

### Code Snippet
```node
function getTwilioToken(some_id) {
  const token = new AccessToken(
    TWILIO_ACCOUNT_SID,
    TWILIO_API_KEY,
    TWILIO_API_SECRET, {
      identity: `${some_id}`
    }
  );
  const chatGrant = new ChatGrant({
    serviceSid: TWILIO_CHAT_SERVICE_SID
  });
  token.addGrant(chatGrant);
  return token;
}
```

### Steps to Reproduce
1. Send in an int

### Feature Request
We should handle/throw error, if the identity is integer or not string. Currently, it produces token but missing the identity field.

**Comment by childish-sambino** [comment]
Interesting. Keeping open for backlog purposes.
