### ISSUE TITLE
Heavy use of _.template

### ISSUE THREAD

**Issue by tflanagan** [twilio/twilio-node#441]
**Version:** 3.30.2

I'm building a desktop application, via Electron, that uses this Twilio client.

The `_.template` function uses `eval()` to accomplish what it does, which when targeting the browser with browserify, is an unsafe practice resulting in forcing one to allow unsafe-eval in their CSP or to rethink the whole application workflow.

I've tried to narrow down the use-cases of this lodash function, but they are everywhere.

Example:
./lib/rest/accounts/v1/credential/aws.js@L51
```js
  AwsListInstance._solution = {};
  AwsListInstance._uri = _.template(
    '/Credentials/AWS' // jshint ignore:line
  )(AwsListInstance._solution);
```

I'm not even sure what the thought process was behind this example. But this example can be seen everywhere!

Why can you not just assign a string:

```js
 AwsListInstance._uri = '/Credentials/AWS';
```

Or at least not use _.template. Use the new template literal syntax: http://es6-features.org/#StringInterpolation

The heavy handed use of this eval lodash function seems almost lazy.

**Comment by childish-sambino** [comment]
@tflanagan Yup, looks like overkill for simple string concatenation/interpolation/templating. You'll find this _everywhere_ since a majority of the library is generated code. Let me see how difficult a change is.

Also relates to https://github.com/twilio/twilio-node/pull/437
