### ISSUE TITLE
incomingPhoneNumbers.remove() has wrong return type in typescript.

### ISSUE THREAD

**Issue by jwalton** [twilio/twilio-node#442]
**Version:** Master

The [JSDoc](https://github.com/twilio/twilio-node/blob/41807bf122d6ec067892c4c4aab7fa14843c829c/lib/rest/api/v2010/account/incomingPhoneNumber.js#L794) for incomingPhoneNumbers.remove() says this function returns a Promise, but [.d.ts](https://github.com/twilio/twilio-node/blob/41807bf122d6ec067892c4c4aab7fa14843c829c/lib/rest/api/v2010/account/incomingPhoneNumber.d.ts#L356) says it returns void.  :(

### Code Snippet
```ts
        return this.client.incomingPhoneNumbers(sms._id).remove()
        .catch(err => console.log(err)) // Property 'catch' does not exist on type 'void'
```

**Comment by jwalton** [comment]
Same problem exists on [addresses.remove()](https://github.com/twilio/twilio-node/blob/41807bf122d6ec067892c4c4aab7fa14843c829c/lib/rest/api/v2010/account/address.js#L591).

**Comment by childish-sambino** [comment]
Relates to https://github.com/twilio/twilio-node/pull/414

**Comment by jwalton** [comment]
Why is #414 closed?

**Comment by childish-sambino** [comment]
There's a comment in the PR. A change is needed in the code generator otherwise changes here would be overwritten on the next release.

**Comment by childish-sambino** [comment]
Working on a PR now.
