### ISSUE TITLE
Autopilot should have audio responses

### ISSUE THREAD

**Issue by SuperRonanCraft** [twilio/twilio-node#443]
### Feature Request
Could we please get audio playback for autopilot to remove the robot voice :D

**Comment by microagent** [comment]
That already exists, you can modify the voice under your Autopilot assistant, Tasks, Stylesheet, say_voice parameter. I recommend: Polly.Joanna, https://www.twilio.com/docs/autopilot/api/assistant/stylesheet.

**Comment by SuperRonanCraft** [comment]
> That already exists, you can modify the voice under your Autopilot assistant, Tasks, Stylesheet, say_voice parameter. I recommend: Polly.Joanna, https://www.twilio.com/docs/autopilot/api/assistant/stylesheet.

I know you can change the voice, but I would like to replace the automatically generated voice with an audio file I uploaded on my assets page

**Comment by childish-sambino** [comment]
This feature is outside the scope of `twilio-node`. I recommend [filing a support](https://twilio.com/help/contact) to request this feature.
