### ISSUE TITLE
Feature Request: Studio - Access to execution_context requires additional calls

### ISSUE THREAD

**Issue by ShelbyZ** [twilio/twilio-node#451]
### Feature Request
To access the execution_context from a Studio flow execution requires additional calls to get access to the data.  It appears to be a related to returning a [ExecutionContextList](https://www.twilio.com/docs/libraries/reference/twilio-node/3.31.0/Twilio.Studio.V1.FlowContext.ExecutionContext.ExecutionContextList.html) when calling executionContext() on a fetch'd execution.  I would expect that there will only ever be a single context associated with a given execution so it would instead go directly to a [ExecutionContextContext](https://www.twilio.com/docs/libraries/reference/twilio-node/3.31.0/Twilio.Studio.V1.FlowContext.ExecutionContext.ExecutionContextContext.html).

I've listed the extra step as `option_one` below and included the direct access, `option_two` to the execution_context (using the execution_sid) below for comparison.

**Version:**
3.31.0

### Code Snippet
```node
let execution = await client.studio.flows(flow_sid).executions(execution_sid).fetch();
let option_one = await execution.executionContext().get().fetch();
let option_two = await client.studio.flows(flow_sid).executions(execution_sid).executionContext(execution.sid).fetch();
```

**Comment by childish-sambino** [comment]
I'm not understanding your request. Are you looking for this?
```
await client.studio.flows(flow_sid).executions(execution_sid).executionContext.get().fetch();
```
