### ISSUE TITLE
constructor functions declared multiple times

### ISSUE THREAD

**Issue by dnalborczyk** [twilio/twilio-node#453]
**Version:**
latest (and prior)

https://github.com/twilio/twilio-node/blob/master/lib/twiml/VoiceResponse.js

several constructor functions are declared multiple times in:
https://github.com/twilio/twilio-node/blob/master/lib/twiml/VoiceResponse.js

this makes it impossible to be used in e.g. `rollup` (for server bundling) and other tools.

it would be great if this would be fixed. I'd also do a PR, but since the file seems to be generated, it seems to be pointless. I suppose that `yoyodyne` (internal twilio tool?) would need to be fixed.

Unfortunately `strict mode` allows multiple declarations with the same name, otherwise this issue wouldn't exist. Fixing this would also have the nice side effect of using less space.

when removed, file size goes down from **77 kb** to **43 kb**

function declarations:

4 x `Pause`
4 x `Play`
4 x `Say`
4 x `SsmlW`
4 x `SsmlSub`
4 x `SsmlSayAs`
4 x `SsmlS`
4 x `SsmlProsody`
4 x `SsmlPhoneme`
4 x `SsmlP`
4 x `SsmlLang`

2 x `Prompt`
2 x `Queue`
2 x `SsmlBreak`
2 x `SsmlEmphasis`

to illustrate: https://github.com/twilio/twilio-node/pull/454

**Comment by childish-sambino** [comment]
Duplicates #394 

Resolving this in the code generator is near the top our backlog.

**Comment by dnalborczyk** [comment]
@childish-sambino  I think this is way more severe than just `Prompt` defined twice, speaking of a duplicate.

**Comment by childish-sambino** [comment]
@dnalborczyk I agree. The fix will be to remove all the duplicates in the TwiML code. Just trying to track this all in a single place.
