### ISSUE TITLE
Adding Custom Headers Property

### ISSUE THREAD

**Issue by rbeatie** [twilio/twilio-node#458]
*Note: These issues are for bugs and feature requests for the helper libraries.
If you need help or support, please email help@twilio.com and one of our experts
will assist you!*

**3.32.0**

### Feature Request
The ability to add headers to an API request with the product helper utilities would provide support for those that need custom headers like `X-Twilio-Webhooks-Enabled`. 

```node

// example of the feature request

const client = twilio('SKxxxx', 'xxxx', {
  accountSid: 'ACxxxx'
});

await client.chat
  .services(serviceSid)
  .channels(channelSid)
  .messages.create({
    body: `This was created by the API. It's ${moment().format('HH:mm:ss')}`,
    from: author,
    headers: {
      "X-Twilio-Example": "Foo" 
      "X-Twilio-Header": "Awesome Value",
      "X-Twilio-Webhooks-Enabled": "true"
   }
});

```

**Comment by childish-sambino** [comment]
For reference: https://www.twilio.com/docs/chat/webhook-events#triggering-webhooks-for-rest-api-events

**Comment by childish-sambino** [comment]
This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it to move up the backlog.

**Comment by eshanholtz** [comment]
The fix for this issue will be included in the next release on 12/4.

**Comment by CatalinVoss** [comment]
@eshanholtz Is this documented somewhere?

**Comment by CatalinVoss** [comment]
For confused souls of the future, the field is called `xTwilioWebhookEnabled`:

```
twilioClient.chat
  .services(your TWILIO_CHAT_SERVICE_SID)
  .channels(your channel)
  .messages.create({
    from: author,
    body,
    ...
    xTwilioWebhookEnabled: true,
  });
```
