### ISSUE TITLE
Twilio Verify VerificationCheck is out of date.

### ISSUE THREAD

**Issue by SmoshySmosh** [twilio/twilio-node#461]
The underlying API for verify has changed but the documentation / library has yet to be updated to reflect these changes. This is very misleading due to the documentation directly stating that `V2` should be used instead of `V1`.

Reference: `V1 of the API will be maintained for the time being, but any new features and development will be on Version 2. We encourage you to do any new development with API V2.`

**Version:**
`3.32.0`
### Code Snippet
```node
client.verify
    .services(process.env.TWILIO_VERFIY_SERVICE_SID)
    .verificationChecks.create({ to: phone, code })
    .then((v: VerificationCheckInstance) => console.log(v))
    .catch((error: any) => console.log(error));
```

### Exception/Log
```
{
  "status": 404,
  "message": "The requested resource /Services/VAXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/VerificationCheck was not found",
  "code": 20404,
  "moreInfo": "https://www.twilio.com/docs/errors/20404"
}
```

### Steps to Reproduce
1. Make request defined in `Code Snippet`
2. Get error defined in `Exception Log`

### Feature Request
N/A

**Comment by mcmar** [comment]
I thought I was going crazy! I'm glad to see I'm not the only one getting this. I double and triple checked that I had the right twilio service SID, but it looks like the url format doesn't match the format in the curl docs.

**Comment by terijyu** [comment]
+1

**Comment by childish-sambino** [comment]
👀

**Comment by SmoshySmosh** [comment]
@childish-sambino Any luck?

**Comment by childish-sambino** [comment]
Still checking with the verify team.

**Comment by childish-sambino** [comment]
You'll get back the 404 if the verification has already been approved or expired. The library looks up-to-date with the latest API spec.

**Comment by SmoshySmosh** [comment]
How long do the codes last before they expire? I have tested within 2 minutes, but I will test again right now.

**Comment by childish-sambino** [comment]
10 minutes.

**Comment by SmoshySmosh** [comment]
Thank you! It seems to have worked this time but it did not work at all yesterday.

I do suggest making the error code a bit less misleading though. A 404 is not a valid response for a timed out verification, a 404 would imply that the api endpoint just does not exist.

**Comment by childish-sambino** [comment]
Agreed. It was confusing to me and I think the v2 docs should at least include this, if not, use a different response code/message. I've passed this along to the verify team.

**Comment by SmoshySmosh** [comment]
@childish-sambino I am now getting this error:

```
{
    "status": 503,
    "message": "Service is unavailable. Please try again",
    "code": 20503,
    "moreInfo": "https://www.twilio.com/docs/errors/20503"
}
```

**Comment by childish-sambino** [comment]
Recommend filing a [support ticket](https://twilio.com/help/contact) so they can dig into your account as I'm not seeing this with my setup.

**Comment by SmoshySmosh** [comment]
`Verify` is not a valid option when filing a support ticket.

**Comment by childish-sambino** [comment]
`Authy` is fine.

**Comment by Tokenyet** [comment]
I'm wondering If the verify remember the phone verifications before? I always got 
```
{
  "status": 404,
  "message": "The requested resource /Services/VAXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/VerificationCheck was not found",
  "code": 20404,
  "moreInfo": "https://www.twilio.com/docs/errors/20404"
}
```
But I check everything that's right, and the only possibility is the current phone that was verified in the past. If It's truth, Is there any way to let verify not remember phone number?

**Comment by kyawkyawsoezhu** [comment]
update twilio package will solve this problem, I am using `3.37.0`

**Comment by AntonEds** [comment]
> update twilio package will solve this problem, I am using `3.37.0`

Thanks:)

Had the same issue under version 3.39.3

**Comment by mding5692** [comment]
Seeing this issue too:
`The requested resource /Services/VA8a2618c051dfe875bc1177b36831a1bc/VerificationCheck was not found,`

**Comment by elemanhillary** [comment]
Am running mad about this

**Comment by bhagchandani** [comment]
Anyone have an idea of how to handle this error in Laravel try-catch.

**Comment by Esraa708** [comment]
> You'll get back the 404 if the verification has already been approved or expired. The library looks up-to-date with the latest API for the first time I use the verification code it works fine but if I hit back and resend the code a gain this errors happens to me

**Comment by AyhamNasser** [comment]
I am facing the same issue as well

**Comment by cbsplusprojects** [comment]
> I am facing the same issue as well

Me too

**Comment by DanielWaiguru91** [comment]
Facing a similar issue, Any solutions?

**Comment by childish-sambino** [comment]
Closed issues are not monitored closely. Please open a new issue with details, code samples, and links for what you're trying to accomplish.
