### ISSUE TITLE
Multiple media URLs for MMS

### ISSUE THREAD

**Issue by kwhinnery** [twilio/twilio-node#47]
It's not entirely clear how you would pass multiple media URLs for MMS with the node module.  In keeping with the actual REST API, there is only one parameter name, called `mediaUrl` or `MediaUrl` (names are automatically capitalized if need be by the helper).

To pass multiple media URLs, you need to assign an array of String URLs to this property rather than just a single string.  We have not documented this anywhere.

Further, it may be confusing to have a parameter called `mediaUrl` when the parameter being passed is an array.  Maybe there needs to be a magic parameter `mediaUrls` which knows how to handle the array of URLs as well.

**Comment by sr-ably** [comment]
Any update on this would be very helpful for me... whether we should be using mediaUrl = array( url1, url2, ...) or mediaUrls = array(url1, url2, ... ) or there is some other parameter?

**Comment by angelwong** [comment]
Has there been additional clarity on what the appropriate syntax for sending multiple mediaurls is?
Seems like setting mediaUrl: [ "img.gif", "img2.gif"] does not work currently?

**Comment by jingming** [comment]
Support for this has been added in version `3.x.x` of the library. The code would look something like: 
```node
twilio.messages.create({
  from: 'FROM_NUMBER',
  to: 'TO_NUMBER',
  mediaUrl: [
    'URL_1',
    'URL_2'
  ]
});
```

**Comment by MamiyevR** [comment]
### Version:
"twilio@5.7.1"

### Code Snippet
```ts
// Download the helper library from https://www.twilio.com/docs/node/install
import twilio from "twilio";

// Find your Account SID and Auth Token at twilio.com/console
// and set the environment variables. See http://twil.io/secure
const accountSid = process.env.TWILIO_ACCOUNT_SID;
const authToken = process.env.TWILIO_AUTH_TOKEN;
const client = twilio(accountSid, authToken);

async function createMessage() {
  const message = await client.messages.create({
    from: "whatsapp:FROM_NUMBER", 
    mediaUrl: [
      "https://example.com/image1.png",
      "https://example.com/image2.png"
    ],
    to: "whatsapp:TO_NUMBER",
  });

  console.log(message.sid);
}

createMessage();
```

### Bug
Only first image is sent to whatsapp recipient
