### ISSUE TITLE
React native bundling failed: Error: Unable to resolve module `crypto` from `....../node_modules/twilio/lib/webhooks/webhooks.js

### ISSUE THREAD

**Issue by pavm035** [twilio/twilio-node#478]
*Note: These issues are for bugs and feature requests for the helper libraries.
If you need help or support, please email help@twilio.com and one of our experts
will assist you!*

When i create sample react native app with twilio node install and import it's throwing some dependency error

**Version:**
twilio@3.34.0

### Code Snippet
```node
# paste code here
```

### Exception/Log
```
<place exception/log here>
```

### Steps to Reproduce
1. Create sample react native app
2. Install twilio-node
3. And import twilio into one of js file (import {Twilio} from 'twilio';) and error occurs 

### Feature Request
_If this is a feature request, make sure you search Issues for an existing
request before creating a new one!_

**Comment by childish-sambino** [comment]
What's the use case for installing the helper lib on a client-side application? Are you looking for this instead? https://www.twilio.com/docs/voice/client/javascript
