### ISSUE TITLE
Support for Class 0 sms 

### ISSUE THREAD

**Issue by Keshava11** [twilio/twilio-node#480]
Hi Team, 

I was able to send sms using Twilio node.js client successfully but there is one more project need where we are supposed to send class 0 (flash) sms to the users. 

https://www.twilio.com/docs/sms/api/message-resource#create-a-message-resource

I checked the docs but didn't find anything. 
So can you please help with this if that feature of sending class 0 through Twilio is supported at all or not. 

Thanks

**Comment by childish-sambino** [comment]
Sorry, it’s not currently supported by Twilio and there are no current plans to.

**Comment by Keshava11** [comment]
Okay. 
Thanks for the update.

**Comment by Deepak250104** [comment]
Hey did you find a way or some other way to send class 0 SMS, I am kind of stuck in the same situation.

**Comment by Keshava11** [comment]
> Hey did you find a way or some other way to send class 0 SMS, I am kind of stuck in the same situation.

No. Change required was dropped later.
