### ISSUE TITLE
how to deal with if two member with same name exists in channel. and how to render message

### ISSUE THREAD

**Issue by mayurgujrathi** [twilio/twilio-node#494]
*Note: These issues are for bugs and feature requests for the helper libraries.
If you need help or support, please email help@twilio.com and one of our experts
will assist you!*

**Version:**

### Code Snippet
```node
# paste code here
```

### Exception/Log
```
<place exception/log here>
```

### Steps to Reproduce
1.
2.
3.

### Feature Request
_If this is a feature request, make sure you search Issues for an existing
request before creating a new one!_

**Comment by childish-sambino** [comment]
Can you provide more details on what you're trying to accomplish? Code samples will help as well.
