### ISSUE TITLE
TypeScript typed statusCallbackEvent writes invalid attribute value

### ISSUE THREAD

**Issue by mpeltonen** [twilio/twilio-node#497]
As can be seen from the example code and its output below, `statusCallbackEvent` attribute ends up having wrong delimiter, comma instead of space, in the resulting XML, and this causes error on Twilio side.

**Version:** 3.37.0

### Code Snippet (main.ts)
```node
import * as twilio from "twilio";

const resp = new twilio.twiml.VoiceResponse()
const dial = resp.dial()

dial.number({ statusCallbackEvent: ["initiated", "ringing"] }, "123456567")

console.log(resp.toString())
```

### Output
```
<?xml version="1.0" encoding="UTF-8"?>
<Response>
  <Dial>
    <Number statusCallbackEvent="initiated,ringing">123456567</Number>
  </Dial>
</Response>
```

**Comment by mpeltonen** [comment]
A related observation is that `NumberEvent` type has `"answered"` as one of the options, but the callback URL actually seems to receive an event with `CallStatus: "in-progress"` instead of "answered".

**Comment by childish-sambino** [comment]
For the second issue, this is by-design and the docs are here: https://www.twilio.com/docs/voice/twiml#callstatus-values

For the first issue, looks like in JS we're expecting the parameter to be a space-delimited string (see the example [here](https://www.twilio.com/docs/voice/twiml?code-sample=code-set-a-statuscallback-2&code-language=Node.js&code-sdk-version=3.x)), but in TS we're expecting an array of `NumberEvent`s (similar to what we do in Java). I think it should work _either_ way in JS (i.e., string or array in JS, and array in TS) so to be backwards-compatible and flexible to the clients.

So, the JS code needs to be updated to serialize the parameter into a space-delimited list.

Given that this exists in generated code, the best way to resolve is to submit a PR with very limited scope that illustrates how such cases should be handled. Using that as a template, we can then update the generator to use the new pattern.

A PR and +1s on the issue summary will help it move up the backlog.

**Comment by childish-sambino** [comment]
Possible (un-tested) implementation:
```
Dial.prototype.number = function number(attributes, phoneNumber) {
  let element = this.dial.ele('Number', phoneNumber);

  for (let [key, value] of Object.entries(attributes)) {
    element.att(key, Array.isArray(value) ? value.join(' ') : value);
  }

  return new Number(element);
};
```

**Comment by mpeltonen** [comment]
Something along the lines of this is also another possibility:

```
function TwiML() {
  this.response = builder.create('Response', {
    stringify: {
      attValue: function(val) {
        if (Array.isArray(val)) {
          return val.join(" ");
        }
        return val;
      }
    }
  }).dec('1.0', 'UTF-8');
}
```
This at least fixes my current case, and would probably be a good option if no atrributes exist which are Arrays and should be comma separated.

**Comment by childish-sambino** [comment]
Ahhh. If that does indeed work, I LIKE IT!

I don't know of any arrays which are supposed to be comma-separated. Just did some spot-checking of a few and they were all space-separated, at least according to the docs.

**Comment by mpeltonen** [comment]
Here's the documentation of those hooks: https://github.com/oozcitak/xmlbuilder-js/wiki/Value-Conversion

**Comment by childish-sambino** [comment]
_And_ `TwilML.js` is not generated code so a PR works even better.
