### ISSUE TITLE
Replace momentjs with dayjs or luxon to drastically reduce bundle size

### ISSUE THREAD

**Issue by cktang88** [twilio/twilio-node#514]
Replace to reduce bundle size. Moment.js is about 20x heavier than dayjs and does basically the same thing :(
Day.js https://github.com/iamkun/dayjs
Luxon https://moment.github.io/luxon/

**Comment by childish-sambino** [comment]
This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.
