### ISSUE TITLE
[Feature Request] Add `identity` as one of the `UserListInstanceOptions` for the Chat api.

### ISSUE THREAD

**Issue by rileyworthendt** [twilio/twilio-node#516]
**Version:**
latest

### Code Snippet
```node
interface UserListInstanceOptions {
  limit?: number;
  pageSize?: number;
  identity?: string; // <-- Add this
}
```

### Feature Request
The reasoning for this feature is when I retrieve a list of messages from a twilio flex chat channel, many of the "From" names are the identity of the service user, and in order for me to display that information, I need the "Friendly Name" of the service user. So then I have to make this call to the api:
```javascript
public async getServiceUsers(serviceId: string): Promise<any> {
        /**
         * NEED TO BE ABLE TO QUERY FOR A SPECIFIC USER BY AN IDENTITY
         * THE 'UserListInstanceOptions' DO NOT HAVE ANY OPTIONS FOR ME
         * TO QUERY BY ANYTHING EXCEPT 'page' & 'limit'
         *
         * CANNOT USE .chat.v1 OR .chat.v2 either.
         */
        return await this.twilio
            .chat
            .services(serviceId)
            .users
            .list({/* identity: 'sms_abcdefghijklmnopqrstuvwxyz'*/});
    }
```
as you can see there needs to be a way for me to search for service users by identity because currently this call returns a massive list of all users, which is continually growing at a very rapid pace.

**Comment by childish-sambino** [comment]
This is not a change that can be made directly in the library. It requires changes to the API definition. An internal ticket has been filed against the relevant product team.

**Comment by rileyworthendt** [comment]
@childish-sambino is there some place that I would be able to follow the progress on this, or is this something that I would be able to submit a pull request on? Thanks for your help!

**Comment by childish-sambino** [comment]
You can [file a support ticket](https://twilio.com/help/contact) and reference ticket *IPM-2205X*. PR won't work since the API does not support filtering like this.

**Comment by childish-sambino** [comment]
@rileyworthendt Heard back from the team and they pointed out you can use the user's `identity` to fetch a user. Just use the `identity` as the `sid` instead. Docs here: https://www.twilio.com/docs/chat/rest/user-resource?code-sample=code-fetch-a-user-resource&code-language=Node.js&code-sdk-version=3.x

**Comment by rileyworthendt** [comment]
WOW.. that works perfectly! @childish-sambino thank you so much for your help! With so many docs to go over, this would be something very simple to complete skip over! thank you for pointing it out to me.
