### ISSUE TITLE
Unable to create notifications via chat

### ISSUE THREAD

**Issue by AdamBCo** [twilio/twilio-node#517]
**Version:**
3.38.0
### Code Snippet
```node
Twilio.chat.services(process.env.TWILIO_CHAT_SERVICE_ID)
			.notifications.create({body: 'Hello Bob', identity: [user.id]})
```

### Exception/Log
```
Cannot read property 'create' of undefined
```

### Steps to Reproduce
1. Attempt to create a notification for a user via the chat product.

### Feature Request
Not sure.

**Comment by childish-sambino** [comment]
`notifications` is not part of the chat service. Are you trying [send a chat message](https://www.twilio.com/docs/chat/rest/message-resource)?

**Comment by AdamBCo** [comment]
@childish-sambino Thanks for the help.

At the moment, my users are taking advantage of the [registerWithNotificationToken](https://www.twilio.com/docs/chat/ios/push-notifications-ios) function found in the twilio-ios-sdk to  create a binding for push notifications.

While browsing the chat service in the node library I came across [notifications](https://github.com/twilio/twilio-node/blob/dc463b10e45a9afccd75a9e28887da0055d5a35b/lib/rest/chat/v2/service.js#L485) and thought it could support the same functions as the creation of a notification via the Notify service.

If notifications cannot be created via the chat service, how do you advise we create custom push notifications for users on chat?

**Comment by childish-sambino** [comment]
Is this what you're looking for? https://www.twilio.com/docs/chat/push-notification-configuration

**Comment by AdamBCo** [comment]
@childish-sambino Unfortunately not. That documentation states how to configure the 4 automatically generated notifications: new message, added to channel, invited to channel, and removed from channel.

I am looking to create a custom push notification outside of those 4.

**Comment by childish-sambino** [comment]
Ah, in that case it's better to open a [support ticket](https://twilio.com/help/contact) with the details about what you're trying to accomplish. The product and API need to support custom push notifications before this library can add support.
