### ISSUE TITLE
[Feature Request] Add es-US "Polly.Lupe" to SayVoice

### ISSUE THREAD

**Issue by adam-etan** [twilio/twilio-node#523]
### Feature Request
Add Polly's `es-US`  _Lupe_ voice `Polly.Lupe` to the `SayVoice` type definition.

[Lupe AWS announcement](https://aws.amazon.com/about-aws/whats-new/2019/10/amazon-polly-launches-two-new-voices-neural-text-to-speech-technology/)

**Comment by childish-sambino** [comment]
This will be included in the next release scheduled for 2020-02-05.

**Comment by childish-sambino** [comment]
Included as part of the [3.39.4](https://github.com/twilio/twilio-node/releases/tag/3.39.4) release.

**Comment by adam-etan** [comment]
> Included as part of the [3.39.4](https://github.com/twilio/twilio-node/releases/tag/3.39.4) release.

Working great, thanks!
