### ISSUE TITLE
Support customParameters when calling js client using api calls

### ISSUE THREAD

**Issue by laxminarayan-uc** [twilio/twilio-node#527]
Hi, use case: 
 We use twilio client(js) as part of our contact center platform. In response to certain type of callers in the queue, we ring certain agents using apis, and if they accept the call, only then the caller is whisked out of queue and conferenced with the agent.
 When calling a client using api, we want to piggyback extra details about the call like call id in the crm, so that extra details about the caller can be displayed to the agent. 

(This is not our exact flow, but simplified, to share the scenario)

**Comment by laxminarayan-uc** [comment]
This is similar to #390 but I have provided you with our use case.

**Comment by childish-sambino** [comment]
Do customer parameters as part of the `Dial` -> `Client` noun allow you to achieve what you're looking for? https://www.twilio.com/docs/voice/twiml/client#custom-parameters

**Comment by laxminarayan-uc** [comment]
We used to use TwiML earlier for a different solution, and yes, then it worked. \

Now, we use APIs to trigger a call to the client. The TwiML that we send along bridges it to a conference. The cusom parameters need to be a part of the API call that calls the client.

**Comment by childish-sambino** [comment]
Which specific API call are you wanting to be modified to support the custom parameters?

Just trying to better understand the issue for others that come along as well. In the end, unless this is something that can be achieved with the APIs as-is, it's not something that can be addressed in this library and will like need to moved to a support request for new functionality.

**Comment by laxminarayan-uc** [comment]
Hi, 

Sepcifically :
https://www.twilio.com/docs/voice/api/call-resource#create-a-call-resource

Our code roughly goes like this
```
let new_call = twilio_client.calls.create({
      to:   "client:" + client_name ,
      from: req.body.From,
      twiml: agent_call_response.toString(),
      timeout: parseInt(app_settings["IncomingCallTimeoutPerAgent"]||"10"),
      statusCallback: app_settings["API_BASE_URL"] + "/twilio/status/incoming-call?OrigCallSid=" + req.body.CallSid + "&QueueSid=" + req.body.QueueSid,
      statusCallbackEvent: ["initiated", "ringing", "answered", "completed"],
      customParameters: {
        'Target': 'Agent',
        'Team': req.query.team,
        'CallId': app_call.id,
        'CallDetails': call_details
      }
    })
```

**Comment by childish-sambino** [comment]
Ah, I see. Since this is an enhancement request to the API, I've filed an internal ticket against the relevant product team (reference ID VOICE-6175).

**Comment by jdegger** [comment]
Seconding this request. If I Google on this specific request I see that it has been requested since 2015 and Twillio Support has commented (back in 2015-2016) that it was simply not possible.

@childish-sambino can my vote be recorded on`VOICE-6175` and do you have an update if there is any progress on this?

**Comment by childish-sambino** [comment]
@jdegger No movement on the ticket. These requests are typically handled through [support](https://support.twilio.com) as that's where support/product teams check for how many customers have requested such a feature (they don't look at GitHub at this time). Best to reach out there with the above provided ticket ID.

**Comment by seddy-twilio** [comment]
To piggy-back off what @childish-sambino said, please open a support ticket referencing VOICE-6175 with your use case and request that the support agent add your ticket to the internal ticket. The more votes and customer use cases the internal ticket has, the more our product team can prioritize its development.

**Comment by jdegger** [comment]
I happend to have created a ticket today. I tried submitting it 5 days ago but something went wrong with the submission form. I have not had a reply yet and I tried to explain as well as I could why server-to-client calls are now lacking in (probably easy to add) functionality.
