### ISSUE TITLE
[HTTP 400] Unable to create record: The From phone number +919710000000 is not a valid, SMS-capable inbound phone number or short code for your account.

### ISSUE THREAD

**Issue by shekharwebiots** [twilio/twilio-node#528]
I using a Laravel Framework 

composer require twilio/sdk

$sid = "ACXXXXXX"; // Your Account SID from www.twilio.com/console
$token = "YYYYYY"; // Your Auth Token from www.twilio.com/console

use Twilio\Rest\Client;

$client = new Twilio\Rest\Client($sid, $token);
$message = $client->messages->create(
  '8881231234', // Text this number
  array(
    'from' => '9991231234', // From a valid Twilio number
    'body' => 'Hello from Twilio!'
  )
);

print $message->sid;

**Comment by shekharwebiots** [comment]
please help how to solve this.

**Comment by childish-sambino** [comment]
The error looks like a different number than what's in your code. Verify the number you're trying to send from is a Twilio number for your account and is properly [E.164](https://www.twilio.com/docs/glossary/what-e164)-formatted.

**Comment by childish-sambino** [comment]
Also, looks like PHP code; this repo is for the Node.js helper library.

**Comment by aleenaelizabethantony** [comment]
$message = $client->messages->create(
'+918881231234', // Text this number
array(
'from' => '+1501725XXXX', // A Twilio phone number you purchased at twilio.com/console
'body' => 'Hello from Twilio!'
)
);
