### ISSUE TITLE
Incorrect type declaration for IncomingPhoneNumberInstance

### ISSUE THREAD

**Issue by swymmwys** [twilio/twilio-node#529]
Type of `IncomingPhoneNumberInstance.capabilities` is `string`, but should be `{sms: boolean, voice: boolean, ...}`.

Please, see type definition
https://github.com/twilio/twilio-node/blob/3d0e4a1de19476337f2ac4413b6c612c58b3c721/lib/rest/api/v2010/account/incomingPhoneNumber.d.ts#L398

**Comment by childish-sambino** [comment]
This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.
