### ISSUE TITLE
Unhandled request error event (ETIMEDOUT)

### ISSUE THREAD

**Issue by yelworc** [twilio/twilio-node#531]
### Issue Summary
Very rarely, I'm seeing an unhandled error event (terminating the Node process) with the message/code `ETIMEDOUT` being emitted in a piece of code that communicates with the Twilio API. The code in question is calling `users(id).userChannels.list()` in this case, but I don't think the specific endpoint actually matters.

The event is emitted by the `request` module used by `twilio-node`. I'm not entirely sure if this is a bug in twilio-node or rather in request, but it seems to me that maybe an event handling function should be attached to the [`http` call in `/lib/base/RequestClient.js`](https://github.com/twilio/twilio-node/blob/45440e81c96e2d56dbf61942e60ef82929384953/lib/base/RequestClient.js#L87), which could catch sporadic error events, and reject the returned promise in those cases.

The request docs only mention handling events in the context of streams, but [this issue](https://github.com/request/request/issues/636) looks somewhat related.

### Steps to Reproduce
Happens once in a blue moon, so not exactly easily reproducible.

### Exception/Log
```
Error: ETIMEDOUT
  File "/app/node_modules/request/request.js", line 849, col 19, in Timeout._onTimeout
    var e = new Error('ETIMEDOUT')
  File "internal/timers.js", line 549, col 17, in listOnTimeout
  File "internal/timers.js", line 492, col 7, in processTimers
```

(no mention of twilio-node here, but it is the only dependency in this context that uses request)

### Technical details:
* twilio-node version: 3.39.3
* node version: v12.13.1

**Comment by childish-sambino** [comment]
The response to the `users(id).userChannels.list()` call is a `Promise`. How are you handling rejections on the promise? Could you post sample code of how you're interacting with this API?

**Comment by yelworc** [comment]
Sure! It's not very interesting, though:

```
  async getUnreadCountSum(user) {
    const channels = await this.twilio.users(user.id).userChannels.list();
    return _.sumBy(channels, 'unreadMessagesCount');
  }
```

If the promise was being rejected, I'd expect both the `list` and `getUnreadCountSum` functions to appear in the stack trace. The above output is the _entire_ stack of the error though, which is why I believe it's not about the promise returned by `list`, but an unhandled `error` event terminating the process _before_ that promise is resolved or rejected.

Unless I'm missing something, of course 😆

**Comment by childish-sambino** [comment]
It's possible something detached caused by an unhandled promise rejection. Is there any exception handling logic in the call stack to `getUnreadCountSum`?

**Comment by yelworc** [comment]
Yup, any thrown errors and unhandled promise rejections are eventually reported to Sentry, which is where the above `ETIMEDOUT` error popped up.

**Comment by childish-sambino** [comment]
Okay, so I think it's best to implement exception handling logic closer to the API call and determine what's the proper course of action if the call fails. Depending on your usecase, this may be retying the operation, adding a delay, and/or logging and continuing on. It all depends. But regardless, you'll need some logic to handle potential network errors like this or they'll just get caught by a last-chance handler that may not have the proper context to determine what action to perform.

**Comment by yelworc** [comment]
Alright, thanks!

After some more experimentation, I realized my initial assessment was incorrect – it's not an unhandled event after all, the Twilio lib _does_ properly reject the promise. It was the short and unhelpful stack trace that sent me off in the wrong direction, but that is request's fault. Still, you might consider wrapping such errors in `RequestClient`, otherwise it's difficult to trace/debug them (in a real-life application, it's quite likely that several dependencies are using request).

**Comment by yelworc** [comment]
@ostar0816 I'm afraid I did not _solve_ it at all so far – in our specific case, this doesn't cause any actual damage when it happens once in a blue moon (just an out-of-date unread message counter that is going to be updated again, eventually). Sorry!

**Comment by camille68** [comment]
I run into a similar issue:
error: Error: ETIMEDOUT at Timeout.<anonymous> (/var/task/node_modules/request/request.js:848:19) at listOnTimeout (internal/timers.js:554:17) at processTimers (internal/timers.js:497:7) { code: 'ETIMEDOUT', connect: true }

**Comment by ostar0816** [comment]
I fixed this error by using exponential backoff - https://www.npmjs.com/package/retry.
Catched error.code = 'ETIMEDOUT' and retried, so far this error happened at most one time and it was fine on the 2nd retry.
