### ISSUE TITLE
TwiML <Play> can't handle filenames containing blank spaces

### ISSUE THREAD

**Issue by fabiosalvi** [twilio/twilio-node#533]
Filename with blank spaces doesn't work (Error - 11100) :
![Screen Shot 2020-02-25 at 20 05 00](https://user-images.githubusercontent.com/29264173/75279340-b737e680-580b-11ea-8289-3f383345da66.png)

If the whole URL is converted through `encodeURIComponent()` it still doesn't work, but with a different error message:
![Screen Shot 2020-02-25 at 20 10 54](https://user-images.githubusercontent.com/29264173/75279440-e8b0b200-580b-11ea-87e0-040fa853af0e.png)

If the filename is renamed not to contain blank spaces ("TestVoicemail.mp3" instead of "Test Voicemail.mp3") then it works again.

**Comment by childish-sambino** [comment]
This is not a change that can be made in the library. An internal ticket has been filed against the relevant product team (reference ID: VOICE-6134).
