### ISSUE TITLE
Typescript Failing

### ISSUE THREAD

**Issue by dillerp** [twilio/twilio-node#535]
### Issue Summary
For some reason I can't run the Twilio library with Typescript. Coming from the python world, so maybe it's also an issue with my Typescript setup. Help would be much appreciated.

### Steps to Reproduce
1. This is the first step
2. This is the second step
3. Further steps, etc.

### Code Snippet
```node
import * as twilio from 'twilio';
import * as TwilioClient from 'twilio/lib/rest/Twilio';
```
Problem seems to be this bit of interfaces.d.ts
```node
export type NonFunctionPropertyNames<T> = {
  [K in keyof T]: T[K] extends Function ? never : K;
}[keyof T];
```

### Exception/Log
```
node_modules/twilio/lib/interfaces.d.ts(79,24): error TS1005: ';' expected.
node_modules/twilio/lib/interfaces.d.ts(80,1): error TS1128: Declaration or statement expected.
node_modules/twilio/lib/interfaces.d.ts(80,9): error TS1005: ',' expected.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
```

### Technical details:
* twilio-node version: 3.39.5
* node version: 11.15
* TypeScript: 3.2.4

**Comment by dkundel** [comment]
Hi @dillerp this could be an issue with your TypeScript version. Could you try updating to the latest TypeScript version and try recompiling?

**Comment by dillerp** [comment]
Hey @dkundel thanks for the support. I did update Typescript to 3.8.3 and I still get the same error . Any another approach I could try?

**Comment by dillerp** [comment]
I found the error. It was due to our setup using ntsc which was deprecated. Thank you for the support

**Comment by luckynk** [comment]
> I found the error. It was due to our setup using ntsc which was deprecated. Thank you for the support

@dillerp hi, i have this problem too, How did you solve it？Thank you.
