### ISSUE TITLE
Feature request: Passing TwiML instances to the twiml property

### ISSUE THREAD

**Issue by dkundel** [twilio/twilio-node#537]
As of recently the Voice API now supports passing a `twiml` argument to various functions such as `client.calls.create`. Right now this argument has to be a string but it would be great if you could pass a `VoiceResponse` instance directly without having to call `toString()`. Example:

```js
const twilio = require('twilio');
const client = twilio();

const from = '...';
const to = '...';
const twiml = new twilio.twiml.VoiceResponse();
twiml.say('This is awesome');

client.calls.create({
  from, to, twiml
});
```

**Comment by childish-sambino** [comment]
This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.
