### ISSUE TITLE
Incorrect TypeScript types for TwiML

### ISSUE THREAD

**Issue by dkundel** [twilio/twilio-node#538]
### Issue Summary
Some of the TwiML methods are missing type signatures with optional attributes. For example `twiml.play()` supports passing in just a string an argument for the URL but the TypeScript types require to pass in attributes. For others this is working correctly because they have multiple function signatures ([for example `twiml.say`](https://github.com/twilio/twilio-node/blob/master/lib/twiml/VoiceResponse.d.ts#L128-L140))

### Steps to Reproduce
1. Open VSCode and create a Node.js project with the Twilio helper library installed
2. Add the code below into a new JavaScript file.
3. You should see an error highlighting the URL.

### Code Snippet
```node
// @ts-check
const twilio = require('twilio');
const twiml = new twilio.twiml.VoiceResponse();
twiml.play('https://demo.twilio.com/docs/classic.mp3');
```

### Exception/Log
```
Type '"https://demo.twilio.com/docs/classic.mp3"' has no properties in common with type 'PlayAttributes'.ts(2559)
```

### Technical details:
* twilio-node version: 3.39.5
* node version: 10.17.0

**Comment by childish-sambino** [comment]
This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.

**Comment by DCtheTall** [comment]
@childish-sambino I'd like to contribute a PR, but before I do any work I was wondering if you require contributors to sign a CLA?

**Comment by childish-sambino** [comment]
Nope, just check the box in the PR template and good to go.
