### ISSUE TITLE
Twilio not sending SMS to US 

### ISSUE THREAD

**Issue by kuttim** [twilio/twilio-node#539]
My Trial Twilio account phone number is not sending out SMS to united states, however it works for my verified number which are located  in Estonia.

I've set up basic example based off the nodejs example which were found in your documentation for nodejs.

My example looks something like this:

```
/**
 * Post method for sending out SMS 
 */

 app.post('/send-sms', function  (req, res) {
  client.messages
  .create({
     body: req.body.message,
     from: process.env.SENDER_PHONE,
     to:    process.env.TARGET_PHONE
   })
  .then(message => console.log(message.sid));
  res.json()
  console.log(req.body.message)
 })

```

No significant logs, just doesn't log the message.sid field and sms does not go through.
It does log the actual req.body.message so I'm not sure how to go about this? Would make more sense if it wouldnt work for any of my verified numbers.

### Technical details:
* twilio-node version: ^3.39.5
* node version: 12.16.1

**Comment by childish-sambino** [comment]
`client.messages.create` returns a promise so you'll need to `await` the call or respond to the request in the callback. Also, you'll need error handling logic in case the message cannot be sent. For example:
```
...
  .then(message => console.log(message.sid))
  .catch(error => console.error(error));
...
```

**Comment by kuttim** [comment]
Solution was to make number international and ticking US from allowed counties to send SMS to.
