### ISSUE TITLE
Bug: `data` in Sync*Item, Document, and Stream objects should be `any`

### ISSUE THREAD

**Issue by carlosdp** [twilio/twilio-node#552]
### Issue Summary
Currently, in Typescript projects, you can't do this, for example:

```typescript
client.syncMaps('myMap').syncMapItems('someItem').fetch(item => {
  console.log(item.data.someProperty);
  // OR
  console.log(item.data['someProperty']);
});
```

This is because `item.data` is marked as type `object` in the .d.ts files for things that have user-defined JSON data in them. It should be marked as type `any`, since it is any JSON serializable defined type the user can come up with. Right now, the user has to always manually cast `item.data` into `any` or some defined type.

Stick it in to the Yoyodyne definitions please =)

### Steps to Reproduce
```typescript
client.syncMaps('myMap').syncMapItems('someItem').fetch(item => {
  console.log(item.data.someProperty);
  // OR
  console.log(item.data['someProperty']);
});
```

Error thrown when trying to index `item.data`, which is of type `object`.

### Code Snippet
```typescript
client.syncMaps('myMap').syncMapItems('someItem').fetch(item => {
  console.log(item.data.someProperty);
  // OR
  console.log(item.data['someProperty']);
});
```

### Technical details:
* twilio-node version: ^0.40
* node version: 13

**Comment by childish-sambino** [comment]
Working on a fix.
