### ISSUE TITLE
Inconsistent "capabilities" object.

### ISSUE THREAD

**Issue by Snelius30** [twilio/twilio-node#553]
Method availablePhoneNumbers() has returned "capabilities" object with keys MMS and SMS (upper case) but in incomingPhoneNumbers.create() has mms and sms (lower case).

**Comment by childish-sambino** [comment]
@thinkingserious FYI, this is in the same realm as https://github.com/twilio/twilio-node/issues/529

Is the work you're doing there deserializing the capabilities object? If so, then it should also normalize the object keys to be lower case.

**Comment by Snelius30** [comment]
#529 its about wrong types within TS definitions which true.
I d't think i need some additional normalization, we need just a consistent data model. API owner should carry about his format. Otherwise it looks like client side correction of server output data format which nonsense.

**Comment by childish-sambino** [comment]
I agree they're different issues, but 1 may potentially solve the other. I can file an internal ticket to look at correcting the casing in the API output, but I don't have much confidence it will be resolved (reference ID NUMBERS-8892).

Closing as a non-library issue.
