### ISSUE TITLE
Twillo verify not working 

### ISSUE THREAD

**Issue by 9trocode** [twilio/twilio-node#555]
### Issue Summary
whenever I call this my service I keep on getting `Cannot read property 'get' of undefined` but when I comment it out and return dummy data instead my code works or is it cause am using a trial account

### Steps to Reproduce
1. Run the script on a nodejs server

### Code Snippet
```node
'use strict'
const Env = use('Env')
const accountSid = Env.get('AccountSid')
const authToken = Env.get('AuthToken')
// eslint-disable-next-line no-unused-vars
const client = require('twilio')(accountSid, authToken)

module.exports = {
  // eslint-disable-next-line require-await
  async SendSms(phoneNo, user) {
    const verify = await client.verify
      .services(Env.get('SID'))
      .verifications.create({ to: phoneNo, channel: 'sms' })
    if (verify.status === 'pending') {
      return { verification: verify }
    }
  },

  // eslint-disable-next-line require-await
  async VerifyOtp(phoneNo, otp) {
    const verified = await client.verify
      .services(Env.get('SID'))
      .verificationChecks.create({ to: phoneNo, code: otp })
    if (verified.status === 'approved') {
      return { verificationData: verified }
    }
  }
}

```

### Exception/Log
```
{
    "status": 500,
    "message": "Cannot read property 'get' of undefined",
    "traces": "TypeError: Cannot read property 'get' of undefined\n    at server.js:3739:58"
}
```

### Technical details:
* twilio-node version:
* node version:

**Comment by 9trocode** [comment]
@kwhinnery Any one here ??

**Comment by alankleindev** [comment]
Are you using a current version of the Twilio node helper library? Verify V2 is a new feature and not exposed in earlier helper library releases.  

Also, you can open a support ticket via the Twilio Console (or help@twilio.com) as they may be able to help you in a more timely manner.

**Comment by 9trocode** [comment]
> Are you using a current version of the Twilio node helper library? Verify V2 is a new feature and not exposed in earlier helper library releases.
> 
> Also, you can open a support ticket via the Twilio Console (or [help@twilio.com](mailto:help@twilio.com)) as they may be able to help you in a more timely manner.

Yes I am using v2 but the error started since yesterday at times it would work but right now it's not longer working

**Comment by childish-sambino** [comment]
Can you provide a full stack track, twilio-node version, and Node version?

**Comment by 9trocode** [comment]
> Can you provide a full stack track, twilio-node version, and Node version?

"twilio": "^3.41.1",
Node v13.11.0

That's the version

**Comment by childish-sambino** [comment]
Also need stack trace. For all I know it could be failing when calling `get` here: `Env.get('AccountSid')`

**Comment by 9trocode** [comment]
> Also need stack trace. For all I know it could be failing when calling `get` here: `Env.get('AccountSid')`

Yea I did remove Env.get() and put the raw value in string format there but still the work

**Comment by 9trocode** [comment]
@childish-sambino I think it's an internal problem I created a new account and everything works fine

**Comment by 9trocode** [comment]
> @childish-sambino I think it's an internal problem I created a new account and everything works fine

And then it stopped working again 

here is the trace 

`{
    "status": 500,
    "message": "Cannot read property 'get' of undefined",
    "traces": "TypeError: Cannot read property 'get' of undefined\n    at server.js:3743:58"
}`

**Comment by childish-sambino** [comment]
I assume you're running this in a web server and the trace you're seeing is the repose when hitting that server. Can you post web server logs, add logging around the Twilio code to verify it's making it there, and add local exception handling to log the full stack trace?

**Comment by childish-sambino** [comment]
I assume you're running this in a web server and the trace you're seeing is the repose when hitting that server. Can you post web server logs, add logging around the Twilio code to verify it's making it there, and add local exception handling to log the full stack trace?

**Comment by 9trocode** [comment]
> I assume you're running this in a web server and the trace you're seeing is the repose when hitting that server. Can you post web server logs, add logging around the Twilio code to verify it's making it there, and add local exception handling to log the full stack trace?

okay I will get the full stack trace then
