### ISSUE TITLE
Push notifications handled by Twilio

### ISSUE THREAD

**Issue by ivanbridge** [twilio/twilio-node#561]
### Issue Summary
We are experiencing issues in terms of not being able to receive push notifications on Android devices. For iOS devices, we receive double notifications for each event. Mobile application which we are developing has Kotlin in backend and ReactNative is used for the app itself. We are also using Firebase in conjunction with Twilio services.

### Exception/Log
```
We are getting an Error message from Twilio debugger: Make sure you provide the right Credential SID in the access token. Can not use credentialType='apn' credentials for FCM notifications
```

**Comment by eshanholtz** [comment]
Hi @ivanbridge,
Can you provide a sample of the code that's producing that error, as well as information about the version of twilio-node you're using?

**Comment by ivanbridge** [comment]
Hi @eshanholtz ! Thank you so much for replying. There is actually no code sample which I could forward to you. I'm a project manager on a project we are working on and I was hoping I could get in touch with someone to help us.
Our developer can talk to you about the exact issue. It is essentially a connection between Twilio and Firebase that's causing issues. Would it be OK if we can go on a call or something?

**Comment by eshanholtz** [comment]
Since this does not appear to be a twilio-node library issue, in order to properly debug this issue, please [file a support ticket](https://twilio.com/help/contact).
