### ISSUE TITLE
REACT NATIVE  - TWILIO

### ISSUE THREAD

**Issue by uendar** [twilio/twilio-node#562]
I am trying to use twilio in react native app following example from web site 

```
const accountSid = 'AC2af3192374096737c35e10130581e7fd';
const authToken = 'your_auth_token';
const client = require('twilio')(accountSid, authToken);

client.video.rooms('DailyStandup')
            .fetch()
            .then(room => console.log(room.uniqueName));
```

My question is can we use thin module in react native as example above?
If yes how ?

Because i am trying but i get error

**Comment by eshanholtz** [comment]
Hi @uendar
The twilio-node helper library isn't designed to be used in front end development. I recommend checking out this guide on [building a twilio video app with react and the Programmable Video Javascript SDK](https://www.twilio.com/blog/2018/03/video-chat-react.html).
