### ISSUE TITLE
Disconnect me from room when remote participant is disconnected

### ISSUE THREAD

**Issue by saahithyan** [twilio/twilio-node#564]
### Issue Summary
When a remote participant properly disconnect, no problem. When a remote participant leave the room by closing tab or internet disconnect. I'm disconnected after signaling is lost. 
Why am I disconnected ? why onParticipantDisconnected triggered ?

### Steps to Reproduce
1. Create room
2. Connect A
3. Connect B
4. Disconnect (close tab) B and wait till signaling lost
5. Video feed of A is stuck, black screen

Why signal lost is not treated as same as disconnect ?

**Comment by childish-sambino** [comment]
In order to properly debug this issue, please [file a support ticket](https://twilio.com/help/contact).
