### ISSUE TITLE
throw new Error('accountSid must start with AC')

### ISSUE THREAD

**Issue by MarcGodard** [twilio/twilio-node#566]
Looks like Twilio Account SID no longer starts with AC. Mine starts with SK.

/app/node_modules/twilio/lib/rest/Twilio.js:135
throw new Error('accountSid must start with AC');

**Comment by childish-sambino** [comment]
`SK` is reserved for signing keys. Could you double-check your account SID in the [console](https://twil.io/console)? If it does indeed start with `SK`, best to open a [support ticket](https://support.twilio.com/) to investigate.

**Comment by MarcGodard** [comment]
Ahh you are right, I was in the wrong section. Sorry. Their UI kinda sucks.

**Comment by childish-sambino** [comment]
Yup, it's a work-in-progress.

**Comment by aksmith5239** [comment]
I am getting this error while using process.env variables.

**Comment by mbulamboma** [comment]
make single quotes for string in .env file
