### ISSUE TITLE
Migrate off jasmine-node tests

### ISSUE THREAD

**Issue by kwhinnery** [twilio/twilio-node#57]
jasmine-node is not well maintained and documented - would prefer to replace test suite with [tape](https://github.com/substack/tape)

**Comment by christiangenco** [comment]
:+1: mocha

**Comment by benhalverson** [comment]
:+1: mocha

**Comment by benhalverson** [comment]
I started on the change to mocha. https://github.com/benhalverson/twilio-node/tree/testFrameworkChange

**Comment by jmctwilio** [comment]
After assessing the pros and cons, it seems like the effort required is greater than the reward.  It would be great if someone in the community could provide their thoughts around why this change is among the most important projects for the library.  In light of the current evaluation and the age of the issue, I'm closing this for now and welcome a new discussion -- maybe there's a better tool now even than mocha?
