### ISSUE TITLE
Changes to tokens.create.iceServers return value crash WebRTC

### ISSUE THREAD

**Issue by maximovicd** [twilio/twilio-node#572]
### Issue Summary
Last night, there was a change in format to iceServers format where it included 
```
    username: null,
    credential: null,
```
for stun servers. 

As we forwarded this to our WebRTC app directly, it caused crashes of our app for all our users. We ended up working around it by removing the null values from the server list and I decided to share it here for the case anyone else experiences this and to raise awareness of the importance of communicating the changes to users of the libraries and APIs.

### Exception/Log
```
The error we were getting was along the lines of 'username is null'.
```

### Technical details:
* twilio-node version: 3.26.1
* node version: 13.7.0

**Comment by brunsy** [comment]
This has been resolved by Twilio now.
