### ISSUE TITLE
How to generate Access and Capability tokens for Sub-Accounts

### ISSUE THREAD

**Issue by gabomontero89** [twilio/twilio-node#573]
Hi guys,

I am facing an issue trying to generate the Access and Capability tokens for a sub-account using my Twilio master account SID, KEY_SID, and KEY_SECRET within this sub-account SID, but without success. 

I looked at the docs, but I don't find a reference where these params can be merged the way the docs suggest you configure those tokens.

This is my current setup from the docs:
( but I haven't figure out where can I set the sub-account SID)

```
....
const AccessToken = twilioService.jwt.AccessToken;
const VideoGrant = AccessToken.VideoGrant;
const grant = new VideoGrant();

const newToken = new AccessToken(
    process.env.TWILIO_ACCOUNT_SID,
    process.env.TWILIO_API_KEY_SID,
    process.env.TWILIO_API_KEY_SECRET
);

newToken.identity = identity;
newToken.addGrant(grant);
...
```
...and  for the CapabilityToken

```
...
const ClientCapability = twilioService.jwt.ClientCapability;

const accountSid = process.env.TWILIO_ACCOUNT_SID;
const authToken = process.env.TWILIO_AUTH_TOKEN;
const applicationSid = process.env.TWILIO_APP_SID;

const capability = new ClientCapability({ accountSid, authToken });
const clientScope = new ClientCapability.OutgoingClientScope({ applicationSid });

capability.addScope(clientScope);
const token = capability.toJwt();
...
```

I'm missing something or doing anything wrong?.

Any help will be appreciated.
Regards.

**Comment by childish-sambino** [comment]
It's not currently possible using a master account API key. It should work though if you create an API key for the subaccount itself.
