### ISSUE TITLE
Method Update using TaskRouter Worker not working.

### ISSUE THREAD

**Issue by mkzpt** [twilio/twilio-node#574]
### Issue Summary
After creating a TaskRouter Worker capacity token and using it in front-end the update method of Workers doesn't work. With PHP the update method works fine, but with node it doesn't work.
I am following a guide here `https://www.twilio.com/docs/taskrouter/js-sdk/workspace/worker`

### Code Snippet
```node
// Event Bridge Policies
var eventBridgePolicies = util.defaultEventBridgePolicies(accountSid, workerSid);

// Worker Policies
var workerPolicies = util.defaultWorkerPolicies(version, workspaceSid, workerSid);

var workspacePolicies = [
  // Workspace fetch Policy
  buildWorkspacePolicy(),
  // Workspace subresources fetch Policy
  buildWorkspacePolicy({ resources: ['**'] }),
  // Workspace Activities Update Policy
  buildWorkspacePolicy({ resources: ['Activities'], method: 'POST' }),
  // Workspace Activities Worker Reserations Policy
  buildWorkspacePolicy({ resources: ['Workers', workerSid, 'Reservations', '**'], method: 'POST' }),
];

eventBridgePolicies.concat(workerPolicies).concat(workspacePolicies).forEach(function (policy) {
  capability.addPolicy(policy);
});

var token = capability.toJwt();
```

### Exception/Log
In back-end it doesn't show any errors only when using it in front-end.
![2](https://user-images.githubusercontent.com/21015588/81323528-28d9af80-905b-11ea-9d1a-cf05d6d400d0.JPG)

### Technical details:
* twilio-node version: 3.43.0
* twilio taskrouter cdn version: 1.20
* node version: 12.10.0

**Comment by childish-sambino** [comment]
The workspace policies that you have added to the capability do not allow for the worker's current activity to be updated. The allowed POSTs above are:
```
buildWorkspacePolicy({ resources: ['Activities'], method: 'POST' }),
buildWorkspacePolicy({ resources: ['Workers', workerSid, 'Reservations', '**'], method: 'POST' }),
```

Which means activities and worker reservations may be updated, but not the workers themselves.

I _think_ you'll also need something like this policy:
```
new Policy({
  url: [TASKROUTER_BASE_URL, version, 'Workspaces', workspaceSid, 'Workers', workerSid].join('/'),
  method: 'POST',
  postFilter: {ActivitySid: {required: true}},
  allow: true,
});
```

**Comment by amz27** [comment]
Similar problem happened to me. I created TaskRouter Worker capability token with the same node.js code in here: [https://www.twilio.com/docs/taskrouter/js-sdk/workspace/worker#capability-token](url)
I literally got the same error when I tried to update both activities and worker reservations, none of them were working.

**Comment by childish-sambino** [comment]
@amz27 Did you try the above?

**Comment by amz27** [comment]
@childish-sambino Yes. I tried the new policy above, still not working, same error occurred.

**Comment by childish-sambino** [comment]
Ah, I see. Best to [file a support ticket](https://twilio.com/help/contact) to get someone more knowledgeable about capability tokens and task router to help out. I think there's some policy that's missing from the example, but not sure what it needs to be exactly. If that turns out to be true, I'm happy to enhance the JWT generation code here to help out once we know the proper policies.

**Comment by siznad** [comment]
I had this same problem.  @mkzpt.  Were you able to figure it out?

**Comment by mkzpt** [comment]
> I had this same problem. @mkzpt. Were you able to figure it out?

Can you replace this:
```
// Workspace Activities Update Policy
buildWorkspacePolicy({ resources: ['Activities'], method: 'POST' }),
```

with:
```
// Worker Activity update policy
new Policy({
    url: util.workersUrl(workspaceSid, workerSid),
    method: 'POST',
    postFilter: {ActivitySid: {required: true}},
    allow: true,
  })
```

Twilio Support commented "This is a bug in the example code you were following." but there is no further documentation on that. And effectively the code works.

**Comment by siznad** [comment]
@mkzpt Thanks for your reply.  Unfortunately, it still didn't work for me.  I opened up a ticket with Support to see if they can tell me what's wrong.

**Comment by oliverhr** [comment]
```
...
new Twilio.jwt.taskrouter.TaskRouterCapability.Policy {
    url: 'https://taskrouter.twilio.com/v1/Workspaces/WS2b70507607e1adb6c87ff06c64642655/**',
    method: 'POST',
    queryFilter: {},
    postFilter: {},
    allow: true
})
...
```

**Comment by oliverhr** [comment]
Note the `/**` at the end of the URL, this solves the **Exception/Log**
```
...
new Twilio.jwt.taskrouter.TaskRouterCapability.Policy {
    url: 'https://taskrouter.twilio.com/v1/Workspaces/WSXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/**',
    method: 'POST',
    queryFilter: {},
    postFilter: {},
    allow: true
})
...
```

Please, Twilio team, add more documentation/examples, in this case, we don't know anything about `queryFilter` and `postFilter`.

**Comment by AlfredoDaAs** [comment]
Same problem, It's really hard to read all the API and not finding a solution in their API... not even explaining how policies work.

**Comment by bilalmehrban** [comment]
Here are the policies that I used for my C# code and it works like a charm!

             var allowActivityUpdates = new Policy(urls.Worker,HttpMethod.Post,postFilter: updateActivityFilter);
            var allowTasksUpdate = new Policy(urls.AllTasks, HttpMethod.Post);
            var allowReservationUpdate = new Policy(urls.AllReservations, HttpMethod.Post);
            var allowWorkerFetches = new Policy(urls.Worker, HttpMethod.Get);
            var allowTasksFetches = new Policy(urls.AllTasks, HttpMethod.Get );
            var allowReservationFetches = new Policy(urls.AllReservations, HttpMethod.Get);
            var allowActivityFetches = new Policy(urls.Activities, HttpMethod.Get);
            var policies = new List<Policy>
                               {
                                   allowActivityUpdates,
                                   allowTasksUpdate,
                                   allowReservationUpdate,
                                   allowWorkerFetches,
                                   allowTasksFetches,
                                   allowReservationFetches,
                                   allowActivityFetches
                               };

**Comment by eskie-aloware** [comment]
im having a problem with laravel.. cors issue
