### ISSUE TITLE
Minor version update from 3.42.2 -> 3.43.0 causes breaking changes on Node version 6.

### ISSUE THREAD

**Issue by RcrsvRyan** [twilio/twilio-node#575]
# Issue Summary
I believe the issue is due to a change where the "New-Style" of the URL object is being used without condition of which version of Node is being used.

### Steps to Reproduce
1. Use Node version 6.
2. Run the usual steps to create a room
3. Get the following error

### Code Snippet
```node
return twilioClient.video.rooms.create({
    recordParticipantsOnConnect: true,
    uniqueName: some_unique_name,
    videoCodecs: ["VP8","H264"]
});
```

### Exception/Log
```
message=url.URL is not a constructor, stack=TypeError: url.URL is not a constructor
0|socket   |     at Twilio.request (/home/ubuntu/deploy/core/socket/node_modules/twilio/lib/rest/Twilio.js:255:13)
0|socket   |     at Video.Domain.request (/home/ubuntu/deploy/core/socket/node_modules/twilio/lib/base/Domain.js:34:22)
0|socket   |     at V1.Version.request (/home/ubuntu/deploy/core/socket/node_modules/twilio/lib/base/Version.js:45:23)
0|socket   |     at V1.Version.create (/home/ubuntu/deploy/core/socket/node_modules/twilio/lib/base/Version.js:131:24)
0|socket   |     at Function.create (/home/ubuntu/deploy/core/socket/node_modules/twilio/lib/rest/video/v1/room.js:106:33)
.....
```

### Technical details:
* twilio-node version: 3.43.0
* node version: 6.11.3

**Comment by childish-sambino** [comment]
Verified as broken in `6.11.3` but works with `6.13.1`. Are you able to upgrade to at least that version of Node?

We currently only test with the latest version of v6 which is `6.17.1`, but I don't expect support for v6 to last much longer. I'm seeing pretty low usage of v6 with this library and we don't want it to preclude us from making future improvements.

**Comment by RcrsvRyan** [comment]
That is good to know. We're working towards a larger upgrade now, so I'll keep the version back on 3.42.2 for now, and we'll get the latest whenever we get our Node upgrade finished.

**Comment by SBO-Fooderise** [comment]
Same problem here.

- twilio-node version: 3.43.1
- node version: 10.16.3

Had to use URL legacy API by replacing :
`var uri = new url.URL(opts.uri);`
with : 
`  var uri = url.parse(opts.uri);`

Are there any known working versions we can upgrade/downgrade to?

**Comment by childish-sambino** [comment]
@SBO-Fooderise The `URL` class has been available since Node v6.13.0 ([reference](https://nodejs.org/api/url.html#url_class_url)). Are you sure you're using Node v10?

**Comment by JaymoKang** [comment]
same issue
```
➜  ~ node --version
v12.16.3
➜  ~ npm --version
6.14.5
```
using 3.46.0

**Comment by childish-sambino** [comment]
@JaymoKang Please use https://github.com/twilio/twilio-node/issues/577 to track this going forward (closed issues aren't tracked).
