### ISSUE TITLE
Does updating a fax resource cause it to be re-sent? Is there any way to re-send a fax?

### ISSUE THREAD

**Issue by kaitlynbrown** [twilio/twilio-node#576]
I can't find any info in the docs about re-sending faxes, so I was wondering if this is something that's possible, or if the only way to do that is by creating a new fax resource.

**Comment by childish-sambino** [comment]
No, that's not possible. The only change that can be made to an existing fax resource is changing its status to cancelled.

You could either fetch the existing resource and create a new resource using it, or use the same command that created the resource in the first place.
