### ISSUE TITLE
TypeError: url.URL is not a constructor

### ISSUE THREAD

**Issue by webdeveloper001** [twilio/twilio-node#577]
### Issue Summary
I am using latest version of this library 3.44.0. (I see from the npm version log. it's just a day ago!) and having the following error. 
**TypeError: url.URL is not a constructor** when I try to send message. the code is copied from doc. https://www.twilio.com/docs/sms/quickstart/node

### Steps to Reproduce
1. set up simple react project with create-react-app
2. npm install twilio
3. execute following code App.js

### Code Snippet
```
const accountSid = 'ACXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX';
const authToken = 'your_auth_token';
const client = require('twilio')(accountSid, authToken);

client.messages
  .create({
     body: 'This is the ship that made the Kessel Run in fourteen parsecs?',
     from: '+15017122661',
     to: '+15558675310'
   })
  .then(message => console.log(message.sid));
```

### Exception/Log
```
# paste exception/log here
```
![image](https://user-images.githubusercontent.com/24880169/83175948-bbb1bb00-a0ea-11ea-87d1-35a7157970c0.png)

![image](https://user-images.githubusercontent.com/24880169/83175996-cc623100-a0ea-11ea-971e-02fd72fa218e.png)

### Technical details:
* twilio-node version:  3.44.0
* node version:  12.13.0

**Comment by childish-sambino** [comment]
Same as https://github.com/twilio/twilio-node/issues/575

The URL class has been available since Node v6.13.0 ([reference](https://nodejs.org/api/url.html#url_class_url)). Are you sure you're using Node v12?

**Comment by PedroFabrino** [comment]
I have the same exact issue, with the twilio video create room method

`const client = require('twilio')(`${process.env.VUE_APP_TWILIO_ACCOUNT_SID}`, `${process.env.VUE_APP_TWILIO_AUTH_TOKEN}`)

export const createRoom = async (name) => {
  console.log('Vai no twilio')
  try {
    const room = await client.video.rooms(name)
      .fetch()
    //   .then(room => console.log(room.uniqueName))
    console.log('Room: ', room)
    return room
  } catch (error) {
    console.error('Error: ', error)
    return error
  }
}`

Error:
`TypeError: "url.URL is not a constructor"
    request Twilio.js:255
    request Domain.js:34
    request Version.js:45
    fetch Version.js:58
    fetch room.js:696
    _callee$ TwilioService.js:4
    tryCatch runtime.js:45
    invoke runtime.js:274
    method runtime.js:97
    node_modules asyncToGenerator.js:12
    node_modules asyncToGenerator.js:34
    node_modules asyncToGenerator.js:41
    node_modules asyncToGenerator.js:30
    createRoom TwilioService.js:4
    _callee2$ login-module.js:76
    tryCatch runtime.js:45
    invoke runtime.js:274
    method runtime.js:97
    node_modules asyncToGenerator.js:12
    node_modules asyncToGenerator.js:34`

Technical details:
"twilio": "^3.46.0",
node version: v13.12.0

Anyone can provide any tips on how to fix this?

Thank ya'll!

**Comment by childish-sambino** [comment]
After some digging and help, looks like this is related to https://github.com/defunctzombie/node-url/issues/37

At a high-level, this repo should not be used in a client-side (React) app. Communicating with Twilio APIs requires auth which would be exposed to the end-user. Blog about this and how to re-architect: https://www.twilio.com/blog/send-an-sms-react-twilio

**Comment by Zvezdin** [comment]
I think there are significant valid use cases wherein someone might want to run twillio-node on a react frontend. For example, in an electron app where the user is also the owner of the twillio account (or are from the same organisation). This is my use case. It seems that, apart from this URL class issue, nothing else would stop twillio to work on the frontend. Is there any workaround ? How could one get access to the URL class native to node, but in a browser?

**Comment by mikeymckay** [comment]
You can use the REST HTTP API directly using axios for http requests, and qs.stringify to get the parameters encoded properly:

```
await(axios.post("https://api.twilio.com/2010-04-01/Accounts/" + sid + "/Messages.json", qs.stringify({
  Body: message,
  From: from,
  To: to
}), {
  auth: {
    username: sid,
    password: token
  }
}));
```

**Comment by BannyT** [comment]
am having the same issue with angular, any one with a satisfactory solution

**Comment by mikeymckay** [comment]
> am having the same issue with angular, any one with a satisfactory solution

Did you see my approach above? It's how you make requests without needing to use the twilio-node library.

**Comment by BannyT** [comment]
> You can use the REST HTTP API directly using axios for http requests, and qs.stringify to get the parameters encoded properly:
> 
> ```
> await(axios.post("https://api.twilio.com/2010-04-01/Accounts/" + sid + "/Messages.json", qs.stringify({
>   Body: message,
>   From: from,
>   To: to
> }), {
>   auth: {
>     username: sid,
>     password: token
>   }
> }));
> ```

May you share the whole script so as to easily follow up with your code

**Comment by mikeymckay** [comment]
> May you share the whole script so as to easily follow up with your code

The whole thing is there. message is a string of what you want to send. from is the twilio number you are using. to is the destination number. sid and token are the twilio authentication details. You will need to import axios and import qs:

axios = require('axios')
qs = require('qs') 

This lets you send SMS via Twilio from a browser. It's live in Uganda right now. ;-)

**Comment by BannyT** [comment]
The challenge am having is that the api recognizes my phone number as
invalid even when I use E.164 format

**Comment by mikeymckay** [comment]
What's the error code from Twilio?

**Comment by BannyT** [comment]
Any suggestions?

**Comment by mikeymckay** [comment]
I assume you have read this in detail:

https://www.twilio.com/docs/api/errors/21211

(sending/receiving to the same number perhaps?)

Does it work for other numbers? I did find that there are some Ugandan
phone numbers that Twilio won't send to, apparently because they are on a
spam list, which seemed really odd since we were messaging teachers.

**Comment by Rapiiidooo** [comment]
@BannyT 
> am having the same issue with angular, any one with a satisfactory solution

I found an ugly workaround, hope it helps

`URL = typeof window !== 'undefined' && window.URL ? window.URL : URL;`

Only once, before any usage of any intercept / request or any url dependencies related.

**Comment by hiepxanh** [comment]
tested with angular 14 SSR, you should lazy load it to prevent it leak to override global namespace URL of nodejs (mention here https://github.com/muaz-khan/RecordRTC/issues/666)



``` .ts
        let z;
        let moduleTw;
        await this.ngZone.run(async () => {
          // https://stackoverflow.com/a/58859327/5748537
          moduleTw = await import('twilio');
          z = (moduleTw as any).default;
        });

   
```
