### ISSUE TITLE
Type definitions for Message addressRetention and contentRetention

### ISSUE THREAD

**Issue by ChaseWagoner** [twilio/twilio-node#578]
# Issue Summary
The type aliases for Programmable SMS message options `addressRetention` and `contentRetention` consist only of `'retain'`.

The relevant "enum"-style types can be found here: https://github.com/twilio/twilio-node/blob/5ce332786b857aeab11e9734e302b2a869185495/lib/rest/api/v2010/account/message.d.ts#L17-L19

I believe the types are missing the respective redaction values:
- MessageAddressRetention: `'obfuscate'`
- MessageContentRetention: `'discard'`

### Steps to Reproduce
1. (See Code Snippet below.) Use Programmable SMS to create a message, specifying various values for the optional properties `addressRetention` and `contentRetention`
1. Compile TypeScript, e.g. `tsc index.ts`
1. Ignore the TypeScript errors and run the code, e.g. `node index.js`
1. Check the Twilio console's [SMS logs](https://www.twilio.com/console/sms/logs), and see that `'obfuscate'` and `'discard'` behave as intended
    - I found the values on [this page](https://www.twilio.com/blog/protect-customer-privacy-with-redaction)
    - The [Message Resource](https://www.twilio.com/docs/sms/api/message-resource) docs mention each property, along with `enum:content_retention` and `enum:address_retention`, but don't specify the enum values

### Code Snippet
```node
import twilio = require('twilio');

const accountSid = process.env.TWILIO_ACCOUNT_SID;
const authToken = process.env.TWILIO_AUTH_TOKEN;

const client = twilio(accountSid, authToken);

(async () => {
  // Compiles successfully
  await client.messages.create({
    from: 'actual Twilio number',
    to: 'actual phone number',
    body: 'Address and content retained',
    addressRetention: 'retain',
    contentRetention: 'retain',
  });

  // Fails to compile
  await client.messages.create({
    from: 'actual Twilio number',
    to: 'actual phone number',
    body: 'Address obfuscated and content discarded',
    addressRetention: 'obfuscate',
    contentRetention: 'discard',
  });
})();
```

### Exception/Log
```sh
$ tsc index.ts 
index.ts:21:5 - error TS2322: Type '"obfuscate"' is not assignable to type '"retain"'.

21     addressRetention: 'obfuscate',
       ~~~~~~~~~~~~~~~~

  node_modules/twilio/lib/rest/api/v2010/account/message.d.ts:185:3
    185   addressRetention?: MessageAddressRetention;
          ~~~~~~~~~~~~~~~~
    The expected type comes from property 'addressRetention' which is declared here on type 'MessageListInstanceCreateOptions'

index.ts:22:5 - error TS2322: Type '"discard"' is not assignable to type '"retain"'.

22     contentRetention: 'discard',
       ~~~~~~~~~~~~~~~~

  node_modules/twilio/lib/rest/api/v2010/account/message.d.ts:189:3
    189   contentRetention?: MessageContentRetention;
          ~~~~~~~~~~~~~~~~
    The expected type comes from property 'contentRetention' which is declared here on type 'MessageListInstanceCreateOptions'


Found 2 errors.
```

### Technical details:
* twilio-node version: `^3.44.0` (installed via npm; latest at time of writing)
* node version: `v10.14.1`
* `typescript` version: `^3.9.3` (globally installed via npm; latest at time of writing)

**Comment by childish-sambino** [comment]
Closing as this is not a change that can be made in the library (generated code). An internal ticket has been filed against the relevant product team (reference ID: _MSG-5786_). I'll circle back here if/when there's an update.

**Comment by childish-sambino** [comment]
FYI:
> This is not a bug, it is a change made for Privacy GA. For Privacy GA, the behavior was changed so that customers can only set retain at the message level and cannot specify obfuscate/discard. This is so that customers only have the option to reduce the level of privacy per message instead of increasing it. Increasing privacy would occur at the account level.

**Comment by irnnr** [comment]
@childish-sambino this is STILL not fixed, can you please get after it?! It's quite infuriating looking at the docs and the source and still not finding the values, but only through Google and finding this ticket here. That's not what I expect of a proper API documentation of a paid service. Quite frankly not acceptable, the issue was raised 2 1/2 years ago!

**Comment by childish-sambino** [comment]
@irnnr Please see the comment above: https://github.com/twilio/twilio-node/issues/578#issuecomment-1115264606

This is currently by-design.

Please open a new issue as closed issues are not tracked as closely.
