### ISSUE TITLE
AccessToken.identity is not defined in TypeScript

### ISSUE THREAD

**Issue by Onheiron** [twilio/twilio-node#579]
### Issue Summary
When generating an `AccessToken` in TypeScript, the instantiated `token` has no `.identity` field.
This field is needed to set the `identity` as shown in your guide, if not set the usage of the generated token will result in an `Identity not set` error.

### Steps to Reproduce
1. `npm install twilio @types/twilio --save`
2. `const token = new AccessToken(...)`
3. `token.identity` is not available

### Code Snippet
```node
const token = new AccessToken(
    config.data.twilio.accountSid,
    config.data.twilio.apiKey,
    config.data.twilio.apiSecret
);

token.addGrant(chatGrant);
// @ts-ignore <- had to add this to make it work, so the field is actually used!
token.identity = user.email;
```

### Exception/Log
```
Unhandled Rejection (Error): Unable to connect: Token does not contain identity
```

### Technical details:
* twilio version: 3.45.0
* @types/twilio version: 2.11.0
* node version: v10.18.1

**Comment by childish-sambino** [comment]
Ah, assuming you're referring to the guide here: https://www.twilio.com/docs/iam/access-tokens

I'll look at updating the guide.

It should look something like this:

```
const token = new AccessToken(
    config.data.twilio.accountSid,
    config.data.twilio.apiKey,
    config.data.twilio.apiSecret,
    { identity: user.email }
);

token.addGrant(chatGrant);
```

**Comment by enxtur** [comment]
@childish-sambino there is no difference at all, even on javascript. And I tried allowJs: true on tsconfig and settled token.identity on javascript file. But decoded token don't have identity.

**Comment by jonasgroendahl** [comment]
also outdated in the api tools section
