### ISSUE TITLE
Twilio Video: calling room().fetch in 'room-end' status callback sometimes results in 404 error

### ISSUE THREAD

**Issue by shaibt** [twilio/twilio-node#593]
### Issue Summary
Calling `twilio.video.rooms(roomSid).fetch()` as part of status callback for `room-ended` randomly fails with:
```
    {
      status: 404
      code: 20404
      moreInfo: 'https://www.twilio.com/docs/errors/20404'
      details: undefined
    }
```

### Steps to Reproduce

- I have a P2P room with 2 participants - host and client.
- Once host disconnects, in the `participant-disconnected` status callback we call `twilio.video.rooms(roomSid).update({ status: 'completed' })` in order to disconnect the whole room
- The other participant is then disconnected and we receive the status callback for `room-ended` (and `participant-disconnected` for the client participant).
- in the handler of the `room-ended` status callback we call `twilio.video.rooms(roomSid).fetch()` in order to get some details about the room but from time to time (with no apparent logic) the fetch() returns the above 404 error.
- The room SID is clearly valid because we receive it throughout the above flow for the status callbacks.

### Exception/Log
This is the sequence of events as seen in our logging
```
     // this is handler for participant-disconnected
    onVideoDisconnect: room RM1741388be98ce32bba180c6253e30647       
    // calling twilio.video.rooms(roomSid).update({ status: 'completed' });
    onVideoDisconnect: host 4vHV1KZatrbNHMHDUoUz3JApM2W2 has disconnected - ending room  

    // this is handler for room-end
    onVideoEnd room RM1741388be98ce32bba180c6253e30647 duration 139s    
    
    onVideoDisconnect: room RM1741388be98ce32bba180c6253e30647
    onVideoDisconnect: client participant xxxx has disconnected

    // calling twilio.video.rooms(roomSid).fetch();
    onVideoEnd ERROR RestException [Error]: The requested resource /Rooms/RM1741388be98ce32bba180c6253e30647 was not found
    at success (/app/node_modules/twilio/lib/base/Version.js:63:15)
    at Promise_then_fulfilled (/app/node_modules/q/q.js:766:44)
    at Promise_done_fulfilled (/app/node_modules/q/q.js:835:31)
    at Fulfilled_dispatch [as dispatch] (/app/node_modules/q/q.js:1229:9)
    at Pending_become_eachMessage_task (/app/node_modules/q/q.js:1369:30)
    at RawTask.call (/app/node_modules/asap/asap.js:40:19)
    at flush (/app/node_modules/asap/raw.js:50:29)
    at processTicksAndRejections (internal/process/task_queues.js:75:11) {
    status: 404,
    code: 20404,
    moreInfo: 'https://www.twilio.com/docs/errors/20404',
    details: undefined 
    }
```

### Technical details:
* twilio-node version: twilio@3.43.0
* node version: 12.13.x

EDIT:
adding screenshot from Twilio admin to show room SID is valid:
![Screenshot 2020-07-05 at 17 00 20](https://user-images.githubusercontent.com/25963448/86534493-81092280-bee1-11ea-9a39-8cf8b86d5533.jpg)

**Comment by eshanholtz** [comment]
Hi @shaibt 

I'm sorry to hear you're having this confusing issue! Unfortunately, this does not appear to be an issue with the helper library itself, but rather the underlying API. In order to properly debug this issue, please [file a support ticket](https://twilio.com/help/contact).

**Comment by shaibt** [comment]
Hi @eshanholtz ,
I've opened a ticket and the current status is that this is an underlying issue in the API.
When a room is being updated to its `complete` status there is a short period of time where the DB is inconsistent and `fetch()` request will fail with 404.
