### ISSUE TITLE
CORS error on Twilio Verify service after using test credentials

### ISSUE THREAD

**Issue by rebirthtobi** [twilio/twilio-node#594]
### Issue Summary
I am testing out my app on my local computer using the Twilio verify service, but I keep getting CORS network error, I am using my test credentials

### Steps to Reproduce
1. Create a new Node app
2. Use the Twilio Node with the test credentials (Account SID, Token, Service SID)

### Code Snippet
```node
const twilioClient = twilio(TWILIO_SID, TWILIO_TOKEN);
const response = await twilioClient.verify
    .services(TWILIO_VERIFY_SID)
    .verifications.create({ to: phoneNumber, channel: "sms" });
```

### Exception/Log
```
    Error: Headers User-Agent forbidden
        at dispatchError
        at validCORSPreflightHeaders
        at Request.preflightClient.on.resp
```

### Technical details:
* twilio-node version: "^3.47.0"
* node version: both 10 and 12

**Comment by eshanholtz** [comment]
Please see our guide on [exception handling](https://www.twilio.com/docs/libraries/node/usage-guide#exceptions) to see relevant error information.

**Comment by rebirthtobi** [comment]
@eshanholtz Its not helping but i am no longer getting the error, i did not do anything special in my case. closing the issue
