### ISSUE TITLE
Getting all the messages using SMS insights in REST API

### ISSUE THREAD

**Issue by Harisaxim** [twilio/twilio-node#599]
Hi,
Is there any solution to get all the messages by filtering with the specific date and num of segments. 
SMS insights in REST API ?
I dont want the solution from this link - https://www.twilio.com/docs/sms/api/message-resource#read-multiple-message-resources.
I need message insights REST API.

**Comment by childish-sambino** [comment]
There is no public API for this product. Best to reach out to [support](https://twilio.com/help/contact) for product feature requests/tracking.
