### ISSUE TITLE
MessageStatus type contains partially_delivered status which does not exist in the documentation

### ISSUE THREAD

**Issue by eugene-kim** [twilio/twilio-node#607]
### Issue Summary
This may be more of a question but the `MessageStatus` type ([source](https://github.com/twilio/twilio-node/blob/main/lib/rest/api/v2010/account/message.d.ts#L25)) contains a `partially_delivered` string that isn't present in the documentation: https://www.twilio.com/docs/sms/api/message-resource#message-status-values

```typescript
type MessageStatus = 'queued'|'sending'|'sent'|'failed'|'delivered'|'undelivered'|'receiving'|'received'|'accepted'|'scheduled'|'read'|'partially_delivered';
```

Is the type simply outdated or are the docs missing info on the `partially_delivered` status?

Thank you!

### Technical details:
* twilio-node version: 3.49.0

**Comment by eshanholtz** [comment]
Hi @eugene-kim 

It looks like the docs are missing info on the `partially_delivered` status. This Status value was recently added as of `twilio-node` version 3.39.4. This is not a change that can be made through this library, but I've gone ahead and filed an internal ticket to get those docs updated (reference ID: DEVED-4826).

**Comment by eugene-kim** [comment]
Great, thanks for the response @eshanholtz !

**Comment by eugene-kim** [comment]
@eshanholtz just FYI the `scheduled` status is also part of the `MessageStatus` union that isn't mentioned in the [API docs](https://www.twilio.com/docs/sms/api/message-resource#message-status-values)
