### ISSUE TITLE
Broken typescript compilation

### ISSUE THREAD

**Issue by andreidiaconescu** [twilio/twilio-node#609]
I am trying to run 
```
tsc --project .
```
and i get errors:

```
node_modules/twilio/node_modules/@types/express/index.d.ts(98,44): error TS2694: Namespace '"/app/node_modules/@types/express-serve-static-core/index"' has no exported member 'ParamsDictionary'.
node_modules/twilio/node_modules/@types/express/index.d.ts(98,108): error TS2694: Namespace '"/app/node_modules/@types/express-serve-static-core/index"' has no exported member 'Query'.
node_modules/twilio/node_modules/@types/express/index.d.ts(99,17): error TS2315: Type 'ErrorRequestHandler' is not generic.
node_modules/twilio/node_modules/@types/express/index.d.ts(108,32): error TS2694: Namespace '"/app/node_modules/@types/express-serve-static-core/index"' has no exported member 'ParamsDictionary'.
node_modules/twilio/node_modules/@types/express/index.d.ts(108,96): error TS2694: Namespace '"/app/node_modules/@types/express-serve-static-core/index"' has no exported member 'Query'.
node_modules/twilio/node_modules/@types/express/index.d.ts(108,111): error TS2315: Type 'Request' is not generic.
node_modules/twilio/node_modules/@types/express/index.d.ts(109,39): error TS2694: Namespace '"/app/node_modules/@types/express-serve-static-core/index"' has no exported member 'ParamsDictionary'.
node_modules/twilio/node_modules/@types/express/index.d.ts(109,103): error TS2694: Namespace '"/app/node_modules/@types/express-serve-static-core/index"' has no exported member 'Query'.
node_modules/twilio/node_modules/@types/express/index.d.ts(109,118): error TS2315: Type 'RequestHandler' is not generic.
node_modules/twilio/node_modules/@types/express/index.d.ts(111,54): error TS2315: Type 'Response' is not generic.

```

Twilio version: 
    - "twilio": "3.49.0",
Typescript version:
     - "typescript": "3.7.3",
Node version: 12

When i downgrade to 
"twilio": "3.34.0"
the typescript compilation works.

Thank you

**Comment by sambecker** [comment]
Seeing similar `TypeScript` compilation errors when deploying `firebase` functions:

```
Type 'P' does not satisfy the constraint 'Params'.
Type 'P' is not assignable to type 'ParamsArray'.
```
relating to
```
extends core.ErrorRequestHandler<P, ResBody, ReqBody, ReqQuery> { }
interface Request<P = core.ParamsDictionary, ResBody = any, ReqBody = any, ReqQuery = core.Query> extends core.Request<P, ResBody, ReqBody, ReqQuery> { }
interface RequestHandler<P = core.ParamsDictionary, ResBody = any, ReqBody = any, ReqQuery = core.Query> extends core.RequestHandler<P, ResBody, ReqBody, ReqQuery> { }
```

Downgrading from `3.49.1` to `3.49.0` does not seem to help ...

**Comment by childish-sambino** [comment]
@andreidiaconescu Does upgrading the `@types/express` dependency in your lock file help as mentioned above?

**Comment by ntkzwane** [comment]
I was experiencing the same issue with the following dep versions:

- "twilio": "3.49.1"
- "@types/express": "4.17.7" (also tried v4.17.8)
- "typescript": "3.9.3" (also tried v4.0.2)

Deleted my `yarn.lock` file and re-installed fresh dependencies and it sorted me out on my end. Not sure which dependency combination was the problem however.

**Comment by eshanholtz** [comment]
@ntkzwane Do the freshly installed versions of `twilio`, `@types/express` and `typescript` dependencies match what you posted above? Or did the versions get updated with the fresh install?

**Comment by ntkzwane** [comment]
@eshanholtz I've got the same versions in my `yarn.lock` too
"twilio": "3.49.1"
"@types/express": "4.17.7"
"typescript": "3.9.3"

**Comment by eshanholtz** [comment]
@andreidiaconescu Does upgrading your dependencies to these versions solve your compilation issue?

**Comment by E3enezer** [comment]
Same issue `Type 'P' is not assignable to type 'ParamsArray'.`

Had to install `@types/express-serve-static-core` as suggested [here](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/47339#issuecomment-698975634) to make it work...

**Comment by neekey** [comment]
same issue here when using `tsc` to compile.

**Comment by eshanholtz** [comment]
Thanks @E3enezer for the link. @neekey have you tried installing `@types/express-serve-static-core` as suggested? 
It also looks like you'll need to upgrade to `"@types/express": "^4.17.7"`.

This appears to be a known issue with upgrading `@types/express`. I'm going to close this issue as it is unrelated to the `twilio` package. For further guidance. Please reference the [relevant github issue](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/47339#issuecomment-689695381) for additional guidance on how to resolve this error.
