### ISSUE TITLE
Twilio customParameters is showing empty 

### ISSUE THREAD

**Issue by sujeshshivaniia** [twilio/twilio-node#610]
Js: 
const twiml = new VoiceResponse();
const dial = twiml.dial({ callerId: "client:test_14"});
const client = dial.client({});
client.identity("test_15");
client.parameter({name:"name",value:"sujesh"});
client.parameter({name:"touser",value:"john"});
client.parameter({name:"fromUser",value:"tom"});        

this is the xml code gets while calling the api : 
<?xml version="1.0" encoding="UTF-8"?>
<Response>
    <Dial callerId="client:test_14">
        <Client>
            <Identity>test_15</Identity>
            <Parameter name="name" value="sujesh"/>
            <Parameter name="touser" value="john"/>
            <Parameter name="fromUser" value="tom"/>
        </Client>
    </Dial>
</Response>

****
** this is my log response after connecting through web ** 

Incoming connection from  "client:test_14"
Incoming connection from  
  { 
    "ApiVersion":"2010-04-01",
"Params":"name=sujeshn&touser=john&fromUser=tom",
"CallSid":"CA****************************",
"From":"client:test_14",
"To":"client:test_15,
"AccountSid":"AC***********************"}

 customParameters  {}

****

here after console.log()  customerParameters Shows empty. can anyone explain why this happening. i need to implement this on ios & android does it work correct there ??

https://support.twilio.com/hc/en-us/articles/115011213347-Passing-Custom-Information-via-Requests-to-Twilio
 
The need is i want to show name while calling , here i gets only the {To:client:test_15} and {From:client:test_14 } keys . 
and no values in customerParametes.

**Comment by fungiboletus** [comment]
Why did you ping random people on a Saturday evening?

Le sam. 12 sept. 2020 à 19:35, sujeshshivaniia <notifications@github.com> a
écrit :

**Comment by childish-sambino** [comment]
They're in the params: `"Params":"name=sujeshn&touser=john&fromUser=tom",`

https://www.twilio.com/docs/voice/twiml/client#custom-parameters

**Comment by sujeshshivaniia** [comment]
In document it says that :-
These custom parameters can retrieved in the SDKs. For Client JS, refer to **Connection.customerParameters**, for iOS, refer to **TVOConnectOption.params,** and for Android, refer to **ConnectOptions.getParams()**. 

"Params":"name=sujeshn&touser=john&fromUser=tom", yeah got it from the Params already it is not a JSON object and need process that to get an exact value.
I thought it will be available under Connection.customerParameters it showing empty.

Can you explain why it is not comes under  ` Connection.customerParameters ` ?

**Comment by childish-sambino** [comment]
No, I don't know why the request comes in that way. Best to contact [support](https://twilio.com/help/contact) for more help there.

**Comment by sujeshshivaniia** [comment]
:-1:
