### ISSUE TITLE
twilio conversations - roles creation api not found on twilio node

### ISSUE THREAD

**Issue by adityaloshali** [twilio/twilio-node#612]
### Issue Summary
Using the twilio node latest library unable to access the roles creation service for conversations API.
Using the code example mentioned in docs, i get the error that it does not exist.
https://www.twilio.com/docs/conversations/api/role-resource#create-a-role-resource

### Steps to Reproduce
1. install the latest twilio node library
2. write code for role creation for conversations

### Code Snippet
```node
const result = await client
        .conversations
        .roles
        .create({
          type: input.type,
          permission: input.permission,
          friendlyName: input.friendlyName
        })
```

### Exception/Log
```
Typescript - Property 'roles' does not exist on type 'Conversations'.
Console (if bypassed in TS using any) - Cannot read property 'create' of undefined
```

### Technical details:
* twilio-node version: ^3.49.1
* node version: v12.18.2

**Comment by eshanholtz** [comment]
This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.

**Comment by adityaloshali** [comment]
@eshanholtz Hi, i see that in the latest version the missing code has been added. Thanks.
marking the issue as closed.
