### ISSUE TITLE
Twilio Programmable Video - Invalid RecordingSid when deleting recording

### ISSUE THREAD

**Issue by xicovarisco** [twilio/twilio-node#615]
### Issue Summary
A summary of the issue and the environment in which it occurs. If suitable, include the steps required to reproduce the bug. Please feel free to include screenshots, screencasts, or code examples.
Unable to remove recordings from Twilio Programmable video with latest nodeJS library.
I was able to delete the composition that was generated from some recordings, so I don't think the problem is not having the right setup.
Using the code below I get the following error.

### Steps to Reproduce
1. Install the latest twilio node library
2. Run the code below with a **valid** recording SID (I can see the recording on my Twilio Console)

### Code Snippet
```node
return client.video.rooms(roomSid)
            .recordings
            .list()
            .then((recordings) => {
                recordings.forEach(async (r) => {
                    console.log('r', r);
                    try {
                        const response = await client.recordings(r.sid).remove();
                        console.log('response', response);
                    } catch (error) {
                        console.log('error deleting recording', error);
                    }
                });
            })
            .catch(error => ({ error }));
```

### Exception/Log
```
error deleting recording { Error: Invalid RecordingSid: RTc614c3d265ab511ddfcf1d71726da54d
    at success (/Users/xicovarisco/Documents/Askable/data/node_modules/twilio/lib/base/Version.js:113:15)
    at Promise_then_fulfilled (/Users/xicovarisco/Documents/Askable/data/node_modules/twilio/node_modules/q/q.js:766:44)
    at Promise_done_fulfilled (/Users/xicovarisco/Documents/Askable/data/node_modules/twilio/node_modules/q/q.js:835:31)
    at Fulfilled_dispatch [as dispatch] (/Users/xicovarisco/Documents/Askable/data/node_modules/twilio/node_modules/q/q.js:1229:9)
    at Pending_become_eachMessage_task (/Users/xicovarisco/Documents/Askable/data/node_modules/twilio/node_modules/q/q.js:1369:30)
    at RawTask.call (/Users/xicovarisco/Documents/Askable/data/node_modules/asap/asap.js:40:19)
    at flush (/Users/xicovarisco/Documents/Askable/data/node_modules/asap/raw.js:50:29)
    at process._tickCallback (internal/process/next_tick.js:61:11)
  status: 400,
  code: 20001,
  moreInfo: 'https://www.twilio.com/docs/errors/20001',
  details: undefined }
```

### Technical details:
* twilio-node version: 3.49.3
* node version: v10.13.0

**Comment by thinkingserious** [comment]
Hello @xicovarisco,

Thank you for reaching out!

At first look, this does not seem to be a helper library issue. To confirm, could you please try deleting the recording using the API Explorer with the above RecordingSid? If you still can not delete the resource, in order to properly debug this issue, please [file a support ticket](https://twilio.com/help/contact). Thanks!

With best regards,

Elmer

**Comment by xicovarisco** [comment]
Hey @thinkingserious,
Thanks for properly answering :)

I've done what you suggested and it worked out. However, I don't understand why I can delete through the Console and I can't delete through the normal API.

This didn't work:
`client.recordings('RTc614c3d265ab511ddfcf1d71726da54d').remove()`

Do you have any ideas on what could be done to fix the API issue?

Cheers

**Comment by thinkingserious** [comment]
Hello @xicovarisco,

It looks like you may be using the [wrong function](https://www.twilio.com/docs/video/api/recordings-resource#delete-instance), please try: `client.video.recordings('RTc614c3d265ab511ddfcf1d71726da54d').remove();`. 

Thanks!
