### ISSUE TITLE
Twilio chat client

### ISSUE THREAD

**Issue by caduceusGithub** [twilio/twilio-node#616]
I'm trying to **initialize the programmable chat client** as defined in the documentation above:

`Twilio.Chat.Client.create(token);`

running the code returns an **error** as described:

`Cannot read property 'Client' of undefined`

**Comment by childish-sambino** [comment]
Think you're looking for the _Twilio Client JS SDK_ which is not this repo.

https://www.twilio.com/docs/chat/sdk-download-install
