### ISSUE TITLE
How can i fetch by status ?

### ISSUE THREAD

**Issue by nomankt** [twilio/twilio-node#624]
### Issue Summary
A summary of the issue and the environment in which it occurs. If suitable, include the steps required to reproduce the bug. Please feel free to include screenshots, screencasts, or code examples.

### Steps to Reproduce
1. This is the first step
2. This is the second step
3. Further steps, etc.

### Code Snippet
```node
# paste code here
```

### Exception/Log
```
# paste exception/log here
```

### Technical details:
* twilio-node version: 
* node version:

**Comment by childish-sambino** [comment]
Could you provide more details, code samples, and links for what you're trying to accomplish?

**Comment by eshanholtz** [comment]
Closing this issue until more details are provided.
