### ISSUE TITLE
Update TS typings: add "trim" option to client.conferences(ConferenceSid).participants.create

### ISSUE THREAD

**Issue by MaxVynohradov** [twilio/twilio-node#627]
Issue Summary:
In Twilio console we can see next:

![image](https://user-images.githubusercontent.com/13771219/98533077-2d418800-228b-11eb-9d57-27c81bea6883.png)

But TS typings of current method don't have this option:

![image](https://user-images.githubusercontent.com/13771219/98532820-e18ede80-228a-11eb-9150-20ea48c8263c.png)

**Comment by eshanholtz** [comment]
In order to properly debug this issue, please [file a support ticket](https://twilio.com/help/contact)
