### ISSUE TITLE
jitterBufferSize attribute is not available for Twiml Conference

### ISSUE THREAD

**Issue by adrys-lab** [twilio/twilio-node#628]
### Issue Summary
When returning a Twiml response for a Conference participant,
we don't find `jitterBufferSize` as a valid attribute for the Conference Dial.

```
const voiceResponse = new twiml.VoiceResponse()
    const dial = voiceResponse.dial({
      timeLimit: 10000
    })

    dial.conference(
      {
        startConferenceOnEnter: true,
        endConferenceOnExit: false,
        record: 'do-not-record',
        beep: 'false',
        waitUrl: '',
        statusCallbackEvent: ['join', 'leave', 'end'],
        statusCallback: url,
        region: 'de1',
        maxParticipants: 25
        //'jitterBufferSize': 'medium'
      },
      callSid
    )
```

Seems 'jitterBufferSize' is not present in `ConferenceAttributes`.

Even though we know this attribute is at participant level,
We don't see it in any TWIML response.

We use last version 3.51.0 for Node.

Can you provide please the right way to send that configuration parameter using twilio lib ?
or a valid workaround,
or a code snippet as example.

Checking the official DOC, we understand it should be present there for TWIML:
https://www.twilio.com/docs/voice/twiml/conference#attributes-jitterBufferSize

Also here:
https://www.twilio.com/blog/improve-call-experience-new-twilio-conference-jitter-buffer-controls

Thanks

### Code Snippet

```node
const voiceResponse = new twiml.VoiceResponse()
    const dial = voiceResponse.dial({
      timeLimit: 10000
    })

    dial.conference(
      {
        startConferenceOnEnter: true,
        endConferenceOnExit: false,
        record: 'do-not-record',
        beep: 'false',
        waitUrl: '',
        statusCallbackEvent: ['join', 'leave', 'end'],
        statusCallback: url,
        region: 'de1',
        maxParticipants: 25
        //'jitterBufferSize': 'medium'
      },
      callSid
    )
```

### Technical details:
* twilio-node version: 3.51.0
* node version: 12.0

**Comment by thinkingserious** [comment]
Hello @adrys-lab,

It looks like this [setting is set](https://github.com/twilio/twilio-node/blob/b2aaa7517fa7bbb8fd111987377de2eec2ea2636/lib/rest/api/v2010/account/conference/participant.js#L183) at the `participant` level. So I'm thinking the docs might be incorrect. Can you verify that setting this at the participant level will achieve the results you need?

With best regards,

Elmer

**Comment by adrys-lab** [comment]
hi @thinkingserious thanks for your answer,

Responding to your question,
we see the `jitterBufferSize` at participant level, yes,

BUT

in our specific use-case, we don't manually create the Participants,
We just create the Conference,

and the participants arrive to it redirected by Twilio (Twiml App),

So, 
how can we create the Conference with the specific `jitterBufferSize` (at conference level) using Twiml Lib from your library ?

**Full Use Case**

We want to add 2 participants to a Conference:
- The external caller
- An agent connected to a phone with the Twilio SDK embedded.

After some processing, we redirect the external caller from one stack to another, 
and the agent uses the `Device.connect()` method on the Twilio JS SDK.

Therefore our service thus receives 2 callbacks for our 2 participants. 

To each callback, we respond with a Conference TwiML so that they can be connected. 

It is at this point that we would like to add the jitterBufferSize to the Conference TwiML for the agent (connected with a client:XXX device name)

**Comment by eshanholtz** [comment]
Hi @adrys-lab 
It looks like this is an oversight made by one of our backend teams. This is not a change that can be made in the library. An internal ticket has been filed against the relevant product team (reference ID CONF-2851).

**Comment by eshanholtz** [comment]
This issue has been resolved on the back end. You should see the fix reflected in the helper library after our next release on 2020-12-02.
