### ISSUE TITLE
Possible vulnerability in a Twilio dependency

### ISSUE THREAD

**Issue by lukasfialho** [twilio/twilio-node#631]
### Issue Summary

It has been discovered a possible vulnerability at axios dependency of Server-Side Request Forgery (SSRF), as the link below:

https://snyk.io/test/npm/twilio/3.52.0

### To Reproduce

Just run the Snyk software at a project that has Twilio installed.

**Comment by eshanholtz** [comment]
Looks like there's a fix recently merged that hasn't been released yet. We'll have to roll our dependency version when that's done. This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.

**Comment by alonbhaim** [comment]
+1

@eshanholtz do you any estimation when you release the upgrade for axios ?

**Comment by snatalenko** [comment]
The fix is merged in #640, but new version is not yet released. Shouldn't the issue stay open until then?
