### ISSUE TITLE
Twilio Verify - requested resource /Services/.../VerificationCheck was not found

### ISSUE THREAD

**Issue by mding5692** [twilio/twilio-node#633]
### Issue Summary
Seeing this in our sentry: 
`The requested resource /Services/VA.../VerificationCheck was not found`

Customers are complaining, seems to be happening occasionally as can not reproduce locally? Trying to get a better idea.

### Steps to Reproduce
1) Type in phone number
2) Send API call to Twilio Verify to send verification code

### Code Snippet
```node
# paste code here
```

### Exception/Log
```
The requested resource /Services/VA.../VerificationCheck was not found
```

### Technical details:
* twilio-node version: v3.50.0
* node version: v12

**Comment by mding5692** [comment]
<img width="498" alt="Screen Shot 2020-12-04 at 5 10 12 PM" src="https://user-images.githubusercontent.com/9067177/101220383-9383b580-3653-11eb-93f0-f487eff1aa01.png">

**Comment by koleary94** [comment]
@mding5692 I just ran into the same issue (was saying the `VerificationCheck` was not found) and had to downgrade to `3.51.0` to get the api call to work

**Comment by mding5692** [comment]
Will try and see whats going on

**Comment by JenniferMah** [comment]
Hi @mding5692
Could you provide a bit more context or some code samples? Did moving to `twilio-node version: 3.51.0` resolve the error? I'm unable to reproduce the error message you are seeing using `twilio-node version:3.50.0` and `node v12.2`.

**Comment by mding5692** [comment]
> Hi @mding5692
> Could you provide a bit more context or some code samples? Did moving to `twilio-node version: 3.51.0` resolve the error? I'm unable to reproduce the error message you are seeing using `twilio-node version:3.50.0` and `node v12.2`.

Hi @JenniferMah Im not too sure either whats happening, I contacted the customer and started talking to them, it seems like its being sent to the number as I can see it in twilio verify logs but its appearing as expired. What would that mean?

**Comment by mding5692** [comment]
I can provide more info on this customer and the issue in an email as it will have our customer information and could I get more information from your side and your logs?

**Comment by mding5692** [comment]
Going to just voice call option as a fallback as its very hard to not receive a call unless explicitly blocked. 
Not sure what the issue is so going to use this workaround approach to "fix" it.

Referencing this: https://www.twilio.com/docs/verify/api/verification?code-sample=code-start-a-verification-with-voice&code-language=Node.js&code-sdk-version=3.x

**Comment by jcanaviri** [comment]
twilio.base.exceptions.TwilioRestException: HTTP 404 error: 
Unable to create record: The requested resource /Services/VAxxxxxxxxxxxxxxx/VerificationCheck was not found
