### ISSUE TITLE
Option "includeSubaccounts" does not work when listing usage records

### ISSUE THREAD

**Issue by bilics** [twilio/twilio-node#635]
### Issue Summary

Listing usage records for the main account does not include sub accounts - even if the option "includeSubaccounts" is set to true.

### Steps to Reproduce
1. Run the code snippet below

### Code Snippet
```
const accountSid = 'main_account_id';
const authToken = 'your_auth_token';
const client = require('twilio')(accountSid, authToken);

client.usage.records.lastMonth.each({category: 'channels-messaging-outbound', includeSubaccounts: true}, record => {
     console.log(record)
});
```

### Technical details:
* twilio-node version: ^3.54.0
* node version: v12.13.1

**Comment by thinkingserious** [comment]
Hello @bilics,

I have been able to reproduce this. Thank you for reporting!

This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.

With best regards,

Elmer

**Comment by childish-sambino** [comment]
This is not a change that can be made in the library. Please [file a support ticket](https://twilio.com/help/contact) to inquire about adding this feature to the API.
