### ISSUE TITLE
Make module tree shakable

### ISSUE THREAD

**Issue by thomaschaaf** [twilio/twilio-node#638]
### Issue Summary
The way this package is built webpack is not able to shake off unused code. This causes this npm module to be very large at 13 MB. To speed up (cold starts) of AWS Lambda functions the code needs to be as small as possible this library currently is extremly huge.

### Technical details:
* twilio-node version: 3.52.0

**Comment by eshanholtz** [comment]
Would the packages [lazy loading functionality](https://github.com/twilio/twilio-node#lazy-loading) help with speeding up lambda functions?

**Comment by thomaschaaf** [comment]
No as webpack still can not remove the files which are unused.

**Comment by Mattensor** [comment]
I'm having the same issue, twilio is bloating my lambda. @thomaschaaf Did you have any luck reducing your bundle? I'm considering throwing this packing and using http calls to hit the communications api

**Comment by thomaschaaf** [comment]
@mattensor i am using serverless-webpack and put it in the externals that way at least it's only included once.
