### ISSUE TITLE
I got : TypeError: url.URL is not a constructor running examples with my account parameters

### ISSUE THREAD

**Issue by sergeynilov** [twilio/twilio-node#639]
Hello,
I tried to run several examples from https://www.twilio.com/docs/libraries/node

and running code (with my account sid/token)
```
const accountSid = 'ACXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX';
const authToken = 'your_auth_token';
const client = require('twilio')(accountSid, authToken);

client.calls
  .create({
    url: 'http://demo.twilio.com/docs/voice.xml',
    to: '+14155551212',
    from: '+15017250604',
  })
  .then(call => process.stdout.write(call.sid));

```  
  
I got error :
`TypeError: url.URL is not a constructor  
`  

I tried to debug this issue in Twilio.js:258 and found :
https://prnt.sc/w79oys

and ref to undefined element
https://prnt.sc/w79pqi

and I see ref 10 years old
https://prnt.sc/w79q4s
can it be reason of my error and why so ?

I tried version of twilio 3.54.1 (latest) and 3.54.0
but I have the same error and the same data I see debugging...

In my OS :
```
$ node -v
v14.15.1
$ npm -v
6.14.8
serge@lsb_release -d; uname -r; uname -i
Description:    Ubuntu 18.04.5 LTS
4.15.0-128-generic
x86_64

```
Why so and how it can be fixed ?

Thanks!

**Comment by JenniferMah** [comment]
Hi @sergeynilov
I'm unable to reproduce the error you are seeing. Could enable the [debug logs](https://github.com/twilio/twilio-node#enable-debug-logging) and include the results in your reply?

**Comment by karthik22061993** [comment]
Hi, I am using cypress framework to test angular app that uses two factor authentication. With twilio I grab security code. 
```
accountSid ="xxxxxxxxxxx";
 authToken="yyyyyyyyyyyy";
  const client = require('twilio')(accountSid, authToken);
        let messages;
        (async () => {
            messages = await client.messages.list({limit: 5});
**///---->error is thrown here Uncaught (in promise) TypeError: url.URL is not a constructor**
        })();
        console.log(messages);
        let code = "";
      
        for (message of messages) {
          if (message.direction == "inbound" && message.body.includes("Use verification code") && 
              message.body.includes("licensing")) {
            code = message.body.replace(/[^0-9]+/g, "");
            console.log(new Date(), message.dateUpdated, code);
            break;
          }
        }
        return code;
````

I thought it might be version issue between node and twilio, so I upgraded everything to latest ones.
node: 15.5.0
npm: 7.3.0
twilio: 3.54.1

But nothing has changed, can someone take a look?

**Comment by JenniferMah** [comment]
Hi @karthik22061993
Our library does not currently support node: 15.5.0. Please see [here](https://github.com/twilio/twilio-node#supported-nodejs-versions) for the node versions we support. I would start off by verifying that you are running a supported node version that includes the `URL` class, which has been available since Node v6.13.0 ([reference](https://nodejs.org/api/url.html#url_class_url)). Also check out [issue 577](https://github.com/twilio/twilio-node/issues/577) it looks like this error is related to [defunctzombie/node-url#37](https://github.com/defunctzombie/node-url/issues/37).

**Comment by ttgiang** [comment]
Hi Jennifer - 

I signed up today and find myself in the same predicament. I'm working with the following:

- Windows 10 OS
- Node 10.16.3
- Twilio 3.54.2

Console logging the client variable looks good. However, I am seeing the same error when using client.messages.create:

dashboard.fetchSupport TypeError: url.URL is not a constructor
    at Twilio.request (Twilio.js:258)
    at Api../node_modules/twilio/lib/base/Domain.js.Domain.request (Domain.js:34)
    at

**Comment by chukwumaokere** [comment]
I'm having this same problem too.

Would it be related to this: https://github.com/twilio/twilio-node/issues/577#issuecomment-645560439

**Comment by shwetha-manvinkurke** [comment]
@ttgiang, @chukwumaokere Is this repo being used by you on the client side?

**Comment by parmenion59** [comment]
same issue here, any solution ?

**Comment by thinkingserious** [comment]
Hi @parmenion59,

Are you also using the repo on the client size? Please verify the versions of `twilio-node` and and `node` so that we may try to reproduce. Thank you!

With best regards,

Elmer
