### ISSUE TITLE
How can I use enable-debug-logging option in my Laravel/jQuery/vue  app?

### ISSUE THREAD

**Issue by sergeynilov** [twilio/twilio-node#643]
Hello,
Reading twilio docs about enable logging  https://github.com/twilio/twilio-node#enable-debug-logging
I try to use this functionality in my Laravel 8 / jQuery 3.5.1 / vue 2.6 / Bootstrap 4.5
I use this https://www.twilio.com/blog/implementing-programmable-chat-php-laravel-vue-js article 
so I add Twilio Chat in different way :
In my php blade file I have lines :
```
@endsection

@section('scripts')
    <script src="//media.twiliocdn.com/sdk/js/common/v0.1/twilio-common.min.js"></script>
    <script src="//media.twiliocdn.com/sdk/js/chat/v3.0/twilio-chat.min.js"></script>
    
    <script>
        window.Laravel = {!! json_encode([
                    'csrfToken' => csrf_token(),
                ]) !!};
    </script>
@endsection

```

So I added Twilio
with command 
`npm install twilio
`and in mount event :
```
        mounted() {
            this.setAppTitle('Team Chat', 'Users Listing', bus)           
            if ( this.accountSid && this.authToken ) {
                console.log('SETTING logLevel::')
                
                const client = require('twilio')(this.accountSid, this.authToken, {
                    logLevel: 'debug'
                })
                console.log('client::')
                console.log(client)
                
            } // if ( this.accountSid && this.authToken ) {

```

But I did not found how and in which way can I see/use logging info from this option ?
In the browser's console of my app?

Or in the console of used channel under ny Twilio account :  https://prnt.sc/wf412k ?

I have some problems , written here : https://github.com/favoriabs/twilio-programmable-chat/issues/12
and I would like to use this logging option salving my proble...

Thanks!

**Comment by JenniferMah** [comment]
Hi @sergeynilov
Enabling debug logging in the default HTTP client will only show output when you make an HTTP request like sending an SMS. The messages should be printing to your terminal where you are compiling and running your project. Based on the code snippet above I would expect to see _SETTING logLevel::_, _client::_, and the actual client being printed in the console.
