### ISSUE TITLE
The requested resource /Services/VAXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/VerificationCheck was not found"

### ISSUE THREAD

**Issue by jpmeganathan** [twilio/twilio-node#646]
{
  "status": 404,
  "message": "The requested resource /Services/VAXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/VerificationCheck was not found",
  "code": 20404,
  "moreInfo": "https://www.twilio.com/docs/errors/20404"
}

**Comment by thinkingserious** [comment]
Hello @jpmeganathan,

Could you please provide a bit more information so that I may try to reproduce. First, can we get the source code that produced this error? Thank you!

With best regards,

Elmer

**Comment by mding5692** [comment]
Had a similar issue in the past with users trying to verify their phone with sms verification codes, would check the console and say its expired so we would use the user's phone number and send it to them and ask in real-time to see if they got it but would get this error message

**Comment by eshanholtz** [comment]
Hi @jpmeganathan,

According to a customer experiencing a similar issue discussed in #633, upgrading to version >=3.51.0 solved this problem for them. What version of the twilio-node helper library are you using? I recommend trying to use our [debug logging](https://github.com/twilio/twilio-node#enable-debug-logging) functionality to try and inspect the request that's being sent to Twilio. Please post that debug output here if you're still experiencing these issues after the version upgrade.

@mding5692 

Have you tried the debug logging I mentioned above? If nothing looks unusual there, I recommend [filing a support ticket](https://twilio.com/help/contact).

**Comment by LuisSaybe** [comment]
Had to dig into these issues to find out the same still is still happening at my company while using Twilio, I have quite a few users who never receive a code via text or when they redeem the correct code, I get the error referenced in this issue.

Using version `"twilio": "^3.66.1"`

**Comment by shirishsurti** [comment]
This issue is blocking me from trying out Twilio Verify API.

I created a Verify Service and used the Twilio Python package V7.4.0 to generate an OTP request but the API call fails with the below error message,

twilio.base.exceptions.TwilioRestException: HTTP 404 error: Unable to create record: The requested resource /Services/<service SID>/VerificationCheck was not found

I am trying Twilio Verify for the first time. Any pointers will help.
