### ISSUE TITLE
Latest messages not available in messages.list

### ISSUE THREAD

**Issue by grimunit** [twilio/twilio-node#647]
### Issue Summary
We are missing the latest messages that have been sent in response back to our customers numbers, so our conversation is out of date for several hours at times.

### Steps to Reproduce
1. We are handling incoming messages as they are sent to our customers number and showing our own preview of the message by creating a copy of the message and showing it to them.
2. They then go to open up the conversation on the frontend, and they keep experiencing not seeing the messages that came in just recently show up in the conversation.
3. The backend code shown below is going to get the conversation, and it's missing the latest messages, and they don't show up for several hours sometimes, it's intermittent.
4. Do you guys have any sort of guarantees around timing of sent messages availability? I would hate to have to build an entire layer of redundancy because we can't know if you will be providing all of the messages (including very recently sent) in these calls.

### Code Snippet
```node
        const twilio: RestClient = require('twilio')(subAccountSid, authToken);

	const countryCode: string = cellPhoneCode || COUNTRY_CODE_USA;

	const fullCustomerNumber: string = `+${countryCode}${cellPhone}`;

	const { customerMessages } = await getCustomerMessages(twilio, fullCustomerNumber);
	const { companyMessages } = await getCompanyMessages(twilio, fullCustomerNumber);

	return {
		customerMessages: JSON.stringify(customerMessages),
		companyMessages: JSON.stringify(companyMessages),
	};

async function getCompanyMessages(
	twilio: RestClient,
	customerNumber: string,
): Promise<{ companyMessages: {}[] }> {
	return new Promise<{ companyMessages: {}[] }>((resolve, reject) => {
		try {
			twilio
				.messages
				.list({
					to: customerNumber
				}, (error, messages) => {
					if (error) {
						reject(error);
					}
					const resolvedMessages = messages || [];
					resolve({ companyMessages: resolvedMessages });
				});
		} catch (e) {
			reject(e);
		}
	});
}

async function getCustomerMessages(
	twilio: RestClient,
	customerNumber: string,
): Promise<{ customerMessages: {}[] }> {
	return new Promise<{ customerMessages: {}[] }>((resolve, reject) => {
		try {
			twilio
				.messages
				.list({
					from: customerNumber,
				}, (error, messages) => {
					if (error) {
						reject(error);
					}
					const resolvedMessages = messages || [];
					resolve({ customerMessages: resolvedMessages });
				});
		} catch (e) {
			reject(e);
		}
	});
}
```

### Exception/Log

No exception being thrown

### Technical details:
* twilio-node version: 3.33.1
* node version: 10.15.3

**Comment by thinkingserious** [comment]
Hello @grimunit,

Thank you for the detailed issue support!

This does not appear to be an issue with this helper library. In order to properly debug this issue, please [file a support ticket](https://twilio.com/help/contact). If you determine otherwise, please feel free to reopen.

With best regards,

Elmer
