### ISSUE TITLE
`2021-01-21T12:09:44.988266+00:00 app[web.1]: /app/node_modules/twilio/lib/rest/Twilio.js:140 throw new Error('accountSid must start with AC');

### ISSUE THREAD

**Issue by rohanmathewalex** [twilio/twilio-node#648]
`2021-01-21T12:09:44.988266+00:00 app[web.1]: /app/node_modules/twilio/lib/rest/Twilio.js:140

2021-01-21T12:09:44.988280+00:00 app[web.1]:     throw new Error('accountSid must start with AC');

2021-01-21T12:09:44.988281+00:00 app[web.1]:     ^
2021-01-21T12:09:44.988282+00:00 app[web.1]: 

2021-01-21T12:09:44.988282+00:00 app[web.1]: Error: accountSid must start with AC`

I'm receiving this error while deploying my application to Heroku

My Application worked efficiently on the development environment. when deploy application I'm receiving this

_Originally posted by @rohanmathewalex in https://github.com/twilio/twilio-node/issues/600#issuecomment-764616181_

**Comment by shwetha-manvinkurke** [comment]
Hi @rohanmathewalex,

Do you have a code sample that I can take a look at? Also, is this similar to the [issue](https://github.com/twilio/twilio-node/issues/600) you linked? If so, have you followed the [workaround](https://github.com/twilio/twilio-node/issues/600#issuecomment-668144045) mentioned there? Did that not work?

Thanks,
Shwetha

**Comment by rohanmathewalex** [comment]
> Hi @rohanmathewalex,
> 
> Do you have a code sample that I can take a look at? Also, is this similar to the [issue](https://github.com/twilio/twilio-node/issues/600) you linked? If so, have you followed the [workaround](https://github.com/twilio/twilio-node/issues/600#issuecomment-668144045) mentioned there? Did that not work?
> 
> Thanks,
> Shwetha

`const db = require('../config/connection');

const config=  require('../config/config');
const collection = require('../config/collection');
const client = require("twilio")(config.accountSID,config.authToken);
const bcrypt = require('bcrypt');
const objectId = require('mongodb').ObjectID;


module.exports={ 
     generateOtp:(userNumber,channel) => {
        client
        .verify
        .services(config.serviceID)
        .verifications
        .create({
          to:`+91${userNumber}`,
          channel:channel
        })
        .then((data) => {
           // console.log(data)
            // return callback(null, 'success');
        })
        .catch((error) => {
            console.log(error);
        });
     },
     
     verifyOtp:(userNumber,userOtp) => {
         client
         .verify
         .services(config.serviceID)
         .verificationChecks
         .create({
            to:`+91$${userNumber}`,
            code:userOtp

         })
         .then((data) => {
            //console.log(data);
         })
         .catch((error) => {
             //console.log(error);
         })
     },
 `


When I'm working on local development it sends OTP to the user and verify OTP   then tried to deploy on Heroku and I'm receiving an error
`/app/node_modules/twilio/lib/rest/Twilio.js:140
2021-01-21T13:16:37.288357+00:00 app[web.1]:     throw new Error('accountSid must start with AC');
2021-01-21T13:16:37.288358+00:00 app[web.1]:     ^
2021-01-21T13:16:37.288359+00:00 app[web.1]: 
2021-01-21T13:16:37.288359+00:00 app[web.1]: Error: accountSid must start with AC
2021-01-21T13:16:37.288360+00:00 app[web.1]:     at new Twilio (/app/node_modules/twilio/lib/rest/Twilio.js:140:11)`


accountsid must start with AC I had cross-checked my accountSid and it starts with AC I don't know why Heroku shows this error. In VS code I'm not getting any error. It's working perfectly

**Comment by rohanmathewalex** [comment]
I'm using Twilio verify service.
Could you tell why it is happening

**Comment by rohanmathewalex** [comment]
> Hi @rohanmathewalex,
> 
> Do you have a code sample that I can take a look at? Also, is this similar to the [issue](https://github.com/twilio/twilio-node/issues/600) you linked? If so, have you followed the [workaround](https://github.com/twilio/twilio-node/issues/600#issuecomment-668144045) mentioned there? Did that not work?
> 
> Thanks,
> Shwetha

Thank you Issue solved
