### ISSUE TITLE
Support personalizing SMS with variables like recipient first name

### ISSUE THREAD

**Issue by mhatvan** [twilio/twilio-node#655]
### Feature request
For the current client project that I am working, it is a business requirement to bulk send SMS with a salutation like "Dear {firstName}, etc."

Similar to how mailgun does it, it would be great to be able to send values like  `["John Doe <+491625559232>"]` instead of just phone number arrays like `["+491625559232"]` which resolves the first name and last name of John Doe.

**Comment by shwetha-manvinkurke** [comment]
@mhatvan Why can't you simply add the salutation needed in the body of your message when you bulk send the sms if you are using our node helper?
