### ISSUE TITLE
Bulk send SMS with a dynamic alphanumeric sender ID

### ISSUE THREAD

**Issue by mhatvan** [twilio/twilio-node#659]
### Feature request
For the client project that I am working on, a requirement is to send out SMS with an alphanumeric ID that should be dynamic based on the logged-in user who is sending out these SMS. So the sender could be e.g. "Restaurant A" or "Restaurant B".

I followed this great guide to set up bulk sending SMS to recipients: https://www.twilio.com/blog/2017/12/send-bulk-sms-twilio-node-js.html

Unfortunately, it looks like you have to define either `TWILIO_NOTIFY_SERVICE_SID` or `TWILIO_MESSAGING_SERVICE_SID` upfront in the Twilio Dashboard. 

Is there any way of setting a custom, dynamic alphanumeric ID through the API right before sending it out?

**Comment by shwetha-manvinkurke** [comment]
@mhatvan looks like you probably would need to set up multiple messaging services with your custom number/s for each and handle the logic of sending based on who's logged in programmatically in your code. Either way, this doesn't look like a helper library issue to me. Please reach out to [support](https://support.twilio.com/) with your request.
