### ISSUE TITLE
SyntaxError: Unexpected token U in JSON at position 4

### ISSUE THREAD

**Issue by metrocoding** [twilio/twilio-node#662]
Hi this is my Code for sending SMS

```
const sendSMS = async (body: string, to: string) => {
    const client = twilio(accountSID, authToken);
    const options = {
        body,
        from: twilioPhoneNumber,
        to,
    };

    try {
        const messageInstance = await client.messages.create(options);
        if (messageInstance.status === "sent") return true;
        else {
            logger.error(
                `TWILIO_SMS - status: ${messageInstance.status} - error_code: ${messageInstance.errorCode} - error_message: ${messageInstance.errorMessage}`
            );
        }
    } catch (err) {
        console.log(err);
    }
};
```
it returns `SyntaxError: Unexpected token U in JSON at position 4` in a catch block

after I investigate in error trace I found that in `node_modules/twilio/lib/base/RestException.js:7:59` file I got a response like this:
```
{ 
      statusCode: 451, 
      body: '451 Unavailable For Legal Reasons' 
}
```
this response cause error in line 7 when try to `Json.parse(response.body)`
see the picture.

and I wanna know why I get a 451 error?  because I'm from Iran?

<img width="1085" alt="Screen Shot 2021-03-03 at 4 21 47 PM" src="https://user-images.githubusercontent.com/46874334/109808795-cc283080-7c3c-11eb-86cf-e49929f42fe7.png">

**Comment by eshanholtz** [comment]
In order to properly debug this issue, please [file a support ticket](https://twilio.com/help/contact).
