### ISSUE TITLE
Error: getaddrinfo ENOTFOUND conversations.roaming.gll.twilio.com

### ISSUE THREAD

**Issue by noih** [twilio/twilio-node#666]
### Issue Summary
I found that DNS cannot resolve the domain of the API.

For Example: https://conversations.roaming.gll.twilio.com/v1/Users

I modified the `getHostname` in `lib/rest/Twilio.js` and removed the edge / region to bypass the problem. 

### Exception/Log
```
> nslookup https://conversations.roaming.gll.twilio.com/v1/Users
Server:  8.8.8.8
Address: 8.8.8.8#53

** server can't find https://conversations.roaming.gll.twilio.com/v1/Users: NXDOMAIN
```

### Technical details:
* twilio-node version: 3.59.0
* node version: v12.20.1

**Comment by thinkingserious** [comment]
Hello @noih,

Is your intention to call `conversations.twilio.com`? 

I may not understand the full use case, could you please provide some additional context? Thanks!

With best regards,

Elmer

**Comment by noih** [comment]
I tried to find out the root cause and found that if the environment variables `TWILIO_REGION` and `TWILIO_EDGE` are set, for example: 
```
TWILIO_EDGE=roaming
TWILIO_REGION=gll
```

The SDK will call to `https://conversations.roaming.gll.twilio.com/`, resulting in a DNS error.
for example, create a user:
```
-- BEGIN Twilio API Request --
POST https://conversations.roaming.gll.twilio.com/v1/Users
Headers:
User-Agent: twilio-node/3.59.0 (node.js v12.20.1)
Accept-Charset: utf-8
Content-Type: application/x-www-form-urlencoded
Accept: application/json
Connection: close
-- END Twilio API Request --
```

**Comment by thinkingserious** [comment]
Thank you for the additional information! What is the end result you are looking for? Should the URL be `conversations.roaming.gll.twilio.com`. I'm not sure what you are ultimately trying to do. I'm not familiar with the usage of `roaming.gll` in the URL.

**Comment by noih** [comment]
I read this [document](https://www.twilio.com/docs/global-infrastructure/edge-locations/legacy-regions). What happens if I set `edge` and `region` in TwilioClientOptions ? 

Finally, I deleted the environment variable, but it was not mentioned in the documentation.

**Comment by noih** [comment]
Maybe I misunderstood the meaning of these two parameters 😱

**Comment by thinkingserious** [comment]
Thank you for the clarification!

Maybe https://api.conversations.roaming.twilio.com is the configuration you are looking for? (I'm assuming you only care about using the `roaming` edge).

Once I fully understand your end goal I can make some recommendations for docs updates.

**Comment by noih** [comment]
It is recommended to explain in the document that edge / region is used for `Interconnect` service, and even if it is not set with `TwilioClientOptions`, it will be affected by environmental variables.
