### ISSUE TITLE
TypeScript: Cannot find module 'twilio'

### ISSUE THREAD

**Issue by a-dpq** [twilio/twilio-node#670]
I'm getting started with TypeScript, and I I get the following error on the line `import twilio from 'twilio'`:

> Cannot find module 'twilio'. Did you mean to set the 'moduleResolution' option to 'node', or to add aliases to the 'paths' option?

Here is my `tsconfig.json`:

```
{
  "compilerOptions": {
    "target": "es2020",
    "module": "es2020",
    "strict": true,
    "moduleResolution": "node",
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true
  }
}
```

What do I need to do to get TypeScript to use the types defined in `node_modules/twilio/index.d.ts`?

**Comment by philnash** [comment]
Try `import { Twilio } from "twilio"` instead. You can see more on using Twilio in TypeScript in this post on [sending SMS with TypeScript](https://www.twilio.com/blog/send-sms-typescript-twilio) or just by checking the [TypeScript tag on the Twilio blog](https://www.twilio.com/blog/tag/typescript).

**Comment by a-dpq** [comment]
> Try `import { Twilio } from "twilio"` instead. You can see more on using Twilio in TypeScript in this post on [sending SMS with TypeScript](https://www.twilio.com/blog/send-sms-typescript-twilio) or just by checking the [TypeScript tag on the Twilio blog](https://www.twilio.com/blog/tag/typescript).

Thanks, that worked!
