### ISSUE TITLE
ReservationStatus TypeScript type has an invalid value

### ISSUE THREAD

**Issue by djdmbrwsk** [twilio/twilio-node#676]
### Issue Summary
Based on the [resource docs](https://www.twilio.com/docs/taskrouter/api/reservations) and the [event docs](https://www.twilio.com/docs/taskrouter/api/event#event-types), it looks like `wrapping` is not a valid status for a reservation. Yet `wrapping` is [present as an option](https://github.com/twilio/twilio-node/blob/main/lib/rest/taskrouter/v1/workspace/task/reservation.d.ts#L17) in the TypeScript types.

**Comment by shwetha-manvinkurke** [comment]
@djdmbrwsk the code is auto-generated from the internal api definitions which lists all of those mentioned statuses. Following up with the docs team to find out why the mismatch.
