### ISSUE TITLE
Dependency url-parse fails audit check

### ISSUE THREAD

**Issue by tylerfehr** [twilio/twilio-node#688]
### Issue Summary
With the release of 3.67.0,  url-parse is failing `npm audit`.

### Exception/Log
![Screen Shot 2021-08-16 at 9 22 44 AM](https://user-images.githubusercontent.com/56086429/129570602-df8af7da-9cfe-4e0b-b9d4-b133be92ef2d.png)

### Technical details:
* twilio-node version: 3.67.0

**Comment by JenniferMah** [comment]
Hi @tylerfehr! This should be fixed by this [PR](https://github.com/twilio/twilio-node/pull/686) in the next release on 8/25.
