### ISSUE TITLE
Video Composition get stuck in enqueue for long time incase multiple callbacks for composition of same RoomID

### ISSUE THREAD

**Issue by Krishank-Tripathi** [twilio/twilio-node#690]
### Issue Summary
While fetching callback URL from composition for particular room_id recordings I am facing this issue where composition status is stuck to enqueue for a long time this doesn't happen in normal cases.

Due to this on the callback, I am doing an action for Push notification which is getting delayed.

The following case does not happen for the same video call duration of 8-10 min when called for a single time.
But if the composition is called back to back then the two compositions are stuck in en queue for a long time.

Possible causes: Resource Allocation to convert the following compositions video from same room ID recordings.

### Steps to Reproduce
1. Create a Room for Video Call with Room type Group-Small 
2. On End of Call, Call function or API that triggers the below in code snippet function for composition creation. 
3. Again join the room & after some time end call will repeat step 2.

### Code Snippet
```node
# paste code here
let videoRecordings: any[] = await demo_client.video.recordings.list({
			groupingSid: [roomID],
			limit: 20
		});

		if (!videoRecordings.length)
			throw new BadRequestError("No Such Video record refernece Found");

		let composedVideo = await demo_client.video.compositions.
			create({
				roomSid: roomID,
				audioSources: '*',
				videoLayout: {
					grid: {
						video_sources: ['*']
					}
				},
				statusCallback: callBackURL, //added to test call back via url
				statusCallbackMethod: "GET",
				format: 'mp4'
			});
```

### Exception/Log
```
# paste exception/log here
```

### Technical details:
* twilio-node version: 3.49.1
* node version: 12.18.3

**Comment by eshanholtz** [comment]
This does not appear to be an issue with the Node helper library. In order to properly debug this issue, please [file a support ticket](https://twilio.com/help/contact).
