### ISSUE TITLE
BrandRegistrationListInstanceCreateOptions is missing brandType

### ISSUE THREAD

**Issue by btknorr** [twilio/twilio-node#694]
### Issue Summary
client.messaging.brandRegistrations.create doesn't support the required field brandType that is needed when creating a STARTER brand.

### Code Snippet
```node
client.messaging.brandRegistrations.create({
  customerProfileBundleSid: 'your profile sid',
  a2PProfileBundleSid: 'your profile sid',
  brandType: 'STARTER'
})
```

BUT these are the only options supported:

```node
interface BrandRegistrationListInstanceCreateOptions {
  a2PProfileBundleSid: string;
  customerProfileBundleSid: string;
}
```

**Comment by JenniferMah** [comment]
Hi @btknorr! What version of the twilio-node library are you using? It looks like [brandType](https://github.com/twilio/twilio-node/blob/main/lib/rest/messaging/v1/brandRegistration.d.ts#L155) should be included in the `BrandRegistrationListInstanceCreateOptions` interface in the latest version of the twilio-node library.

**Comment by btknorr** [comment]
Ahhh...yep that's it...after upgrading to the latest we now have brandType.  Thanks!
