### ISSUE TITLE
403 error when using twilio.webhook() middleware on Express App with Custom Job

### ISSUE THREAD

**Issue by AbhilashG97** [twilio/twilio-node#701]
### Issue Summary

I get 403 error when I add validation to the webhook used by the [Twilio custom job](https://www.twilio.com/docs/usage/bulkexport/export-custom-job). Twilio custom job provides the ability to use a webhook which provides a notification when the logs are ready. 

I created the webhook using Express and in the POST route, I used `twilio.webhook()` middleware. I exposed the webhook using ngrok and I also passed the appropriate parameters to `twilio.webhook`. But I still get 403 when the custom job is complete.

I have gone through all closed and open issues on GitHub and I have also tried the suggestions mentioned in those issues but none of them have helped me so far. Any help with this issue would be really appreciated. 

### Steps to Reproduce

1. Create an Express app
2. Create a route that handles a POST request with the code mentioned in **Router** below.
3. Use ngrok to expose the PORT 3000 `npx ngrok http 3000`
4. Add the ngrok URL in the twilio.webhook() params
5. Run the express app
6. Create a custom job and pass the ngrok URL
7. View Express and ngrok logs

### Code Snippet

**app.js**

```javascript
"use strict";
require("dotenv").config();

var express = require("express");
var cookieParser = require("cookie-parser");
var logger = require("morgan");

var indexRouter = require("./routes/index");

var app = express();

app.use(logger("dev"));
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());

app.use("/", indexRouter);

module.exports = app;
``` 

**Router**

```javascript
const twilio = require("twilio");
var express = require("express");
var { fetchAndPushTwilioLogs } = require("../controller");
var router = express.Router();

/* GET home page. */
router.get("/", function (req, res, next) {
  res.send({
    app: "Upload Twilio Logs",
  });
});

/* POST twilio log to Kinesis */
router.post(
  "/",
  twilio.webhook(process.env.TWILIO_AUTH_TOKEN, {
    protocol: "https",
    host: "https://xxxxx.ngrok.io",
  }),
  async function (req, res) {
    const response = await fetchAndPushTwilioLogs(req.body.day);
    res.send(response);
  }
);

module.exports = router;
```

**createCustomJob.js**

```javascript
let customExportResponse = await client.bulkexports
  .exports("Messages")
  .exportCustomJobs.create({
    webhookMethod: "POST",
    webhookUrl: "https://xxxxx.ngrok.io",
    startDay: startDate,
    endDay: endDate,
    friendlyName: jobName,
  });
console.log(
  "Custom Export Job created successfully. Jobs details are shown below.\n\n",
  customExportResponse
);
```

### Exception/Log

```
403
Twilio Request Validation Failed.
```

### Technical details:
* twilio-node version: 3.67.0
* node version: v14.15.1

**Comment by AbhilashG97** [comment]
Hello, 

I have updated the issue with the complete error message.

The error message that I got was - `403: Twilio Request Validation Failed.`

I was able to work around this issue by following this blog post - https://www.twilio.com/blog/how-to-secure-twilio-webhook-urls-in-nodejs

The middleware sadly didn't work for me.

**Comment by shwetha-manvinkurke** [comment]
Can you show me the code where you initialize the `client`?

**Comment by eshanholtz** [comment]
Closing due to lack of customer response
