### ISSUE TITLE
Wrong typing for playbackGrant (PlaybackGrantContext)

### ISSUE THREAD

**Issue by twixr** [twilio/twilio-node#711]
### Issue Summary
![image](https://user-images.githubusercontent.com/5758900/143287397-fd1c339d-c601-4029-8814-83880e1292b1.png)
Full code line:
![image](https://user-images.githubusercontent.com/5758900/143286912-ad88bbcb-a222-47a5-ae4f-07c82a3194f1.png)

According to the docs: (https://www.twilio.com/blog/build-livestreaming-application-twilio-live-express)
![image](https://user-images.githubusercontent.com/5758900/143286980-05d3474b-af99-4de6-96c1-b86c70a36b64.png)

So I looked into the code: (https://github.com/twilio/twilio-node/blob/main/lib/rest/media/v1/playerStreamer.js#L567)
And it seems like the playback does not have any arguments.
Yet, the type declaration file says that sid (string) is required:
https://github.com/twilio/twilio-node/blob/main/lib/rest/media/v1/playerStreamer/playbackGrant.d.ts#L36

I might be wrong, but it seems like that sid argument shouldn't be there.

Tried to make a PR for it, but it is a generated file, hence the issue. :(  

### Technical details:
* twilio-node version: latest
* node version:

**Comment by JenniferMah** [comment]
This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.

**Comment by twixr** [comment]
I did make a PR, however the docs are telling me that it's a part of the code where no PR's will be accepted and we have to make an issue instead.

**Comment by childish-sambino** [comment]
Fixed by https://github.com/twilio/twilio-node/pull/814

This will be included in the first release candidate for twilio-node@v4 dropping this week.
