### ISSUE TITLE
Node 16 Support?

### ISSUE THREAD

**Issue by TechnotronicOz** [twilio/twilio-node#717]
Will Node 16 support be landing soon?

**Comment by Pic2490** [comment]
I just ran it with 16.3.0 and it works fine

**Comment by JenniferMah** [comment]
Hi @TechnotronicOz! We have a ticket in the backlog to add support for Node 16 and +1s on this issue summary will help it move up in the backlog.

**Comment by childish-sambino** [comment]
Fixed by https://github.com/twilio/twilio-node/pull/736
