### ISSUE TITLE
Export RestException type

### ISSUE THREAD

**Issue by Alko89** [twilio/twilio-node#719]
I use TypeScript

I have been looking through the code where I noticed there is an implementation of RestException, which is inherited from the standard Error class but is not exported.

Exporting this type would help implement error handling for Twilio exceptions using a middleware or in case of Nest.js using exception filters:
https://docs.nestjs.com/exception-filters#exception-filters-1

**Comment by eshanholtz** [comment]
The `RestException` type is exported [here](https://github.com/twilio/twilio-node/blob/main/lib/base/RestException.d.ts#L9) and can be imported with
```typescript
import { RestException } from "twilio/lib/base/RestException"
```

**Comment by Alko89** [comment]
I see, sorry about that :)
