### ISSUE TITLE
Typescript RecordingInstance: Property 'media' does not exist on type 'string' 

### ISSUE THREAD

**Issue by adyaksaw** [twilio/twilio-node#724]
### Issue Summary
In the [Twilio docs](https://www.twilio.com/docs/video/api/recordings-resource#recording-instance-resource), links attribute in the example is an object that contains a `media` attribute. But looking at the [type definition](https://github.com/twilio/twilio-node/blob/31c18138a7194aa83bc3cdd03c580e0d48ea2638/lib/rest/video/v1/recording.d.ts#L311), `links` is marked as a string. Is the defined class different with the docs one?

### Code Snippet
```node
const accountSid = process.env.TWILIO_ACCOUNT_SID;
const authToken = process.env.TWILIO_AUTH_TOKEN;
const client = require('twilio')(accountSid, authToken);

room_sid = "RMXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
participant_sid = "PAXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

const getRecordingQuery = { limit: 2, groupingSid: [room_sid, participant_sid] }
const recordingListResponse = await client.video.recordings.list(getRecordingQuery);

const videoRecording = recordingListResponse.filter(recording => recording.type === 'video');

const mediaResponse = await client.request({ method: "GET", uri: videoRecording[0].links.media }); // Error here
```

### Technical details:
* twilio-node version:  3.63.1
* node version: 14.15.4

**Comment by beebzz** [comment]
This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.

**Comment by claudiachua** [comment]
Closing as fixed in the RC branch: https://github.com/twilio/twilio-node/blob/4.0.0-rc/lib/rest/video/v1/recording.ts#L326

This will be included in the next release candidate for twilio-node@v4
