### ISSUE TITLE
Axios security update

### ISSUE THREAD

**Issue by stephenwade** [twilio/twilio-node#725]
Axios has been updated to v0.25.0. Among other things, it includes a fix for a [vulnerable dependency (follow-redirects)](https://github.com/axios/axios/pull/4379) that causes security warnings when using this package.

Can we get an update to `twilio` with the latest version of Axios? Thanks!

**Comment by eshanholtz** [comment]
This issue has been added to our internal backlog to be prioritized (reference ID: DI-1930). Pull requests and +1s on the issue summary will help it move up the backlog.

**Comment by childish-sambino** [comment]
Note that the issue is isolated to `v0.24.0`, and twilio-node uses `v0.21.x`: https://github.com/twilio/twilio-node/blob/83960a67721fe255194840ba2e4c171aec0fde55/package.json#L23

Note that semver for versions `0.x.x` treats minor versions as breaking.
