### ISSUE TITLE
axios xhrAdapter being used in nodejs

### ISSUE THREAD

**Issue by createvibe** [twilio/twilio-node#738]
### Issue Summary
Maybe I'm missing something, but after upgrading to the latest version (3.74.0), I'm noticing that the xhrAdapter is being used for axios.  I noticed "Refused to set unsafe header" for all the endpoints and so I made an interceptor to print the config. This is NOT running in a browser, it is running in nodejs v12.18.3.

When I bring the package back to our older version (3.29.2) I can see that `request:^2.88.0` is being used instead of axios.

Webpack is building my code using `target: 'node12',`

I'm also noticing an invalid cert error in the response.

Any help is appreciated. 

When I use the axios module packaged with our library, it works as expected. 

### Steps to Reproduce
see code snippet

### Twilio Code Snippet
```node
import twilio from 'twilio';
import axios, { AxiosRequestConfig } from 'twilio/node_modules/axios';

const client = twilio(TWILIO_ACCOUNT_SID, TWILIO_AUTH_TOKEN);

axios.interceptors.request.use((config: AxiosRequestConfig) => {
  console.log('axios config', config);
  return config;
});

// using the date from the documentation for deactivations api
client.messaging.deactivations().fetch({ date: new Date(Date.UTC(2020, 8, 5)) })
  .then(console.log)
  .catch(console.error);

```

### Exception/Log
```
adapter: [Function: xhrAdapter]
```

```
Refused to set unsafe header "Accept-Charset"
Refused to set unsafe header "Connection"
```

```
{
  ...
  responseText: "Error [ERR_TLS_CERT_ALTNAME_INVALID] [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: messaging.twilio.com. is not in the cert's altnames: DNS:*.s3.amazonaws.com, DNS:s3.amazonaws.com\n" +
      '    at Object.checkServerIdentity (tls.js:287:12)\n' +
      '    at TLSSocket.onConnectSecure (_tls_wrap.js:1511:27)\n' +
      '    at TLSSocket.emit (events.js:315:20)\n' +
      '    at TLSSocket.EventEmitter.emit (domain.js:483:12)\n' +
      '    at TLSSocket._finishInit (_tls_wrap.js:936:8)\n' +
      '    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:710:12)',
  ...
}
```

### Our Packaged Axios Code Snippet

```node
import axios, { AxiosRequestConfig } from 'axios';

axios.interceptors.request.use((config: AxiosRequestConfig) => {
  console.log('axios config', config);
  return config;
});

axios.request({
  url: 'https://messaging.twilio.com/v1/Deactivations?Date=2020-09-05',
  method: 'GET',
  headers: {
    'Authorization': 'Basic ' + Buffer.from(TWILIO_ACCOUNT_SID + ':' + TWILIO_AUTH_TOKEN).toString('base64'),
  },
}).then(console.log).catch(console.error);
```

```
adapter: [Function: httpAdapter]
```

```
{
  status: 200,
  statusText: 'OK',
  ...
}
```

### Technical details:
* twilio-node version: [3.74.0](https://github.com/twilio/twilio-node/releases/tag/3.74.0)
* twilio#axios@0.25.0
* axios@0.21.4
* node version: v12.18.3

**Comment by imthatcarlos** [comment]
+1 seeing the same issue on my end. On another project I've used version `3.50.0` with no issues, but on the latest version - seeing the same error as above.

**Comment by createvibe** [comment]
@imthatcarlos thanks for pointing that out. I would rule that issue out by trying with CURL - here's what I did to make sure the cert was valid and accepted on my sever before making this thread.

```
curl -v -s https://messaging.twilio.com/v1/Deactivations?Date=2020-09-05 \
-u $TWILIO_ACCOUNT_SID:$TWILIO_AUTH_TOKEN
```

```
*   Trying 54.204.149.76...
* TCP_NODELAY set
* Connected to messaging.twilio.com (54.204.149.76) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=Twilio, Inc.; CN=*.twilio.com
*  start date: Feb 19 00:00:00 2021 GMT
*  expire date: Feb 23 23:59:59 2022 GMT
*  subjectAltName: host "messaging.twilio.com" matched cert's "*.twilio.com"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert TLS RSA SHA256 2020 CA1
*  SSL certificate verify ok.
```

When I connect with Node's HTTP client I do not receive any request header warners and I do not receive the cert error.

**Comment by imthatcarlos** [comment]
nice, thanks @createvibe . I ultimately decided to drop the `twilio` lib in favor of just raw POST requests via axios. That lib increased the size of my lambda anyways.

**Comment by createvibe** [comment]
@childish-sambino thanks, I'm aware that `axios` uses `xhrAdapter` when running without `process` defined. I was confused why it was recognizing the the correct adapter for us but not for the packaged `axios` module in `twilio-node`. 

It seems like `axios` has the check for `XMLHttpRequest` before the check for `process` inside of `getDefaultAdapter`.  I found that `xmlhttprequest.js` is being hoisted by web3 and for some reason it's defined globally when `twilio/node_modules/axios` is calling `getDefaultAdapter`.

This code is not being used in a browser, it's in NodeJS on an Ubuntu Server.

That said, we can close this out. Thanks again.
