### ISSUE TITLE
Access Restriction Bypass url-parse

### ISSUE THREAD

**Issue by penfold45** [twilio/twilio-node#739]
### Issue Summary
I do not see anything here or on stackoverflow relating to this issue
so thought I would post it. There is a security issue inside 
url-parse https://security.snyk.io/vuln/SNYK-JS-URLPARSE-2401205

upgrading to the latest version appeartnly resolves the issue.

### Technical details:
* twilio-node version: 3.74

**Comment by JenniferMah** [comment]
Hi @penfold45! I've opened a PR to update this dependency. This update will be included in the next release on 2/23/22.
