### ISSUE TITLE
Missing "dtmf speech" type in VoiceResponse.GatherInput

### ISSUE THREAD

**Issue by alechko** [twilio/twilio-node#749]
### Issue Summary

The TwiML `<Gather>` input attribute supports `dtmf speech` but the library types are not.

### Steps to Reproduce
1. `<Gather>` input attribute documentation: https://www.twilio.com/docs/voice/twiml/gather#input
2. `VoiceResponse.GatherInput` type: https://github.com/twilio/twilio-node/blob/main/lib/twiml/VoiceResponse.d.ts#L218

### Technical details:
* twilio-node version:  "^3.75.1"
* node version: 16.0.0

**Comment by JenniferMah** [comment]
Hi @alechko!
Thanks for bringing this to our attention. `dtmf speech` was removed in [version 3.15.1](https://github.com/twilio/twilio-node/blob/main/CHANGES.md#2018-04-20-version-3151) of the twilio-node library. It looks like our documentation has not be updated to reflect this change. I'll reach out to our docs team to let them know about this mismatch.

**Comment by JenniferMah** [comment]
After further investigation, the code sample below should result in valid TwiML (`<?xml version="1.0" encoding="UTF-8"?><Response><Gather action="/pollResponse" numDigits="1" method="POST" input="dtmf speech"></Response>`)
``` node
const twiml = new VoiceResponse();

    const gather = twiml.gather({
        action: '/pollResponse',
        numDigits: '1', 
        method: 'POST',
        input: 'dtmf speech'
    });
```
Could you please elaborate on the problem that you are encountering while using the twilio-node library?

**Comment by alechko** [comment]
Sure, in typescript, if I want to use the type of VoiceResponse.GatherInput in order to see the possible values I cannot see or use the `dtmf speech` value. But if you say that it was removed from official TwiML support then I guess it's not relevant anymore.

For example:

<img width="687" alt="image" src="https://user-images.githubusercontent.com/1391846/166627944-f58ef24c-7634-493d-8c71-414b4ccd2220.png">

**Comment by beebzz** [comment]
Correct, you won't see it as an option in your IDE but using `dtmf speech` type will still work; the string will simply be treated as an enumerable and the first detected type (`dtmf` in this case) will be defaulted to.

**Comment by beebzz** [comment]
Correct, you won't see it as an option in your IDE but using `dtmf speech` type will still work; the string will simply be treated as an enumerable and the first detected type (`dtmf` in this case) will be defaulted to.

**Comment by alechko** [comment]
I understand that I can pass a string value to the method instead of using the library types, it's just very helpful when the package reflects the official docs and making the development workflow easier as one could look into the library instead of the official docs and avoid making mistakes :)

Please close this issue if no further action needed.
