### ISSUE TITLE
media.delete() on a media instance returns 404

### ISSUE THREAD

**Issue by cylinderStudio** [twilio/twilio-node#75]
When I create and send an MMS, I call a function in a separate fallback application using the statusCallback property. I'm trying to use that function to check for smsStatus of 'sent' and then delete any media instances that were created for a message from Twilio's servers.

I can get as far as actually listing the media instances, but attempting to delete them is a problem. I actually get a media list with media instances in the array, and the console.log statement in the if(err) block shows a value for mediaElement.sid, but the second console.log statement there shows err.status of 404.

```
if (req.body.SmsStatus === 'sent') {
		twilio_client.messages(req.body.MessageSid).media.list(function(err, data) {
			if (data.media_list.length > 0) {
				data.media_list.forEach(function(mediaElement) {
		    	twilio_client.messages(req.body.MessageSid).media(mediaElement.sid).delete(function(err, data) {
		    		if (err) {
				      console.log('Unable to delete Twilio media instance: ' + mediaElement.sid);
				      console.log('Error status: ' + err.status);
				    } else {
				      console.log('Twilio media instance ' + mediaElement.sid + ' deleted successfully.');
				    }
		    	});
		    });
			}
		});
	}
```

**Comment by kwhinnery** [comment]
Hi there - it's possible that there are some timing issues at play here with the API. If you attempt to delete the media resource associated with a message immediately after creating it, it can result in a 404 while our media service data becomes consistent.

Are you able to delete the media resources after a delay?

If this is not your issue, and for any future support requests, I would recommend starting with sending a note to help@twilio.com - we're happy to help you here if we can, but our response to GitHub issues is much slower than what you will experience with support.

Thanks,
-Kevin

**Comment by cylinderStudio** [comment]
Hi, Kevin. Thanks for responding.

No, I'm unable to do it after a delay. That's why I thought it may be an issue with the library. In the scenario above, the statusCallback is called after a couple of minutes at the soonest, and I've waited as long as hours to try and delete an instance with the same results. 

I've tried creating support requests by mailing help@twilio.com with no response in the recent past. I've submitted this particular issue directly to an engineer at Twilio and have had no response either. If you or someone you can ping is actively watching the help@twilio.com email address, I'm happy to try again and submit this issue there.

**Comment by kwhinnery** [comment]
Very sorry to hear about the troubles with the support channel -
help@twilio.com is the right e-mail, but if you can either reply to your
last message or create a new one with "kwhinnery@twilio.com" in CC I can
help make sure it gets sorted.

Thanks,
-Kevin

On Wed, Feb 11, 2015 at 11:29 AM, Cylinder Studio <notifications@github.com>
wrote:

> Hi, Kevin. Thanks for responding.
>
> No, I'm unable to do it after a delay. That's why I thought it may be an
> issue with the library. In the scenario above, the statusCallback is called
> after a couple of minutes at the soonest, and I've waited as long as hours
> to try and delete an instance with the same results.
>
> I've tried creating support requests by mailing help@twilio.com with no
> response in the recent past. I've submitted this particular issue directly
> to an engineer at Twilio and have had no response either. If you or someone
> you can ping is actively watching the help@twilio.com email address, I'm
> happy to try again and submit this issue there.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twilio/twilio-node/issues/75#issuecomment-73924177>.
>



-- 
*Kevin Whinnery@kevinwhinneryhttp://kevinwhinnery.com
<http://kevinwhinnery.com>*

**Comment by cylinderStudio** [comment]
Thanks, I appreciate it. Sorry I was wrong about it potentially being an issue with the library. I already re-quested to help@, but if I don't get a response, I'll forward along to you.
