### ISSUE TITLE
WebhookListInstanceCreateOptions incorrectly typed

### ISSUE THREAD

**Issue by canegru** [twilio/twilio-node#750]
### Issue Summary
Incorrect types for WebhookListInstanceCreateOptions used in conversations.conversations(conversationId).webhooks.create(opts)

Path: twilio\lib\rest\conversations\v1\conversation\webhook.d.ts

### Code Snippet
Works:

```typescript
        const createRequest = await this.client.conversations
            .conversations(conversationId)
            .webhooks.create({
                // @ts-expect-error incorrectly typed library
                'configuration.method': 'POST',
                'configuration.filters': ['onMessageAdded'],
                'configuration.url': conversationsUrl,
                'configuration.replayAfter': 0,
                target: 'webhook',
            });
```

Doesnt work: Twilio's backend throws an error that the request is invalid.

```typescript
        const createRequestNotWorking = await this.client.conversations
            .conversations(conversationId)
            .webhooks.create({
                configuration: {
                    method: 'POST',
                    filters: ['onMessageAdded'],
                    url: conversationsUrl,
                    replayAfter: 0,
                },
                target: 'webhook',
            });
```

### Note

Having prop notation with a dot in it is confusing, ideally, the way it's typed today should be the way we use it to create the conversations webhook.

### Technical details:
* twilio-node version: 3.76.1
* node version: 16.14.2

**Comment by beebzz** [comment]
Hi @canegru, thanks for reaching out. This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.

**Comment by beebzz** [comment]
In the meanwhile, can you post the exact error that you received?

**Comment by canegru** [comment]
Hey @beebzz, apologies, it was a filter issue - please close this as it's not a bug and the payload works as expected. I was passing onConversationAdded to a new webhook creation which is not allowed. 

Possibly add the available filters to the filter types instead of sting | string[]
