### ISSUE TITLE
Webhook middleware not working with Firebase cloud functions

### ISSUE THREAD

**Issue by Jordan-Loeser** [twilio/twilio-node#753]
### Issue Summary
When attempting to use the `webhook` middleware on a firebase cloud function, I am getting a `403 FORBIDDEN` response with  the message `Twilio Request Validation Failed`. The `TWILIO_AUTH_TOKEN` env variable is set and I've attempted to explicitly pass a `host` and `protocol` param with no luck.

The function is working correctly as a webhook without the middleware, so I believe something must just be misconfigured.

### Steps to Reproduce
1. Deploy the code below to firebase cloud functions
2. Send a message to the configured Twilio number

### Code Snippet
```node
import * as functions from "firebase-functions";
import { twiml, webhook } from "twilio";

exports.inboundSMS = functions.https.onRequest(async (req, res) => {
  webhook({
    host: "my-project-name.cloudfunctions.net",
    protocol: "https",
  })(req, res, async () => {
    // generate and send twiml response
  }
});
```

### Exception/Log
```
sourceComponent=14100&httpResponse=403&url=https%3A%2F%2Fus-central1-my-project.cloudfunctions.net%2FinboundSMS&ErrorCode=11200&LogLevel=ERROR&Msg=Forbidden&EmailNotification=false
```

### Technical details:
* twilio-node version: `^3.75.1`
* node version: `16`

**Comment by claudiachua** [comment]
Hi @Jordan-Loeser, in order to properly debug this issue, please [file a support ticket](https://twilio.com/help/contact).
