### ISSUE TITLE
Adding a full stop in sentence in README.md file

### ISSUE THREAD

**Issue by bishal7679** [twilio/twilio-node#762]
### Issue Summary
I know this is a very minor issue but it can be added a full stop in this below sentence.

![Screenshot (140)](https://user-images.githubusercontent.com/70086051/174471350-a9057b32-ace4-45a9-9cc6-487023cb0f5d.png)

**Comment by JenniferMah** [comment]
Hi @bishal7679,
Please feel free to submit a PR with this update to the read.me and our team will review it.
