### ISSUE TITLE
subresourceUris type is wrong

### ISSUE THREAD

**Issue by ianzone** [twilio/twilio-node#763]
![image](https://user-images.githubusercontent.com/20043230/174838472-ad08fbe9-1a26-4ab9-b0fa-faa871a7bf2e.png)

It should be an object.

### Technical details:
* twilio-node version: 3.77.3
* node version: v18.4.0

**Comment by beebzz** [comment]
Hey @ianzone, thanks for submitting this issue. It's been added to our internal backlog to be prioritized, +1s and pull requests on the issue summary will move it further up the backlog.

**Comment by EltonAlvess** [comment]
Can I get it?

**Comment by claudiachua** [comment]
Update: We are working on this and will be ready for the next release candidate.

**Comment by childish-sambino** [comment]
Closing as fixed: https://github.com/twilio/twilio-node/blob/3452c036543be32a512fcfefd63de62c96fd545c/lib/rest/api/v2010/account/call.ts#L713-L716

This will be included in the first release candidate for twilio-node@v4 dropping in a week.
