### ISSUE TITLE
Twillio message api pagination total,length,page methods are not available

### ISSUE THREAD

**Issue by sudha53633** [twilio/twilio-node#78]
Hi there,

How can i fetch twilio old sms, i couldn't read more that 50 recent message from message api. Would you please help me out to get all message.

Thanks,
Sudha

**Comment by kwhinnery** [comment]
Hi there,

Paging large result sets is possible but not yet elegant in this module.  First, you should consult this reference on how paging is handled at the REST API level:

https://www.twilio.com/docs/api/rest/response#response-formats-list-paging-information

The response data for any request that has pages contains this information.  If your result set isn't too large, you can simply pass in `pageSize: 1000` in your request parameters and increase the result set to 1000.  If you do in fact need to page, you'll need to pass in a custom URL for the next page of data:

```javascript
var twilio = require('twilio');
var accountSid = 'ACxxx';
var authToken = 'yyy';
var client = twilio(accountSid, authToken);
var baseUrl = 'https://' + accountSid + ': '+ authToken + '@' + client.host;

function handleResults(err, data) {
    if (err) {
        return console.error(err);
    }

    // do something with current page...
    console.log(data.messages);

    if (data.numPages > 1) {
        // request the next page in the janky way
        client.request({
            url: baseUrl + data.nextPageUri,
            qs: {
                // need to use actual REST API parameter - this method does not
                // massage inputs, it's pretty much a direct passthrough to 
                // the underlying HTTP client (mikeal/request)
                PageSize: 1000
            }
        }, handleResults);
    }
}

// fetch resources normally
client.listMessages({
    pageSize: 1000
}, handleResults);
```

We need to handle this better at the API level for sure.  If you have further support related requests, I would recommend sending a note to help@twilio.com, as GitHub issues are checked irregularly.

Thanks,
-Kevin

**Comment by sudha53633** [comment]
Hi Kevin,

Thanks for the quick response, It helps me a lot.

Thanks,
Sudhakar
