### ISSUE TITLE
Meteor Js unsupported on new JavaScript SDK

### ISSUE THREAD

**Issue by atakurt034** [twilio/twilio-node#785]
### Steps to Reproduce
1. This is the first step
 - Use latest version of twilio SDK on the browser with Meteor
2. This is the second step
 - Fetch token and initialize twilio SDK

Meteor version 2.6
twilio-sdk latest

**Comment by claudiachua** [comment]
Hi @atakurt034, Could you provide more details, code samples, and links for what you're trying to accomplish? If you are running the code on Client side, you will not be able to as this library is only for back-end application due to the potential exposure of your account credentials.

**Comment by beebzz** [comment]
Closing issue due to lack of response. Please re-open this issue or open a new GitHub issue if you still need help.
