### ISSUE TITLE
statuscallback events for outbound call, help me how to get a statuscall events the url i have given is the api which triggers aws lambda to get the callback events but im not getting , help me out in detail please

### ISSUE THREAD

**Issue by Ganesh9840** [twilio/twilio-node#786]
from twilio.rest import Client
# Find your Account SID and Auth Token at twilio.com/console
# and set the environment variables. See http://twil.io/secure
account_sid = '******************************************'
auth_token = '*******************************************'
client = Client(account_sid, auth_token)
call = client.calls.create(
                        method='GET',
                        status_callback='https://iztw9otfrc.execute-api.ap-south-1.amazonaws.com/dev/ivr_twiliocallback',
                        status_callback_event=['initiated', 'ringing','answered', 'completed'],
                        status_callback_method='POST',

                      
                        twiml='<Response><Say> hello Hi how can i help you please tell me </Say></Response>',
    
                    
                        to='to_number',
                        from_='from_number'
                    )

print(call.sid)

**Comment by claudiachua** [comment]
Hi @Ganesh9840 , please refer to this [documentation](https://www.twilio.com/docs/voice/make-calls#call-end-setting-your-statuscallback) on how to request status callbacks. 

Else, in order to properly debug this issue, please [file a support ticket](https://twilio.com/help/contact).
