### ISSUE TITLE
recordings.delete broken in 1.11.0

### ISSUE THREAD

**Issue by mrpetrocket** [twilio/twilio-node#79]
While using version 1.10.0 of twilio-node, I used a command like this to delete a recording:
```javascript
client.recordings(sid).delete(func callback(err){})
```
This works fine in 1.10.0. In 1.11.0, the recording is deleted off of the Twilio server, but the delete() call dies on line 147 of Client.js because the variable "data" is null. "data" is set to null on line 122 of Client.js because the variable "body" is empty.

I haven't dug further than this. Any thoughts?

**Comment by kwhinnery** [comment]
Thanks for the report - pushed https://github.com/twilio/twilio-node/commit/382e0d923a30daefe55253ea5bbc35de9b4be98e to fix. Will update npm soon.
