### ISSUE TITLE
TwiML Node Example

### ISSUE THREAD

**Issue by tejasmanohar** [twilio/twilio-node#80]
Is there an example of capturing dial-pad response during a call w/ TwiML through this node module?

**Comment by kwhinnery** [comment]
Not per se, but here's how it would look:

```javascript
var twiml = new twilio.TwimlResponse();

twiml.say('Press one for sales, two for support').gather({
    numDigits: 1
});

console.log(twiml.toString());
/*
the above outputs:
<Response>
<Say>Press one for sales, two for support</Say>
<Gather numDigits="1"></Gather>
</Response>
*/
```

All other TwiML verbs can be constructed in this way.  If you have further questions, please reach out to help@twilio.com, as the GitHub issues are not the fastest way to get support on the product.

**Comment by tejasmanohar** [comment]
@kwhinnery Got it! Thanks :+1:
