### ISSUE TITLE
twilio.validateExpressRequest broken on 1.11 works on 1.8

### ISSUE THREAD

**Issue by hthetiot** [twilio/twilio-node#81]
twilio.validateExpressRequest stoped validating twilio request properly on 1.11 but works on 1.8.
causing some outage on my side.

**Comment by wenzowski** [comment]
I'm seeing can't seem to generate a matching sha1 with either 1.11 or 1.8

**Comment by euclio** [comment]
I am getting this issue as well. Cannot generate the correct hash on 1.11 or 1.8.

**Comment by kwhinnery** [comment]
Hey all,

Sorry no one noticed this until now - we do have a passing test covering request signature, so there must be a case we haven't covered. If you can, could you provide the versions of twilio and Express you're using, as well as a fail case (url you're trying to validate, with params).

As general guidance, some of the default values provided by Express can vary depending on the deployment environment, so it's usually best to be explicit about the URL that's configured on the Twilio side.  You might try actually using the same value in code that you use in the Twilio admin console. Also, make sure you have mounted the body parser (urlencoded) middleware before attempting to validate the request signature.

**Comment by wenzowski** [comment]
working again with 2.2.0

**Comment by kwhinnery** [comment]
Please re-open if you can provide a failing test case - thanks...
