### ISSUE TITLE
LookupsClient in docs but not in module.

### ISSUE THREAD

**Issue by derekcaneja** [twilio/twilio-node#82]
I cannot seem to find the LookupsClient, but I see it in the docs: 
https://www.twilio.com/docs/api/rest/lookups

```
// Download the Node helper library from twilio.com/docs/node/install
// These vars are your accountSid and authToken from twilio.com/user/account
var accountSid = 'AC7425ab30a8809d5b4f714da8b3740860';
var authToken = "{{ auth_token }}";
var client = require('twilio').LookupsClient(accountSid, authToken);
 
client.phoneNumbers.get("+15108675309", function(error, number) {
    process.stdout.write(number.phoneNumber);
});
```

**Comment by skimbrel** [comment]
We should be getting an updated release out today. Thanks for your patience.

**Comment by vinnyglennon** [comment]
+1

**Comment by nemo** [comment]
Hey folks,

Any updates on this? It looks like you've already pushed out a 2.0.0 release but Lookup isn't in it?

**Comment by skimbrel** [comment]
Hey, apologies for the oversight here. I will make sure this gets out for you today.

**Comment by skimbrel** [comment]
Released. Thanks again for your patience.

**Comment by nemo** [comment]
Thanks!
