### ISSUE TITLE
Twilio create token iceServers type

### ISSUE THREAD

**Issue by jorgevrgs** [twilio/twilio-node#824]
### Issue Summary
A summary of the issue and the environment in which it occurs. If suitable, include the steps required to reproduce the bug. Please feel free to include screenshots, screencasts, or code examples.

### Steps to Reproduce
1. Create a twilio client
2. Get the token iceServers
3. Verify the type, currently `string[]`, expected `RTCConfiguration['iceServers']`

### Code Snippet
```node
const client = twilio();
client.tokens.create().then((token) => console.log(token.iceServers)).catch(console.error);
```

### Exception/Log

It seems to be:

```typescript
type iceServers = RTCConfiguration['iceServers']
```

Or

```typescript
type iceServers =  {
  urls: string;
  url?: string;
  username?: string;
  credentials?: string;
}[]
```

### Technical details:
* twilio-node version: v3.82.1
* node version: v18.12.0

**Comment by jorgevrgs** [comment]
Do you think that this solves the problem?

https://github.com/jorgevrgs/twilio-node/commit/a26225de021958515d07bb6fcfc6c634512f8a44

**Comment by mattcole19** [comment]
Thank you for bringing this up! This typing [exists](https://github.com/twilio/twilio-node/blob/4.0.0-rc/lib/rest/api/v2010/account/token.ts#L20) in our RC branch which is in development.
