### ISSUE TITLE
Wrong `PromptAttributes` interface implementation

### ISSUE THREAD

**Issue by asfo** [twilio/twilio-node#825]
### Issue Summary
Right now I'm following the docs to use `Pay.Prompt` noun but there is a problem while using TypeScript.

The interface includes the following:
```ts
export interface PromptAttributes {
  attempt?: number[];
  cardType?: PromptCardType[];
  errorType?: PromptErrorType[];
  for_?: PromptFor;
  requireMatchingInputs?: boolean;
}
```

And as we can see the attribute is `for_` (with the `_`) and inside the docs:
https://www.twilio.com/es-mx/docs/voice/twiml/pay/prompt#for

It's `for` only (without the `_`), if we try to use `Pay.Prompt` like the following:
```ts
const pay = twilioVoice.pay({
    ...
});
const paymentProcessing = pay.prompt({
    for: 'payment-processing',
});
```

It throws an error:
`Argument of type '{ for: string; }' is not assignable to parameter of type 'PromptAttributes'.`

So, we need to use `for_` but the Twilio parser does not detect `for_`.

Another thing is that it looks like the docs are also out of date:
The errorTypes are:
```ts
type PromptErrorType = 'timeout'|'invalid-card-number'|'invalid-card-type'|'invalid-date'|'invalid-security-code'|'internal-error'|'input-matching-failed';
```

And there is no `invalid-postal-code` for example when the current docs state that it is actually there. Maybe it could be another good idea to add the usage of the errorTypes inside the docs? so we know it's an array and how to use it with `cardType` could be really useful.

### Steps to Reproduce
1. Create a Twilio Serverless function
2. Add TS support
3. Use the `Pay` verb
4. Add the `Prompt` noun support

### Code Snippet
```ts
...
const twilioVoice = new VoiceResponse();
const pay = twilioVoice.pay({
    chargeAmount: 100,
    paymentConnector: '***',
    tokenType: 'one-time',
    paymentMethod: 'credit-card',
});
const paymentProcessing = pay.prompt({
    for: 'payment-processing',
});
...
```

### Exception/Log
```
src/app/functions/pay/index.ts:71:5 - error TS2345: Argument of type '{ for: string; }' is not assignable to parameter of type 'PromptAttributes'.
  Object literal may only specify known properties, but 'for' does not exist in type 'PromptAttributes'. Did you mean to write 'for_'?

71     for: 'payment-processing',
       ~~~~~~~~~~~~~~~~~~~~~~~~~
```

### Technical details:
* twilio-node version: ^3.80.0
* twilio/runtime-handler: ^1.25.0
* node version: 16.16.0
* typescript: 4.0.0
* ts-node: 10.7.0
* @types/node 17.0.21

### Workaround:
There is a workaround by adding `// @ts-ignore` above the line like:
```ts
const paymentProcessing = pay.prompt({
    // @ts-ignore
    for: 'payment-processing',
});
```

**Comment by claudiachua** [comment]
Hi @asfo , I've tried to recreate your issue but did not get the same error. In order to properly debug this issue, please [file a support ticket](https://twilio.com/help/contact).

**Comment by asfo** [comment]
@claudiachua how you are not able to reproduce my issue if literally, the interface is wrong... 🤔 can you share the code that was used for testing?

You can see the interface here:
https://github.com/twilio/twilio-node/blob/main/lib/twiml/VoiceResponse.d.ts#L630

You also can see that on an old commit:
![image](https://user-images.githubusercontent.com/829964/204352155-04c9e61b-e8cc-4454-aa9b-6e4fa80d99d0.png)

And even the docs are out of date, the `master-card` was replaced with `mastercard` but the docs still have the `master-card`:
![image](https://user-images.githubusercontent.com/829964/204352490-00531073-7fe9-4c62-8e10-516a8f5caee9.png)

Please, share your code, so I can test locally a brand-new service. Since I'm still facing this, and also I'm having even worst issues like not being able to hear properly the `wait` (` 'payment-processing'` option) it just says something like "Please wai..." and it got cut if I use a longer phrase (like the one on the docs).

Finally, here is a screenshot from an IDE with TS support:
![image](https://user-images.githubusercontent.com/829964/204352977-58d8b770-d9d9-472d-a208-49df7b1157b1.png)

You can see it's even warning me about the error and TypeScript throw it:
![image](https://user-images.githubusercontent.com/829964/204353114-48be41fb-6c30-4346-b85d-f5b22161716f.png)

I will try to ask a partner to also run this test locally to see if it's something more general at the moment.

**Comment by claudiachua** [comment]
Please [file a support ticket](https://twilio.com/help/contact) with regards to the docs issue, so the support team can assign it to the correct team responsible for it

**Comment by asfo** [comment]
![image](https://user-images.githubusercontent.com/829964/204369916-3c31f992-e595-442f-8d12-8faaacd92454.png)
Same error with that source but using imports 🤔 I think maybe is because I'm using some settings that affect and use the typings from the Twilio TS code.

![image](https://user-images.githubusercontent.com/829964/204370899-d870ccb8-5141-4837-83c2-8b205774272b.png)


Can you try the following @claudiachua?:

```json
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "module": "commonjs",
    "target": "es6",
    "outDir": ".",
    "rootDir": ".",
    "sourceMap": true,
    "strict": false,
    "esModuleInterop": true,
    "baseUrl": ".",
    "allowJs": true,
    "resolveJsonModule": true,
    "forceConsistentCasingInFileNames": true,
    "noUnusedLocals": true,
    "allowUnreachableCode": false,
    "skipLibCheck": true
  },
  "exclude": ["node_modules"]
}
```
```ts
import Twilio from 'twilio';

const VoiceResponse = Twilio.twiml.VoiceResponse;
const twilioVoice = new VoiceResponse();
const pay = twilioVoice.pay({
    chargeAmount: '100',
    paymentConnector: "***",
    tokenType: 'one-time',
    paymentMethod: 'credit-card'
});
const paymentProcessing = pay.prompt({
    for: 'payment-processing'
});
console.log(paymentProcessing.toString());

```
If needed on the deps on package.json
```json
"dependencies": {
    "twilio": "^3.83.3"
  },
  "devDependencies": {
    "@types/node": "^18.11.9",
    "typescript": "^4.9.3"
  }
  ```

You should be able to see the error 🤔

**Comment by claudiachua** [comment]
@asfo I'm seeing the error now. Thank you for raising this issue. Since the change is required in a generated file, we'll need to make changes in the internal upstream generator. This issue has been added to our internal backlog to be prioritized (Internal Ref: DI-1419). 

current workarounds is to either:
1.  use commonjs `require` statement instead of `import`
e.g. `const VoiceResponse = require('twilio').twiml.VoiceResponse;` , or
2. use `for_` instead of `for`

**Comment by asfo** [comment]
> @asfo I'm seeing the error now. Thank you for raising this issue. Since the change is required in a generated file, we'll need to make changes in the internal upstream generator. This issue has been added to our internal backlog to be prioritized (Internal Ref: DI-1419).
> 
> current workarounds is to either:
> 
> 1. use commonjs `require` statement instead of `import`
>    e.g. `const VoiceResponse = require('twilio').twiml.VoiceResponse;` , or
> 2. use `for_` instead of `for`

Thanks! 🙌

The second workaround doesn't work since the XML is generated like <Prompt for_="...> and Twilio ignores this because the `for_` is not valid, but we used: `// @ts-ignore` so Ts ignores that specific line and it works :) 

I really appreciate your help!

**Comment by Hunga1** [comment]
I'll be leaving this issue open as it has been added to our internal backlog (Internal Ref: DI-1419).

**Comment by Hunga1** [comment]
With the 4.7.0 release and beyond, the issue regarding the `PromptAttributes.for` interface property has been addressed. Please upgrade to the latest version of the library for the fix.
