### ISSUE TITLE
errors should inherit from the Error object

### ISSUE THREAD

**Issue by kevinburkeshyp** [twilio/twilio-node#83]
currently twilio errors are represented as a dictionary:

``` javascript
            error = {};
            // response is null if server is unreachable
            if (response) {
                error.status = response.statusCode;
                error.message = data ? data.message : 'Unable to complete HTTP request';
                error.code = data && data.code;
                error.moreInfo = data && data.more_info;
            } else {
                error.status = err.code;
                error.message = 'Unable to reach host: "'+client.host+'"';
            }
```

it would be better if errors inherited from the Error js object. there are a few reasons for this:
- Error objects have stack traces, which help you nail down where they originate
- makes it possible for someone to throw a Twilio error (currently a dictionary). the JS behavior for throwing/catching non-Error objects is wonky at best and handling varies by library
- mocha, raven-node behave oddly when you're using them without an Error object.

It would be pretty straight forward to add considering there is already a `message` property on the object.

**Comment by kevinburkeshyp** [comment]
here's the wrapper we're using:

```javascript
TwilioError = (function() {
  function TwilioError(message, status, code, moreInfo) {
    this.message = message;
    this.status = status;
    this.code = code;
    this.moreInfo = moreInfo;
    // handle the case where you don't invoke this with `new`
    if (!(this instanceof TwilioError)) {
      return new TwilioError(this.message);
    }
    Error.call(this);
    Error.captureStackTrace(this, arguments.callee);
    this.name = this.constructor.name;
  }

  TwilioError.prototype = Object.create(Error.prototype);

  TwilioError.prototype.constructor = TwilioError;

  return TwilioError;

})();
```

**Comment by dougblack** [comment]
Hey @kwhinnery do you have time to take a look at this?

**Comment by kevinburkeshyp** [comment]
hey folks, any update here ?

**Comment by kevinburkeshyp** [comment]
hey folks - anything I can do to help this along? we just got bit by this again.

**Comment by carlosdp** [comment]
@kevinburke the 3.x RC implemented this

**Comment by kevinburkeshyp** [comment]
sweet!

**Comment by jingming** [comment]
This has shipped as part of the `3.x.x` line!
