### ISSUE TITLE
RC version error Cannot find module '../interfaces' or its corresponding type declarations

### ISSUE THREAD

**Issue by csravya9** [twilio/twilio-node#867]
### Issue Summary
Using RC version after commit 522d897ba2257c6176ae0d3cc36a41c593c98ba7(chore: upgrade jsonwebtoken from 8.5.1 to 9.0.0 (https://github.com/twilio/twilio-node/pull/847)). Tried all commits after the one above and see Issue on Mac.

### Steps to Reproduce
1. Add RC version to Package.json 
"twilio": "github:twilio/twilio-node#1508e52e712ad3e837571b26148dad6af92b8081",
2. Try to install, audit and run to see the errors

### Exception/Log
```
[node_modules/twilio/dist/lib/base/BaseTwilio.d.ts#L3]
Cannot find module '../interfaces' or its corresponding type declarations.
[node_modules/twilio/dist/lib/base/RequestClient.d.ts#L2]
Cannot find module '../interfaces' or its corresponding type declarations.
[node_modules/twilio/dist/lib/http/request.d.ts#L2]
Cannot find module '../interfaces' or its corresponding type declarations.
```

### Technical details:
* twilio-node version: RC version after commit 522d897ba2257c6176ae0d3cc36a41c593c98ba7(chore: upgrade jsonwebtoken from 8.5.1 to 9.0.0 (https://github.com/twilio/twilio-node/pull/847)). 
* node version:18.12.1

**Comment by childish-sambino** [comment]
Thanks for reporting this! Fix submitted pending review.
