### ISSUE TITLE
Support paging via nextpageuri

### ISSUE THREAD

**Issue by alexcchan** [twilio/twilio-node#87]
This is a feature request to support paging via the nextpageuri attribute included in list GET responses.

**Comment by comster** [comment]
+1

**Comment by comster** [comment]
Any docs on how to do this currently?  Manually call client.request with the nextPageUri?

**Comment by comster** [comment]
is the example in #11 still the best way to page?

**Comment by zawadzkip** [comment]
+1

**Comment by tmcpro** [comment]
+1

**Comment by jingming** [comment]
hey! thank you all for writing in!

We are currently working on this implementing auto paging in our `next-gen` version! Feel free to try out the `rc` line of libraries! We would love to hear any feedback that you may have!

**Comment by natesilva** [comment]
@jingming Is there documentation for the `rc` libs?

**Comment by jingming** [comment]
This has shipped in the `3.x.x` version of the library!
