### ISSUE TITLE
jsonwebtoken vulnerability

### ISSUE THREAD

**Issue by maniekins** [twilio/twilio-node#887]
Do you want to update 'jsonwebtoken' dependency? Version below 9.0.0 thorws issue with vulnerability.

**Comment by isha689** [comment]
Hi @maniekins, this looks like a duplicate issue #884.

We have update our twilio-node v4 release candidate to v9: https://github.com/twilio/twilio-node/blob/4.0.0-rc/package.json#L26

**Comment by maniekins** [comment]
Oh, Thanks a lot. Sorry for duplication. Thank you for the answer!
