### ISSUE TITLE
Any worries about JWT vulnerability?

### ISSUE THREAD

**Issue by tinisi** [twilio/twilio-node#89]
Folks,
I am digging through our NPM packages after seeing the article below about possible token vulnerabilities.

https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/

It looks like jwt-simple patched something recently that relates, and y'all are requiring an older version.

Are you concerned about this? Any plans to upgrade your dependency to 0.3.0?

Thanks much!

Jason

**Comment by skimbrel** [comment]
Hey,

Thanks for checking in. From my understanding of the vulnerability disclosure, it only applies to code using the affected libraries to validate (not generate) tokens signed with asymmetric encryption algorithms. The only use of jwt-simple in twilio-node is for token generation, so we're unaffected here. We've also audited all of the services in the Twilio platform that verify JWTs and we aren't using any of the affected libraries on our end. I'm still happy to accept a tested PR bumping the dependency if that will reassure people though!

**Comment by tinisi** [comment]
I think for our purposes your assurance that you've done an audit is enough for now.

Just trying to do my due diligence ;-)

And thanks for the quick reply!
