### ISSUE TITLE
jsonwebtoken Use of a Broken or Risky Cryptographic Algorithm

### ISSUE THREAD

**Issue by skt1598** [twilio/twilio-node#891]
Introduced through:  twilio@3.84.1 › jsonwebtoken@8.5.1 

Affected versions of this package are vulnerable to Use of a Broken or Risky Cryptographic Algorithm such that the library can be misconfigured to use legacy, insecure key types for signature verification. For example, DSA keys could be used with the RS256 algorithm. 
Ref: https://security.snyk.io/vuln/SNYK-JS-JSONWEBTOKEN-3180026

**Comment by isha689** [comment]
Duplicate Issue https://github.com/twilio/twilio-node/issues/846
We have updated our twilio-node v4 release candidate to v9
