### ISSUE TITLE
Installing v4 with a caret range with Yarn retrieves a 5 year old deprecated version

### ISSUE THREAD

**Issue by jthele** [twilio/twilio-node#896]
### Issue Summary
Installing v4 with a caret range with Yarn retrieves a 5 year old deprecated version

### Steps to Reproduce

Using Yarn v1.22.19 in an empty directory:

1. `yarn add twilio@^4.0.0-rc.5`

Notice this actually installed 4.6.0:
```
success Saved 67 new dependencies.
info Direct dependencies
└─ twilio@4.6.0
info All dependencies
...
```

### Technical details:
* There appears to have been a typo in a 3.6.0 release 5 years ago that produced this 4.6.0 version:  https://www.npmjs.com/package/twilio/v/4.6.0
* I tried NPM v9.2.0 and v8.19.3 and did not see this behavior, so this may be specific to how Yarn handles deprecated versions when caret range matching.

**Comment by mattcole19** [comment]
Thank you for creating this issue! However, I was unable to re-create it. 

When I run `yarn add twilio@^4.0.0-rc.5`, I get the following output: `no matches found: twilio@^4.0.0-rc.5`

I will be closing this issue, but it can be reopened if the issue appears again.
