### ISSUE TITLE
Can you please update jsonwebtoken to version 9.0.0?

### ISSUE THREAD

**Issue by salsabea** [twilio/twilio-node#900]
### Issue Summary
jsonwebtoken has 4 critical vulnerabilities as mentioned in https://github.com/auth0/node-jsonwebtoken/security/advisories and these are fixed in version 9.0.0

### Technical details:
* twilio-node version: 3.84.1
* node version: ">=6.0"

**Comment by shrutiburman** [comment]
Duplicate issue https://github.com/twilio/twilio-node/issues/846 Please refer that for details.

**Comment by vetlevo** [comment]
I think they were gonna release v4 soon (today as per last comment I saw). However, I'm not sure if that was a solid date or anything. It's a bit difficult to know when there is no public release schedule.

**Comment by childish-sambino** [comment]
Yes, it's today in a few hours.
