### ISSUE TITLE
NPM still reporting "current" version as `3.84.1`, not `4.7.1`

### ISSUE THREAD

**Issue by jdpowell1** [twilio/twilio-node#912]
It's causing quite a lot of headaches when updating packages in our mono repo. The `latest` tag needs to be added to the published version `4.7.1` so it shows as the latest version in NPM.

Link: https://www.npmjs.com/package/twilio?activeTab=versions

**Comment by mattcole19** [comment]
Thanks for bringing this up! We just added the `latest` tag to version 4.7.1
