### ISSUE TITLE
better error message when no credentials

### ISSUE THREAD

**Issue by ralyodio** [twilio/twilio-node#915]
The error message doesn't indicate the error is from twilio.

Please add "Username is required.....*for twilio*" i spent 2 days trying to figure out where the error "Username is required" is coming from.

**Comment by sbansla** [comment]
Hi @ralyodio 
Thank you for opening issue. Let me check it within the team.
 +1s on the issue summary will help it to understand the priority.

**Comment by claudiachua** [comment]
Hi @ralyodio, we have raised this issue to our team and will take it into future consideration.
