### ISSUE TITLE
How do I use the Messages resource instead of SMS so that I can send messages longer than 160 characters?

### ISSUE THREAD

**Issue by jamauro** [twilio/twilio-node#92]
It looks like SMS/Messages has been deprecated in favor of Messages. How can I leverage Messages to send messages greater than 160 characters? For reference: https://www.twilio.com/docs/api/rest/sending-messages

**Comment by skimbrel** [comment]
Just send a Body parameter longer than 160 characters to the Messages endpoint and Twilio will automatically segment it into 160-character messages for delivery to the recipient. The `sendMessage` function on the `RestClient` object uses the new /Messages endpoint.

Note that Twilio bills per message, not per request, so a long message split up into multiple parts will charge for each part individually.

**Comment by jamauro** [comment]
Cool. I was using a meteor package that was wrapping an older version of the api. Thanks!
