### ISSUE TITLE
Do not send `process.env` by default to twilio servers

### ISSUE THREAD

**Issue by kasvith** [twilio/twilio-node#931]
### Issue Summary
Currently, Twilio SDK Client sends `process.env` of the current process to the Twilio servers by default. Most people are using `process.env` to store sensitive data like passwords/secrets etc. Since the Twilio client sends these data to the backend using default settings people may unknowingly send sensitive information to Twilio servers.

This is a security vulnerability that must be resolved immediately.

```js
const client = new Twilio(sid, token) // <-- sends process.env by default to the twilio servers
```

Code: https://github.com/twilio/twilio-node/blob/972358a298b1ebfaeddffe913b7b9768e2969a95/src/base/BaseTwilio.ts#L78

### Technical details:
* twilio-node version: latest
* node version: 18.x

**Comment by AsabuHere** [comment]
Hi @kasvith, This issue has been fixed and merged to use only required twilio specific values from process.env instead of loading them all. The changes will be available from next release
Thanks,
Athira
