### ISSUE TITLE
`env` should not be assigned to `process.env`

### ISSUE THREAD

**Issue by titanism** [twilio/twilio-node#938]
```sh
node_modules/twilio/lib/base/BaseTwilio.js
36:            this.env = this.opts.env || process.env;
```

This line exposes the entire `process.env` to the client, which is unnecessary.

Without explicitly setting `env` option, it sets this entire object in memory.

If someone were to log the `client` object, then this too would be exposed, which is a security issue.

Please remove change this line of code:

```diff
-this.env = this.opts.env || process.env;
+this.env = this.opts.env || {};
```

**Comment by AsabuHere** [comment]
Hi @titanism, I have merged the fix for this issue to refer only twilio specific required values from process.env and not loading all of them. Fix will be available from next release
Thanks,
Athira
