### ISSUE TITLE
Getting a SyntaxError: Unexpected token . , It works on local system, but does'nt work on server

### ISSUE THREAD

**Issue by ajithv11** [twilio/twilio-node#940]
Hi,

Getting a SyntaxError: Unexpected token . , It works on local system, but does'nt work on server, Unfortunately I don't have much details to share here, I got only the line of code where the error happens

```
/var/www/server/node_modules/twilio/lib/rest/Twilio.js:34
if (this.opts?.lazyLoading === false) {
```

My nodejs version on server is v10.19.0  Does this cause the issue?

By the way my local nodejs version is v12.22.9

**Comment by shrutiburman** [comment]
Hi @ajithv11, 
Yes, please try upgrading to Node v12. It'd be great to upgrade to Node v14+ [(as these are the officially supported node versions)](https://github.com/twilio/twilio-node#supported-nodejs-versions). Thanks

**Comment by ajithv11** [comment]
@shrutiburman  Fixed the issue by upgrading Nodejs version on the server

**Comment by shrutiburman** [comment]
That's great. Closing this issue then. Please feel free to open a new one in case any issue occurs. Thanks!
