### ISSUE TITLE
Missing ForwardedFrom attribute 

### ISSUE THREAD

**Issue by justsomeofl** [twilio/twilio-node#948]
I did set up a webhook on a french phone number (+33). 
Then I made a call to another phone number that is forwarding to the webhook phone number. 
But the ForwardedFrom attribute is missing. Is it the expected behavior?

**Comment by justsomeofl** [comment]
Hi @AsabuHere, 

here are the other fields:

```
{
  AccountSid: 'AXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  ApiVersion: '2010-04-01',
  CallSid: 'CXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  CallStatus: 'ringing',
  Called: '+331XXXXXXXX',
  CalledCity: '',
  CalledCountry: 'FR',
  CalledState: '',
  CalledZip: '',
  Caller: '+337XXXXXXXX',
  CallerCity: '',
  CallerCountry: 'FR',
  CallerState: '',
  CallerZip: '',
  Direction: 'inbound',
  From: '+337XXXXXXXX',
  FromCity: '',
  FromCountry: 'FR',
  FromState: '',
  FromZip: '',
  To: '+331XXXXXXXX',
  ToCity: '',
  ToCountry: 'FR',
  ToState: '',
  ToZip: ''
}
```

```
const call = await client.calls(request.body.CallSid)
        .fetch();

console.log("ForwardedFrom", request.body.CallSid, request.body.ForwardedFrom, call?.forwarded_from); 
//ForwardedFrom CXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX undefined undefined
```

Thanks

**Comment by AsabuHere** [comment]
Can you try accessing the attribute from call like this
client.calls
      .create({
         url: 'http://demo.twilio.com/docs/voice.xml',
         to: '+1XXXXXXXXX',
         from: '+1XXXXXXXXX'
       })
      .then(call => console.log(call.forwardedFrom));
I can access the value like this in the latest version of twilio-node

**Comment by justsomeofl** [comment]
I am able to access it with the way you mentionned.
But when i catch a real call redirected to a webhook, this attribute is missing.
Maybe this value is filled only for twilio created calls ?

**Comment by tiwarishubham635** [comment]
Hi @justsomeofl! I rechecked it again and I am able to get the `forwardedFrom` field in the response of fetch. In my case it is not showing undefined. Can you recheck again?
I will list my steps here:
1. I followed this [documentation](https://www.twilio.com/docs/voice/api/call-resource)
2. I created a call resource using [this](https://www.twilio.com/docs/voice/api/call-resource#create-a-call-resource)
3. Then I fetched the call using [this](https://www.twilio.com/docs/voice/api/call-resource#create-a-call-resource)
4. The response had forwardedFrom field as expected. It was set to `null` in my case.

Please let me know if we are doing something differently. Thanks!

**Comment by tiwarishubham635** [comment]
Closing this as no response received
