### ISSUE TITLE
RestExceptionError interface is incorrect

### ISSUE THREAD

**Issue by dremin** [twilio/twilio-node#950]
### Issue Summary
The [RestExceptionError interface's `code` property](https://github.com/twilio/twilio-node/blob/e3d6e80f3/src/base/RestException.ts#L4C13-L4C13) has an incorrect type. It should be string instead of number. For example, I am receiving `code: 'ECONNRESET'` in error objects, and that is definitely not a number :)

### Technical details:
* twilio-node version: 4.14.0
* node version: 16.20.0

**Comment by sbansla** [comment]
Hi @dremin,
We have added this to our backlog.

**Comment by sbansla** [comment]
We have created internal ticket.

**Comment by sbansla** [comment]
Hi @dremin,
Can you give more details about the api you are calling and the error you are getting ?

**Comment by tiwarishubham635** [comment]
Closing this issue as no feedback was received in last 30 days
