### ISSUE TITLE
IreAdewolu wants to pay 0 USD to have this issue fixed

### ISSUE THREAD

**Issue by Ireadewolu** [twilio/twilio-node#951]
Testing mintycode with Twilio SDK 
 For more details visit [https://mintycode.io](https://mintycode.io/profile?action=CREATOR_SUPPORT_MODAL&requestId=45bf626e-fdd3-4e21-8360-96e6b19c839c&owner=twilio&name=twilio-node)

**Comment by sbansla** [comment]
Hi @Ireadewolu,
Can you elaborate on the issue?

**Comment by tiwarishubham635** [comment]
Closing this issue as no feedback received in last 30 days
