### ISSUE TITLE
If you pass mediaUrl:undefined to the sendMessage function, no call is made

### ISSUE THREAD

**Issue by jonathankeebler** [twilio/twilio-node#96]

**Comment by skimbrel** [comment]
Can you clarify a bit more? By "no call is made" do you mean the client doesn't emit an HTTP request to Twilio, or that Twilio doesn't do anything in response?

**Comment by jonathankeebler** [comment]
Traced it a bit more and I'm getting this reply from Twilio API: 
```
{ status: 400,
  message: 'Media urls:  are invalid. Please use only valid http and https urls',
  code: 21620,
  moreInfo: 'https://www.twilio.com/docs/errors/21620' }
```

I'm working on a patch.

**Comment by skimbrel** [comment]
What would you like to patch in the library for this? The library shouldn't be responsible for validating all parameters of all REST requests, as that's already implemented in the actual API handler.

**Comment by jonathankeebler** [comment]
It was a feature not a bug ;)
