### ISSUE TITLE
Error :  Secondary Customer Profile for direct_customer can only be created through Twilio console.

### ISSUE THREAD

**Issue by Neeraja-Reddy-1** [twilio/twilio-node#965]
While creating CustomerProfilesResource using policy sid - **RNdfbf3fae0e1107f8aded0e7cead80bf5**
Getting this error - Secondary Customer Profile for direct_customer can only be created through Twilio console.

**Comment by Neeraja-Reddy-1** [comment]
What can be issue ?

**Comment by ev-pragma** [comment]
I'm getting the same error using that Policy SID.
Is that the correct Policy to create Secondary Customer Profiles?

Because I'm getting the same error even if I try:
```
...
attributes: {
  business_identity: "isv_reseller_or_partner",  //  "unknown" does not work either.
},
...
```

**Comment by ev-pragma** [comment]
> What can be issue ?


Ok, I think I figured it out,
you can read it here:
https://www.twilio.com/docs/messaging/compliance/a2p-10dlc/onboarding-isv-api

```
In order to register secondary profiles,
the primary customer profile needs to have "ISV Reseller or Partner" selected as your Business Identity.
```


Still, not sure, I need to run some tests, but in order to do so, I need to change my Primary Customer Profile to  `isv_reseller_or_partner`

**Comment by tiwarishubham635** [comment]
Closing this issue as no response was received
