### ISSUE TITLE
Pass Cookies in sendMessage method

### ISSUE THREAD

**Issue by trever** [twilio/twilio-node#97]
I'm looking to pass a `headers['Set-Cookie']` value into the method's option argument.

Use Case: App sends an hourly text message to a user and expects a response. On the cron job's execution (sending the SMS), it should tag that message with a "session identifier". On the next job execution it creates a new session. That way, if the user fails to respond to the first SMS, but does respond to the second, session integrity is maintained. 

Thoughts?

**Comment by skimbrel** [comment]
Unfortunately this functionality isn't available in the Twilio REST API. Cookies are supported by the Twilio TwiML engine, which I'm guessing is what you saw in our documentation (https://www.twilio.com/docs/api/twiml/sms/your_response), but you'll need to have an inbound message from the user first to set a cookie on the session.

**Comment by trever** [comment]
Got it. Yeah, I was referring to this - https://www.twilio.com/blog/2014/07/the-definitive-guide-to-sms-conversation-tracking.html but didn't read toward the bottom where it says exactly what you mentioned.

I'll close now.

Thanks!
