### ISSUE TITLE
Publish 4.19.1?

### ISSUE THREAD

**Issue by theogravity** [twilio/twilio-node#982]
Need to pick up the axios security update.

**Comment by abrom** [comment]
#971 isn't in [4.19.1](https://github.com/twilio/twilio-node/tree/4.19.0)

See https://github.com/twilio/twilio-node/compare/4.19.1...main

It would presumably be in 4.19.2.. but yes, also looking for the release 😄

**Comment by tiwarishubham635** [comment]
Hi! The changes of #971 have been recently merged. They will be reflected in our coming release on this thursday

**Comment by yhou2021** [comment]
@tiwarishubham635 Will there be a release today?

**Comment by azakero** [comment]
@tiwarishubham635 will there be a release today? (2)

**Comment by theogravity** [comment]
@tiwarishubham635 ill there be a release today? (3)

**Comment by AsabuHere** [comment]
There is no release planned for today. Next release is scheduled on Nov 30

**Comment by yangsu-ab** [comment]
seems like 4.9.1 released failed due to testing. as well as the 4.9.2 release failed today due to testing as well. is that expected? if the tests continue to fail nothing will be deployed?

**Comment by Aeolun** [comment]
@AsabuHere  It would be very nice to have a release here.

**Comment by theogravity** [comment]
@tiwarishubham635 Checking up on this.

**Comment by theogravity** [comment]
Oh I see it in the package.json def.
