### ISSUE TITLE
Question about task_queue_bulk_real_time_statistics 

### ISSUE THREAD

**Issue by e-l-i-s-e** [twilio/twilio-node#986]
### Issue Summary
Hello 👋, I wonder if someone could clarify something for me. The [changelog](https://github.com/twilio/twilio-node/blob/main/CHANGES.md#2023-10-19-version-4190) says that in v4.19.0 the `task_queue_bulk_real_time_statistics` endpoint should no longer be in beta. But I don't see this api in the `twilo-node` library. 

The bulk queue realtime statistics api looks like it's only in the `twilio-go` [library](https://github.com/twilio/twilio-go/blob/main/rest/taskrouter/v1/model_taskrouter_v1_task_queue_bulk_real_time_statistics.go). Will this be added to the `twilio-node` library soon? Or is there another way that we could to access that api  (using `twilio-node` instead of making an http request to https://taskrouter.twilio.com/v1/Workspaces/WSxxx/TaskQueues/RealTimeStatistics)?

**Comment by tiwarishubham635** [comment]
Hi! We have added the API in this SDK as part of the major version release 5.0.0. You can find it [here](https://github.com/twilio/twilio-node/blob/main/src/rest/taskrouter/v1/workspace/taskQueue/taskQueueBulkRealTimeStatistics.ts). Thanks!

**Comment by tiwarishubham635** [comment]
Closing this issue as no updates were received in last 30 days.
