### ISSUE TITLE
LookupClient undefined

### ISSUE THREAD

**Issue by unChaz** [twilio/twilio-node#99]
Using version 2.2.1, requiring the LookupsClient as documented returns undefined.

```javascript
lookupsClient.phoneNumbers.get(...
```
I was getting the error: 
> TypeError: Cannot read property 'phoneNumbers' of undefined

So I added a log:
```javascript
var lookupsClient = require('twilio').LookupsClient(accountSID, authToken);
console.log('lookup client', lookupsClient);
```
Yields:
> lookup client undefined

I should add that I haven't had any issues with the main Twilio module and sending SMS.

**Comment by skimbrel** [comment]
Bah. This is a bug in the documentation. You need `new` in front of the LookupsClient constructor.

Thanks for pointing this out; we'll fix it ASAP.

**Comment by unChaz** [comment]
Thanks for the fast response. I found another error in the documentation.

It says to use
```javascript
lookupClient.phoneNumbers.get(phone, function(error, number) {
```
Which throws the error
> TypeError: object is not a function

Changing it to this will fix it:
```javascript
var phoneNumbers = lookupClient.phoneNumbers(phone);
phoneNumbers.get(function(error, number) {
```

**Comment by justingosan** [comment]
The documentation (https://www.twilio.com/docs/api/rest/lookups) for this is completely misleading. I had to stumble into this issue in order to get things working. Please fix ASAP.

**Comment by ganoro** [comment]
Just to have a full example that should work:

    var LookupsClient = require('twilio').LookupsClient
    var lookupsClient = new LookupsClient('', '');
    var phoneNumbers = lookupsClient.phoneNumbers(phoneNumber);
    phoneNumbers.get(function(error, number) {
    });

**Comment by kwhinnery** [comment]
Sorry for the issues here - the docs should be fixed now.
