### ISSUE TITLE
update you readme ffs. 

### ISSUE THREAD

**Issue by ralyodio** [twilio/twilio-node#990]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/twilio/twilio-node/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/twilio/twilio-node/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/twilio/twilio-node/issues) for a feature request that matches the one I want to file, without success.
- [X] This is not a general Twilio feature request or bug report. It is a feature request for the twilio-node JavaScript package.

### Problem Description

give me an example with esm 2022  modules

### Proposed Solution

give me an example with esm 2022  modules

### Alternatives Considered

give me an example with esm 2022  modules

### Additional Information

give me an example with esm 2022  modules

**Comment by Spacey4K** [comment]
Here's an example on how to import with esm modules.
```ts
import Twilio from "twilio";
const client = Twilio(accountSid, authToken);
```

**Comment by celesteking** [comment]
Twilio doesn't give a shit. It's no longer a dev first platform.

**Comment by tiwarishubham635** [comment]
Hi folks! Here is an example to use twilio with es module.
```node
import twilio from 'twilio'

const accountSid = 'xxx'
const authToken = 'xxx'
const client = twilio(accountSid, authToken)

client.messages
  .create({
      body: 'Hello from Twilio',
      from: '+1xxx',
      to: '+1xxx'
  })
  .then(message => {
    console.log(message.sid)
  })
```
Make sure you have `"type": "module"` present in your package.json. Thanks!

**Comment by tiwarishubham635** [comment]
Closing this issue as no update was received in last 30 days
